import pathlib,subprocess,json,copy,hashlib
W=pathlib.Path('D:/spheres-offload/codex-next-20260928/review-su35');E=W.parent/'su35-review';p='docs/campaign-certification/C01/research/ussr.json';ref='9d97caa982f9dfc03aeda4fdb87d6d584dfad6a4'
a=json.loads((W/p).read_text(encoding='utf8'));raw=subprocess.check_output(['git','show',ref+':'+p],cwd=W);b=json.loads(raw);before=json.loads(subprocess.check_output(['git','show','847d18b9^:'+p],cwd=W));assert before==b
ids={s['id'] for s in b['sources']};new=[s for s in a['sources'] if s['id'] not in ids];c=copy.deepcopy(a);c['sources']=[s for s in c['sources'] if s['id'] in ids];c['organizations']=[o for o in c['organizations'] if o['id'] not in ['su_democratic_russia','su_soyuz_deputies_group']];c['coverage']['unresolved']=[n for n in c['coverage']['unresolved'] if 'CLAUDE-C01-35' not in n];assert c==b
(E/'baseline-isolation.json').write_text(json.dumps({'passed':True,'accepted_integration_reference':ref,'pre_submission_packet_equals_accepted_integration':True,'removed_new_sources':[s['id'] for s in new],'removed_new_claims':[c['id'] for s in new for c in s['claims']],'removed_new_organizations':['su_democratic_russia','su_soyuz_deputies_group'],'removed_one_C01_35_coverage_note':True,'all_remaining_fields_equal':True,'SOURCE_26_preserved_in_full':True,'baseline_git_blob_sha256':hashlib.sha256(raw).hexdigest()},indent=2)+'\n')
commands=[('ussr',['python','-B','-m','unittest','discover','-s','tools/avatars','-p','test_ussr*.py']),('russia',['python','-B','-m','unittest','discover','-s','tools/avatars','-p','test_russia*.py']),('research',['python','-B','-m','unittest','discover','-s','tools/avatars','-p','test_*research*.py']),('campaign',['python','-B','-m','unittest','discover','-s','tools/avatars','-p','test_campaign*.py']),('atlas',['node','--test','tools/ui/check_leadership_research_review.cjs']),('index',['python','-B','tools/avatars/campaign_research.py','--check']),('census',['python','-B','tools/avatars/campaign_census.py','--check']),('workboard',['python','-B','tools/planning/workboard.py','--check'])];results=[]
for name,cmd in commands:
 with (E/(name+'.log')).open('wb') as f:r=subprocess.run(cmd,cwd=W,stdout=f,stderr=subprocess.STDOUT)
 results.append({'name':name,'command':cmd,'exit_code':r.returncode,'log':name+'.log'});print(name,r.returncode,flush=True)
(E/'validation-commands.json').write_text(json.dumps(results,indent=2)+'\n')
