/* People desk: the simulation supplies population counts (millions), rates,
   course progress and policy quotes. This module only formats and submits. */
const PEOPLE={data:null,state:null,session:null,nation:null,seq:0,loading:false,stale:true,error:"",busy:false,message:"",details:new Set(),focus:null};
function peopleText(value){return String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function peopleNumber(value,digits=1){return Number.isFinite(value)?value.toLocaleString("en-US",{maximumFractionDigits:digits,minimumFractionDigits:digits}):"—";}
function peopleCount(value){return !Number.isFinite(value)?"—":value>=1?`${peopleNumber(value)}m`:value>=.001?`${peopleNumber(value*1000)}k`:peopleNumber(value*1e6,0);}
function peoplePercent(value){return Number.isFinite(value)?`${peopleNumber(value*100)}%`:"—";}
function peopleActive(){return typeof S!=="undefined"&&!!S?.player&&typeof CAB!=="undefined"&&CAB.tab==="people"&&typeof cabinetIsOpen==="function"&&cabinetIsOpen();}
function peopleOrdersPending(){return PEOPLE.busy||(typeof advancing!=="undefined"&&advancing)||(typeof pendingAdvance!=="undefined"&&!!pendingAdvance)||(typeof COMMAND_CHANNEL!=="undefined"&&!!(COMMAND_CHANNEL.busy||COMMAND_CHANNEL.pending))||(typeof SESSION!=="undefined"&&SESSION.busy)||(typeof CAB!=="undefined"&&CAB.busy)||(typeof COMP!=="undefined"&&!!(COMP.busy||COMP.pending));}
function peopleCurrent(data=PEOPLE.data,state=PEOPLE.state){return peopleActive()&&!!data&&data===PEOPLE.data&&state===PEOPLE.state&&state===S&&!PEOPLE.loading&&!PEOPLE.stale&&!PEOPLE.error&&!peopleOrdersPending();}
function peopleMetric(label,value,note,tone=""){return `<article class="people-stat ${tone}"><span>${peopleText(label)}</span><strong>${peopleText(value)}</strong><p>${peopleText(note)}</p></article>`;}
function peopleBar(value,label){const percent=Number.isFinite(value)?Math.max(0,Math.min(100,value*100)):0;return `<div class="people-bar" role="meter" aria-label="${peopleText(label)}" aria-valuemin="0" aria-valuemax="100" aria-valuenow="${percent.toFixed(2)}"><i style="width:${percent.toFixed(2)}%"></i></div>`;}
function peopleDetail(id,label,body){return `<details class="people-detail" data-people-detail="${id}" ${PEOPLE.details.has(id)?"open":""}><summary>${label}</summary>${body}</details>`;}
function peopleClassHtml(row,index){const glyph=["❧","⚒","⚙","▤","⌂","◆"][index%6];return `<article class="people-class" data-people-class="${peopleText(row.key)}"><header><span class="people-class-glyph" aria-hidden="true">${glyph}</span><div><h3>${peopleText(row.name)}</h3><p>${peopleCount(row.people_m)} people · ${peoplePercent(row.share)}</p></div></header>${peopleBar(row.share,`${row.name} share of population`)}<dl><div><dt>Living standards</dt><dd>${peopleNumber(row.living_standards,0)}<small> / 100 at start</small></dd></div><div><dt>Discontent</dt><dd>${peoplePercent(row.discontent)}</dd></div></dl>${peopleDetail(`class-${index}`,"Income &amp; wealth",`<dl><div><dt>Income index</dt><dd>${peopleNumber(row.income_index,0)}</dd></div><div><dt>Wealth index</dt><dd>${peopleNumber(row.wealth_index,0)}</dd></div></dl><p>Income is relative to the opening national mean of 100. Wealth shows each class’s asset position. Qualifications and household wealth can move at different speeds. A spell of unemployment does not instantly change a household's class.</p>`)}</article>`;}
function peoplePolicyHtml(row){const ready=peopleCurrent()&&row.available&&!row.selected;return `<article class="people-policy ${row.selected?"selected":""}" data-people-policy-card="${peopleText(row.policy)}"><div class="people-policy-top"><span class="people-tag">${row.selected?"ACTIVE FOCUS":`${peopleNumber(row.political_cost,0)} PC`}</span>${row.cooldown_days>0?`<span class="people-policy-time">${peopleNumber(row.cooldown_days,0)} days to switch</span>`:""}</div><h3>${peopleText(row.name)}</h3><p>${peopleText(row.description)}</p><div class="people-policy-bottom"><button type="button" data-people-policy="${peopleText(row.policy)}" ${ready?"":"disabled"} aria-pressed="${!!row.selected}">${row.selected?"Current focus":`Choose ${peopleText(row.name)}`}</button>${row.reason&&!row.selected?`<small>${peopleText(row.reason)}</small>`:""}</div></article>`;}
function peopleEducationHtml(data){return `<section class="people-education" aria-labelledby="peopleEducationTitle"><div class="people-section-heading"><div><p class="people-kicker">Tomorrow's workforce</p><h2 id="peopleEducationTitle">Learn. Qualify. Move up.</h2></div><button type="button" data-people-budget ${peopleCurrent()?"":"disabled"}>Fund education →</button></div><p>More places help people qualify over time. Trade schools build practical skills; universities prepare professionals and researchers. Employers still need a job to offer.</p><div class="people-learning"><div><span>In education</span><strong>${peopleCount(data.students_m)}</strong><small>students</small></div><span class="people-learning-arrow" aria-hidden="true">→</span><div><span>Adult training capacity</span><strong>${peopleCount(data.training_capacity_m)}</strong><small>places</small></div><span class="people-learning-arrow" aria-hidden="true">→</span><div><span>Graduates</span><strong>${peopleCount(data.annual_graduates_m)}</strong><small>recent completions / year</small></div></div>${peopleCoursesHtml(data)}<p class="people-note">Current qualifications · working-age population</p><div class="people-attainment">${(data.education||[]).map(row=>`<div><span>${peopleText(row.name)}</span><strong>${peoplePercent(row.share)}</strong>${peopleBar(row.share,`${row.name} attainment`)}<small>${peopleCount(row.people_m)} people</small></div>`).join("")}</div><p class="people-note">Education funding: $${peopleNumber(data.education_budget_bn,2)}bn per year. Research capacity: ${peopleNumber(data.research_multiplier,2)}×. Courses take time; today's funding builds future qualifications.</p></section>`;}
function peopleCoursesHtml(data){
  if(!data.courses?.length)return `<p class="people-note">New course intakes appear as the calendar advances.</p>`;
  return `<div class="people-courses">${data.courses.map(course=>`<article><div><h3>${peopleText(course.name)}</h3><p>${peopleCount(course.people_m)} enrolled · ${peoplePercent(course.progress)} complete</p></div>${peopleBar(course.progress,`${course.name} progress`)}<small>Next graduates in ${peopleNumber(course.days_remaining,0)} funded days</small></article>`).join("")}</div>`;
}
function peopleWorkHtml(data){return peopleDetail("work","Inside the job market",`<p>Unemployment counts people looking for work. Participation shows how many working-age people join the civilian labor force. Students, retirees and people outside the workforce are shown separately.</p><dl class="people-work-stats"><div><dt>Unemployment</dt><dd>${peoplePercent(data.unemployment_rate)}</dd></div><div><dt>Participation</dt><dd>${peoplePercent(data.participation_rate)}</dd></div><div><dt>Employment ratio</dt><dd>${peoplePercent(data.employment_rate)}</dd></div><div><dt>Underemployment</dt><dd>${peoplePercent(data.underemployment_rate)}</dd></div><div><dt>Looking for work</dt><dd>${peopleCount(data.unemployed_m)}</dd></div><div><dt>Unfilled jobs</dt><dd>${peopleCount(data.vacancies_m)}</dd></div></dl><div class="people-sector-list">${(data.sectors||[]).map(row=>`<article><div><h3>${peopleText(row.name)}</h3><p>${peopleCount(row.employed_m)} employed · ${peopleCount(row.vacancies_m)} vacancies</p></div><div><strong>${peoplePercent(row.staffing)} staffed</strong>${peopleBar(row.staffing,`${row.name} staffing`)}</div></article>`).join("")}</div>`);}
function peopleProvincesHtml(data){return peopleDetail("provinces",`Across your provinces <span>${(data.provinces||[]).length}</span>`,`<div class="people-provinces">${(data.provinces||[]).map(row=>`<article><div><h3>${peopleText(row.name||row.district)}</h3><p>${peopleCount(row.population_m)} residents</p></div><dl><div><dt>At work</dt><dd>${peopleCount(row.employed_m)}</dd></div><div><dt>Unemployment</dt><dd>${peoplePercent(row.unemployment_rate)}</dd></div><div><dt>Living standards</dt><dd>${peopleNumber(row.living_standards,0)}</dd></div></dl></article>`).join("")||"<p>No mapped province breakdown is available. National totals still include your residents.</p>"}</div>`);}
function peopleContentHtml(){
  const data=PEOPLE.data;
  const hero=`<header class="people-hero"><div><p class="people-kicker">${peopleText(data?.name||"Your nation")} · People</p><h1>A good job.<br>A better tomorrow.</h1><p>Build skills. Open opportunities. Help every class share in your nation's progress.</p></div><svg viewBox="0 0 220 150" aria-hidden="true" class="people-hero-art"><path d="M12 137h197M134 49l27-27 28 27M162 23v76" fill="none" stroke="#d9b872" stroke-width="5" stroke-linecap="round"/><g fill="#a8d8c0"><circle cx="53" cy="66" r="17"/><path d="M28 133V102q0-18 25-18t25 18v31z"/></g><g fill="#e3c18a"><circle cx="104" cy="45" r="19"/><path d="M77 133V85q0-19 27-19t27 19v48z"/></g><g fill="#a9bddb"><circle cx="156" cy="83" r="15"/><path d="M134 133v-18q0-17 22-17t22 17v18z"/></g></svg></header>`;
  const message=PEOPLE.error?`<div class="people-message error" role="alert"><p>${peopleText(PEOPLE.error)}</p><button type="button" data-people-retry ${peopleOrdersPending()?"disabled":""}>Retry reading</button></div>`:PEOPLE.message?`<p class="people-message" role="status">${peopleText(PEOPLE.message)}</p>`:"";
  if(!data)return `${hero}${message}<p class="people-loading" role="status">${PEOPLE.loading?"Reading your nation's people…":"Open this desk to read the current population."}</p>`;
  if(!data.enabled)return `${hero}${message}<section class="people-upgrade"><h2>Bring people into the picture</h2><p>${peopleText(data.reason)}</p><p>Enable connected jobs, education and household classes for this campaign. Your current residents become the starting point.</p><button type="button" data-people-enable ${peopleCurrent()?"":"disabled"}>Enable people &amp; jobs</button></section>`;
  return `${hero}${message}${PEOPLE.loading||PEOPLE.stale?`<p class="people-loading" role="status">Updating the people desk…</p>`:""}<div class="people-stats">${peopleMetric("People at work",peopleCount(data.employed_m),`${peoplePercent(data.unemployment_rate)} unemployment`,"mint")}${peopleMetric("Living standards",peopleNumber(data.living_standards,0),"100 = your starting standard of living","gold")}${peopleMetric("Skills shortage",peopleCount(data.skilled_vacancies_m),"skilled positions waiting for workers","violet")}${peopleMetric("Education access",peoplePercent(data.school_coverage),`${peopleCount(data.annual_graduates_m)} recent graduates / year`,"blue")}</div><div class="people-section-heading"><div><p class="people-kicker">One national focus</p><h2>Choose the next opportunity</h2></div><button type="button" data-people-refresh ${PEOPLE.loading||peopleOrdersPending()?"disabled":""}>Refresh</button></div><div class="people-policies">${(data.policies||[]).map(peoplePolicyHtml).join("")}</div><section aria-labelledby="peopleClassesTitle"><div class="people-section-heading"><div><p class="people-kicker">${peopleCount(data.population_m)} people · shared ambitions</p><h2 id="peopleClassesTitle">Six ways to make a living</h2><p>Follow each class's living standards and pressure for change.</p></div></div><div class="people-classes">${(data.classes||[]).map(peopleClassHtml).join("")}</div></section>${peopleEducationHtml(data)}${peopleWorkHtml(data)}${peopleProvincesHtml(data)}${peopleDetail("population","Who makes up your nation",`<dl class="people-work-stats"><div><dt>Children</dt><dd>${peopleCount(data.children_m)}</dd></div><div><dt>Working age</dt><dd>${peopleCount(data.working_age_m)}</dd></div><div><dt>Retirees</dt><dd>${peopleCount(data.retirees_m)}</dd></div><div><dt>Outside civilian workforce</dt><dd>${peopleCount(data.outside_workforce_m)}</dd></div><div><dt>Military personnel</dt><dd>${peopleCount(data.military_m)}</dd></div><div><dt>Annual upward mobility</dt><dd>${peoplePercent(data.social_mobility)}</dd></div></dl>`)}${peopleDetail("notes","About these estimates",`<div class="people-notes">${(data.notes||[]).map(note=>`<p>${peopleText(note)}</p>`).join("")}</div>`)}`;
}
function peopleRemember(){const root=document.querySelector("#peopleRoot");if(!root||root.dataset.peopleSession!==String(PEOPLE.session??""))return;root.querySelectorAll("details[data-people-detail]").forEach(detail=>{if(detail.open)PEOPLE.details.add(detail.dataset.peopleDetail);else PEOPLE.details.delete(detail.dataset.peopleDetail);});const active=document.activeElement;if(active?.dataset?.peoplePolicy)PEOPLE.focus={policy:active.dataset.peoplePolicy};}
function peoplePanelHtml(){peopleRemember();return `<div id="peopleRoot" class="people-desk" data-people-session="${peopleText(PEOPLE.session)}" aria-busy="${PEOPLE.loading||PEOPLE.busy}">${peopleContentHtml()}</div>`;}
function peopleRender(){if(!peopleActive())return;const root=document.querySelector("#peopleRoot");if(!root)return;peopleRemember();root.innerHTML=peopleContentHtml();root.dataset.peopleSession=String(PEOPLE.session??"");root.setAttribute("aria-busy",String(PEOPLE.loading||PEOPLE.busy));peopleBind(false);}
function peopleBind(fetchIfNeeded=true){
  if(!peopleActive())return;
  peopleResetCampaign();
  const root=document.querySelector("#peopleRoot");if(!root)return;
  const data=PEOPLE.data,state=PEOPLE.state;
  root.querySelectorAll("[data-people-policy]").forEach(button=>{
    button.onclick=()=>peopleSubmit({kind:"set_population_policy",policy:button.dataset.peoplePolicy},data,state);
  });
  const enable=root.querySelector("[data-people-enable]");
  if(enable)enable.onclick=()=>peopleSubmit({kind:"enable_population"},data,state);
  const budget=root.querySelector("[data-people-budget]");
  if(budget)budget.onclick=()=>{
    if(peopleCurrent(data,state)){
      CAB.ministry="education";renderLeft(me());selectCabinetTab("budget");
      document.querySelector("#cab-tab-budget")?.focus({preventScroll:true});
    }
  };
  for(const key of ["refresh","retry"]){
    const button=root.querySelector(`[data-people-${key}]`);
    if(button)button.onclick=()=>{if(!peopleOrdersPending()){PEOPLE.focus={control:key};peopleFetch(true);}};
  }
  root.querySelectorAll("details[data-people-detail]").forEach(detail=>{
    detail.ontoggle=()=>{if(detail.open)PEOPLE.details.add(detail.dataset.peopleDetail);else PEOPLE.details.delete(detail.dataset.peopleDetail);};
  });
  if(!PEOPLE.loading&&!PEOPLE.busy&&PEOPLE.focus){
    let target;
    if(PEOPLE.focus.policy){
      const button=[...root.querySelectorAll("[data-people-policy]")].find(button=>button.dataset.peoplePolicy===PEOPLE.focus.policy);
      target=button&&!button.disabled?button:button?.closest("article");
      if(target&&target!==button)target.tabIndex=-1;
    }else if(PEOPLE.focus.control){
      target=root.querySelector(`[data-people-${PEOPLE.focus.control}]`)||root.querySelector("[data-people-refresh]");
    }
    if(target&&!target.disabled){target.focus({preventScroll:true});PEOPLE.focus=null;}
  }
  if(fetchIfNeeded&&PEOPLE.stale&&!PEOPLE.loading&&!PEOPLE.error)peopleFetch();
}
async function peopleFetch(force=false){if(!peopleActive()||PEOPLE.loading||(!force&&!PEOPLE.stale))return false;peopleResetCampaign();const state=S,seq=++PEOPLE.seq;PEOPLE.loading=true;PEOPLE.stale=true;PEOPLE.error="";peopleRender();try{const data=await api(`/api/population?session_id=${encodeURIComponent(state.session_id)}`);if(seq!==PEOPLE.seq||state!==S||!peopleActive())return false;if(!data||data.session_id!==state.session_id||data.nation!==state.player||typeof data.enabled!=="boolean"||(data.enabled&&(!Array.isArray(data.classes)||!Array.isArray(data.policies))))throw new Error("The population reading did not match this campaign. Refresh to read your current people.");PEOPLE.data=data;PEOPLE.state=state;PEOPLE.stale=false;return true;}catch(error){if(seq===PEOPLE.seq&&state===S&&peopleActive()){PEOPLE.error=error.message||"The population desk could not be reached.";PEOPLE.stale=true;}return false;}finally{if(seq===PEOPLE.seq){PEOPLE.loading=false;peopleRender();}}}
async function peopleSubmit(command,data=PEOPLE.data,state=PEOPLE.state){if(!peopleCurrent(data,state))return false;const policy=command.kind==="set_population_policy"?(data.policies||[]).find(row=>row.policy===command.policy):null;if(command.kind==="set_population_policy"&&(!policy||!policy.available||policy.selected))return false;if(command.kind==="enable_population"&&data.enabled)return false;if(!["enable_population","set_population_policy"].includes(command.kind))return false;PEOPLE.busy=true;PEOPLE.message="";peopleRender();try{const response=await api("/api/command",{commands:[command]});if(S!==state)return false;if(response.errors?.length)throw new Error(response.errors.join(" "));await adopt(response,false);PEOPLE.message=command.kind==="enable_population"?"People and jobs are now part of your campaign.":`${policy.name} is your national focus. Let time pass to see hiring and training develop.`;return true;}catch(error){if(S?.session_id===state.session_id){PEOPLE.error=error.message||"The focus could not be changed.";PEOPLE.stale=true;}return false;}finally{PEOPLE.busy=false;if(S?.session_id===state.session_id)peopleRender();}}
function peopleResetCampaign(){if(PEOPLE.session===S?.session_id&&PEOPLE.nation===S?.player)return;PEOPLE.session=S?.session_id;PEOPLE.nation=S?.player;PEOPLE.data=null;PEOPLE.state=null;PEOPLE.error="";PEOPLE.message="";PEOPLE.details.clear();PEOPLE.focus=null;PEOPLE.stale=true;PEOPLE.loading=false;PEOPLE.busy=false;++PEOPLE.seq;}
function peopleOnStateChanged(){peopleResetCampaign();PEOPLE.state=null;PEOPLE.stale=true;PEOPLE.error="";PEOPLE.loading=false;++PEOPLE.seq;if(peopleActive()){peopleRender();peopleFetch();}}
function peopleClose(){peopleRemember();PEOPLE.loading=false;PEOPLE.stale=true;PEOPLE.focus=null;++PEOPLE.seq;}
function peopleTabChanged(){if(!peopleActive()){peopleClose();return;}peopleResetCampaign();peopleBind();}
function openPeople(){if(typeof S==="undefined"||!S?.player)return false;if(!cabinetIsOpen())toggleGameDrawer("cabinetDrawer");selectCabinetTab("people");document.querySelector("#cab-tab-people")?.focus({preventScroll:true});return true;}
window.openPeople=openPeople;
window.addEventListener?.("resize",()=>{
  if(peopleActive())document.querySelector("#cab-tab-people")?.scrollIntoView({block:"nearest",inline:"nearest"});
});
