param([int]$Iteration=1,[string]$BinaryDirectory="")
$ErrorActionPreference='Stop'
$basePath='C:\Users\ridge\Documents\Codex\2026-09-05\pick-up-the-spheres-game-on\work\campaign-certification'
$repoPath=Join-Path $basePath 'integration'
$evidencePath=Join-Path $basePath 'evidence\political-calibration-20260922'
$dependencyPath=Join-Path $basePath 'integration-target\release\deps'
if($BinaryDirectory){$dependencyPath=[IO.Path]::GetFullPath($BinaryDirectory)}
$simBinary=Join-Path $dependencyPath 'spheres_sim-de8a2e7790f15db6.exe'
$censusBinary=Join-Path $dependencyPath 'bloc_census-b35be4d742aae476.exe'
Set-Location (Join-Path $repoPath 'spheres-sim')
$names=@(
 'politics::tests::fiscal_consolidation_never_increases_spending_or_reduces_tax',
 'politics::tests::daily_fiscal_boundaries_preserve_calendar_scaled_rates',
 'politics::tests::fiscal_recovery_moves_toward_bounds_without_reversing_direction',
 'politics::tests::legacy_fiscal_policy_respects_player_program_and_recovery_owners',
 'politics::tests::an_explicit_annual_plan_keeps_one_fiscal_owner_after_player_handoff',
 'politics::tests::opening_low_budget_nations_are_not_given_unvoted_spending',
 'politics::tests::legacy_fiscal_policy_respects_stock_and_plan_ownership_independently',
 'stratagems::tests::the_paid_consolidation_card_cuts_without_inventing_minimum_spending',
 'stratagems::tests::the_paid_consolidation_card_updates_owned_plans_and_charges_once',
 'stratagems::tests::an_unowned_program_consolidation_is_refused_before_any_effect',
 'stratagems::tests::a_paid_consolidation_keeps_stock_only_aggregate_authority',
 'stratagems::tests::a_fiscal_consolidation_with_no_financial_effect_is_refused',
 'stratagems::tests::each_single_financial_lever_keeps_consolidation_available',
 'government::tests::coups_refresh_open_book_debt_ratios_without_rewriting_legacy_debt',
 'government::tests::a_coup_tick_has_identical_fiscal_state_with_and_without_a_save_boundary',
 'government::tests::ai_voluntary_opening_requires_a_live_eligible_party',
 'government::tests::a_fresh_military_government_keeps_its_choice_without_blocking_paid_openings',
 'government::tests::scheduling_a_new_electoral_successor_preserves_its_real_governing_record',
 'government::tests::a_successor_calendar_keeps_the_eighteen_month_deadline_without_claiming_a_ballot',
 'government::tests::successor_calendar_dates_and_accountability_survive_daily_and_legacy_saves',
 'government::tests::missing_calendars_do_not_erase_real_regime_interims_or_change_the_lens_off_path',
 'army_authority::tests::authority_catalog_is_lagged_weighted_and_rejects_invented_coverage',
 'army_authority::tests::authority_seeds_only_fresh_existing_armies_and_never_backfills_old_saves',
 'army_authority::tests::authority_lifecycle_keeps_the_source_and_uses_the_model_clock',
 'government::tests::sourced_executive_removal_leverage_is_distinct_from_auth_resources_and_coup_risk',
 'government::tests::assessed_army_authority_changes_only_at_real_seizures_and_qualified_transfers',
 'government::tests::paid_snap_ballots_do_not_renew_a_continuing_governments_coup_grace',
 'government::tests::a_new_accountable_party_gets_coup_grace_without_rewriting_the_election_clock',
 'government::tests::electoral_coup_grace_uses_only_matching_observed_history_and_old_save_fallback',
 'government::tests::a_sourced_opening_mandate_is_not_a_completed_or_unrestricted_model_ballot',
 'government::tests::opening_consent_counts_only_attested_live_national_constituencies',
 'government::tests::old_missing_restricted_and_future_opening_mandates_are_not_reconstructed',
 'government::tests::opening_mandates_end_on_restriction_or_broken_authority_and_do_not_return',
 'government::tests::lawful_same_party_succession_retains_only_the_existing_assembly_authority',
 'government::tests::successor_personnel_observation_uses_the_model_clock_not_legacy_settlement_day',
 'opening_mandates::tests::opening_mandate_catalog_is_partial_dated_and_bound_to_the_actual_office',
 'tests::the_daily_clock_preserves_the_political_arm_on_world',
 'government::tests::an_annulled_opening_ballot_does_not_seat_the_parliamentary_winner',
 'government::tests::opening_ballots_keep_same_party_people_separate_heads_and_the_off_path',
 'government::tests::the_first_parliamentary_ballot_reconciles_the_actual_office_with_the_seeded_chamber',
 'government::tests::ai_can_fund_a_midyear_army_crisis_once_without_free_loyalty_or_tiny_churn',
 'army_institutions::tests::army_presence_audit_covers_every_opening_polity_with_explicit_exceptions',
 'government::tests::ai_army_appropriation_targets_actual_loyalty_without_spending_past_useful_resources',
 'government::tests::unsourced_successors_retain_a_dated_force_reference_without_inventing_1990_history',
 'government::tests::civilian_confidence_counts_national_consent_without_manufacturing_a_mandate',
 'government::tests::an_unvoted_opposition_list_does_not_inherit_the_incumbents_bad_record',
 'government::tests::a_legacy_regime_record_is_rekeyed_only_for_its_observed_live_party',
 'government::tests::a_real_party_or_military_handover_resets_accountability_without_inventing_party_history',
 'government::tests::a_continuing_incumbent_keeps_its_record_through_opening_and_its_first_ballot',
 'armed_security::tests::an_unvoted_interim_keeps_its_real_supply_obligations_until_a_completed_ballot',
 'government::tests::convening_a_round_table_opens_the_country_in_six_months',
 'government::tests::the_liberalisation_seam_reseeds_parties_from_movements',
 'government::tests::opening_a_regime_preserves_its_programme_until_a_real_ballot',
 'government::tests::represented_parties_compete_without_spending_unrepresented_voters',
 'government::tests::a_partial_party_table_does_not_erase_unrepresented_national_constituencies',
 'government::tests::lawful_transfers_consolidate_civilian_control_without_snap_election_farming',
 'government::tests::generated_party_regimes_keep_their_role_through_succession_and_then_yield_to_a_ballot',
 'army_institutions::tests::army_presence_rejects_invalid_sources_kinds_duplicates_and_no_force_records',
 'army_institutions::tests::army_presence_overlay_preserves_parties_and_is_not_inferred_from_personnel',
 'army_institutions::tests::army_presence_old_saves_upgrade_once_without_overwriting_live_loyalty',
 'government::tests::the_first_free_ballot_replaces_a_generic_party_regime_but_not_an_inherited_crown',
 'government::tests::sourced_army_presence_keeps_funded_and_civilian_control_guards',
 'government::tests::coalition_exclusion_is_symmetric_without_erasing_pluralities_or_majorities',
 'government::tests::coalition_invitation_preview_and_command_enforce_both_sides_of_the_cordon',
 'government::tests::completed_ballots_refresh_constituencies_without_reinterpreting_seats_or_old_saves',
 'government::tests::voter_reversion_uses_the_last_observed_ballot_and_never_rewrites_it_during_drift',
 'government::tests::reshuffles_and_restricted_ballots_do_not_fabricate_a_new_constituency',
 'government::tests::the_first_free_ballot_seats_the_same_interim_party_and_keeps_its_deadline',
 'government::tests::first_free_elections_replace_original_military_rulers_but_preserve_constitutional_heads',
 'government::tests::an_annulled_first_ballot_has_no_elected_mandate_or_pending_deadline',
 'government::tests::pending_ballot_metadata_is_absent_for_old_saves_and_inert_with_the_lens_off',
 'blocs::tests::coercion_reads_physical_services_before_party_discipline',
 'armed_security::tests::sustained_shortfalls_consume_operational_capacity_and_replacement_rebuilds_it',
 'armed_security::tests::finite_reserves_follow_calendar_supply_in_both_clocks_without_harming_funded_forces',
 'armed_security::tests::exhausted_reserves_do_not_override_the_real_contest_or_disabled_crises',
 'government::tests::a_full_term_remembers_early_hardship_but_sustained_recovery_is_forgiven',
 'government::tests::the_current_party_apparatus_cannot_resurrect_a_defeated_historical_programme',
 'armed_security::tests::an_inherited_security_review_uses_the_real_paid_decision_once',
 'armed_security::tests::security_review_preserves_player_compatible_and_unreviewed_old_save_programmes',
 'armed_security::tests::security_review_does_not_veto_replacement_or_deliberately_restored_supplies',
 'armed_security::tests::an_unaffordable_security_review_waits_without_free_effects_or_random_draws',
 'government::tests::an_autonomous_army_can_veto_a_new_programme_but_civilian_control_and_loyalty_resist',
 'government::tests::army_confidence_responds_to_sustained_civilian_failure_without_changing_resources',
 'government::tests::an_uncrowned_collapse_preserves_the_actual_elected_programme_across_save_and_seeding',
 'government::tests::unsourced_army_size_is_an_explicit_model_estimate_without_rewriting_history',
 'armed_security::tests::armed_security_sources_reject_invalid_parameters_and_unsupported_actors',
 'armed_security::tests::a_military_collapse_does_not_mint_voters_and_ends_the_old_dependency',
 'stratagems::tests::an_affordable_round_table_reaches_the_real_ai_dispatcher',
 'armed_security::tests::dead_patrons_dates_and_daily_steps_follow_actual_supply',
 'armed_security::tests::security_state_round_trips_and_switches_are_inert',
 'armed_security::tests::absent_armed_actors_and_old_saves_never_invent_a_military_claimant',
 'armed_security::tests::maintained_replaced_and_domestically_replaced_supplies_prevent_collapse',
 'armed_security::tests::opening_security_is_sourced_priced_and_separate_from_votes',
 'the_complete_vote_change_preserves_totals_and_its_calendar_bound',
 'franchise_demand_reads_excluded_parties_including_same_bloc_alternatives',
 'organised_civilian_franchise_demand_can_buy_a_peaceful_opening_with_loyal_armed_services',
 'political_record_remembers_a_bad_term_but_resets_when_another_party_governs',
 'political_record_learns_one_calendar_month_in_both_clock_modes',
 'movement_constituencies_keep_organized_opposition_and_single_party_uncertainty',
 'a_coalition_leader_is_accountable_without_erasing_junior_or_opposition_voters',
 'performance_transfers_are_bounded_and_good_government_has_diminishing_returns',
 'd4_tables_are_read_under_the_switch_and_invisible_off',
 'sourced_opening_organizations_exist_without_buying_them_and_preserve_saved_histories',
 'an_established_movement_survives_funding_decay_and_save_load_without_free_support',
 'old_saves_recognize_qualifying_movement_backing_without_inventing_past_organizations',
 'movement_establishment_is_inert_when_off_and_does_not_duplicate_table_presence',
 'blocs::tests::an_absent_islamist_bloc_becomes_present_after_one_sponsor_operation',
 'data::movements::tests::opening_organizations_have_sources_without_invented_vote_shares',
 'data::movements::tests::opening_organizations_reject_duplicates_unknown_nations_and_unsourced_rows',
 'disorder_alone_costs_the_elected_incumbent_support',
 'disorder_alone_costs_a_regime_support_without_changing_the_quiet_record',
 'party_support_moves_with_prices_rather_than_with_a_slider',
 'a_war_going_badly_is_worth_votes_to_the_nationalists',
 'a_regime_s_movements_move_with_the_pains_and_revert',
 'support_finds_an_equilibrium_rather_than_running_away',
 'army_operating_costs_include_local_support_and_imported_equipment',
 'military_resources_have_real_units_and_change_loyalty_without_penalizing_small_budget_shares',
 'foreign_backing_alone_cannot_change_an_internal_coups_programme',
 'ai_army_funding_is_priced_affordable_and_does_not_override_owned_budgets',
 'party_discipline_needs_a_domestic_constituency_and_stays_legacy_when_off',
 'blocs::tests::electoral_uprising_requires_actual_coercion_failure_as_well_as_party_support',
 'the_army_target_is_the_share_arm_off_and_the_pay_arm_is_the_ruled_form',
 'the_regime_s_own_coup_keeps_its_colour_under_the_lens_and_latches_the_deposed_movement_on_the_roads',
 'the_ai_takes_each_lever_only_under_its_thresholds',
 'an_unpaid_army_removes_an_elected_government_and_a_paid_one_never_does',
 'the_algeria_shaped_annulment_fires_under_its_conditions_and_not_under_the_court',
 'a_paid_army_seats_the_islamists_and_a_hostile_one_annuls_the_algerian_way',
 'a_communist_movement_at_discontent_0_70_with_an_unpaid_army_takes_power'
)
$focus=@()
for($i=0;$i -lt $names.Count;$i++) {
 $name=if($names[$i].Contains('::')) { $names[$i] } else { 'government::tests::'+$names[$i] }
 $log=Join-Path $evidencePath "iteration-$Iteration-focus-$i.log"
 & $simBinary --exact $name --nocapture --test-threads=1 *> $log
 $code=$LASTEXITCODE
 $pass=(Get-Content -LiteralPath $log -Raw) -match 'test result: ok\. 1 passed; 0 failed;'
 $focus+=@{test=$name;exit_code=$code;confirmed_one_pass=$pass;log=$log}
 Write-Output "$name => $code onepass=$pass"
}
$focus | ConvertTo-Json -Depth 5 | Set-Content (Join-Path $evidencePath "iteration-$Iteration-focused-results.json")
$gatesLog=Join-Path $evidencePath "iteration-$Iteration-A1-A10.log"
& $censusBinary --include-ignored --skip bloc_census --nocapture --test-threads=4 *> $gatesLog
$gatesCode=$LASTEXITCODE
@{iteration=$Iteration;finished_utc=(Get-Date).ToUniversalTime().ToString('o');focused_passed=@($focus|Where-Object {$_.confirmed_one_pass -and $_.exit_code -eq 0}).Count;focused_total=$focus.Count;gates_exit=$gatesCode;gates_command="$censusBinary --include-ignored --skip bloc_census --nocapture --test-threads=4";gates_log=$gatesLog;source_manifest="iteration-$Iteration-source-input-manifest.json";post_run_observed_source_sha256=@('government.rs','blocs.rs','statecraft.rs'|ForEach-Object {Get-FileHash -LiteralPath (Join-Path $repoPath "spheres-sim\src\$_") -Algorithm SHA256}|Select-Object Path,Hash);binary_sha256=@($simBinary,$censusBinary|ForEach-Object {Get-FileHash -LiteralPath $_ -Algorithm SHA256}|Select-Object Path,Hash)} | ConvertTo-Json -Depth 6 | Set-Content (Join-Path $evidencePath "iteration-$Iteration-results.json")
Get-Content -LiteralPath $gatesLog -Tail 25
