//! The 1990 resource table: who mined what in 1990, and where on the map it
//! sits.
//!
//! `spheres-sim/data/resources_1990.json` is generated by
//! `tools/resources/make_resources_1990.py` from the web's district artifacts
//! and committed, the way `districts.json` and the nation files are. It is
//! embedded with `include_str!` for the same reason they are: the library does
//! no file access, the binary is self-contained, and a determinism test cannot
//! fail because a data file moved. It is a STATIC table — never in
//! `WorldState`, never hashed, never saved — so nothing here can move a golden.
//! Cut one of the resource system (S1) builds the derived HAVE cache over it;
//! this module is the loader and the invariants the loader refuses to do
//! without.
//!
//! Two passes, the `data/mod.rs` convention: pass one parses with
//! `deny_unknown_fields` and checks each table against itself (shares sum to
//! one, every share above the pruning floor, quality zero exactly where the
//! presence bit is zero); pass two resolves every key through
//! `NationId::from_code` and the 1990 roster, so a key that names nobody, or a
//! seat that is not on the board in January 1990, is a refusal addressed to
//! whoever wrote the file rather than a silent zero in somebody's ledger.
//!
//! What the numbers ARE, so no reader multiplies the wrong two:
//! - `national_1990[c][n]` is the transcribed 1990 national figure, verbatim,
//!   in `units[c]`. The USSR's iron is 236,000,000 t (DS-896) and a test says so.
//! - `located[c][n]` is a LOCATION WEIGHT per district — the share of the 1990
//!   owner's figure that sits in that district under one written rule
//!   (`meta.rules.share`). A share is never a tonnage; multiplied by the figure
//!   it says where the output is, which is what changes hands with the ground.
//! - `presence` and `quality` are presence bits and a presence RANK, used to
//!   choose a war aim, never to print a number.
//! - `price_1990[c]` is the one new transcription: a 1990 unit value in dollars
//!   per `units[c]`, with the printed figure and its source beside it. Oil has
//!   no row; the sim prices it at `w.oil_price`.

use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;
use std::sync::OnceLock;

use crate::data::{render_errors, LoadError};
use crate::world::{start_nations, NationId};

pub const EMBEDDED_RESOURCES_1990: &str = include_str!("../data/resources_1990.json");
const FILE: &str = "data/resources_1990.json";

/// The twelve lines, alphabetical. Index `i` is bit `i` of a `presence` mask
/// and column `i` of a `quality` row, and the file's `commodities` list must
/// read exactly this.
pub const COMMODITIES: [&str; 12] = [
    "bauxite",
    "coal",
    "cobalt",
    "copper",
    "gas",
    "gold",
    "iron",
    "oil",
    "phosphate",
    "platinum_group",
    "rare_earths",
    "uranium",
];

/// The six lines with a transcribed 1990 national figure. The other six are
/// presence-only until their figures are transcribed (package D2).
pub const TRACKED: [&str; 6] = ["bauxite", "coal", "copper", "gas", "iron", "oil"];

/// `national` keys the generator refuses to seat, and the loader asserts it
/// refused exactly these. Namibia is a roster seat that comes alive after
/// January 1990 and holds no 1990 district; its figures are reported in
/// `meta.counts.dropped_rows` and carried nowhere else. A start nation may
/// never appear here: that would be a transcribed figure thrown away.
pub const DROPPED_KEYS: [&str; 1] = ["Namibia"];

/// The floor a located share must clear. The generator prunes below it and
/// renormalises; "located" means at or above it (spec section 1.2: a 1e-6
/// coalfield sliver must not count as located, as a district, or as a war aim).
pub const LOCATED_MIN_SHARE: f64 = 1e-3;

/// How far a located list's sum may sit from one.
pub const SHARE_SUM_TOLERANCE: f64 = 1e-9;

// ---------------------------------------------------------------------------
// The schema
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ResourceFile {
    pub meta: Meta,
    pub commodities: Vec<String>,
    pub tracked: Vec<String>,
    /// The sim's unit per tracked line: t, kt, t, bcf, t, kb/d.
    pub units: BTreeMap<String, String>,
    /// Per mined tracked line (never oil): the 1990 unit value.
    pub price_1990: BTreeMap<String, Price>,
    /// commodity -> 1990 start nation code -> the figure, verbatim.
    pub national_1990: BTreeMap<String, BTreeMap<String, Figure>>,
    /// commodity -> 1990 owner code -> [(district, share)], share desc then id.
    pub located: BTreeMap<String, BTreeMap<String, Vec<(String, f64)>>>,
    /// district -> 12-bit mask, bit i = `COMMODITIES[i]` present.
    pub presence: BTreeMap<String, u16>,
    /// district -> presence rank per commodity, 0 absent, 1..3 present.
    pub quality: BTreeMap<String, [u8; 12]>,
    /// district -> share of its 1990 owner's population.
    pub pop_share: BTreeMap<String, f64>,
    /// district -> GHS-POP 1990 count (a modelled surface, not a census line).
    pub pop_1990: BTreeMap<String, u64>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Meta {
    pub generator: String,
    pub upstream: Upstream,
    pub source_sha256: BTreeMap<String, String>,
    pub dropped_keys: Vec<String>,
    pub rules: BTreeMap<String, String>,
    pub counts: Counts,
    /// Mined tracked lines with no sourced 1990 price, and why.
    pub prices_omitted: BTreeMap<String, String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Upstream {
    pub generator: String,
    pub vintage: u32,
    pub sources: BTreeMap<String, UpstreamSource>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct UpstreamSource {
    pub title: String,
    pub url: String,
    pub role: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Counts {
    pub presence_districts: usize,
    pub located_rows: BTreeMap<String, usize>,
    pub located_nations: BTreeMap<String, usize>,
    pub national_rows: BTreeMap<String, usize>,
    pub pruned: BTreeMap<String, BTreeMap<String, usize>>,
    pub unlocated_producers: BTreeMap<String, Vec<String>>,
    pub zero_rows_omitted: BTreeMap<String, usize>,
    pub dropped_rows: BTreeMap<String, BTreeMap<String, f64>>,
    pub pop_districts: usize,
}

/// One transcribed 1990 unit value. `usd_per_unit` is dollars per one
/// `units[c]`, derived from `as_printed` by `conversion`; `source` is the
/// citation verbatim, which the web prints on hover.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Price {
    pub usd_per_unit: f64,
    pub as_printed: String,
    pub conversion: String,
    pub source: String,
}

/// One transcribed 1990 national figure and the artifact source key it came
/// from (`meta.upstream.sources` describes the key).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Figure {
    pub value: f64,
    pub source: String,
}

/// The parsed file plus the keys resolved to `NationId`, so a consumer never
/// touches a string twice. Built once, behind `tables()`.
#[derive(Clone, Debug)]
pub struct Tables {
    pub file: ResourceFile,
    /// commodity -> nation -> the 1990 figure in the sim's units.
    pub national: BTreeMap<String, BTreeMap<NationId, f64>>,
    /// commodity -> 1990 owner -> located (district, share), share desc.
    pub located: BTreeMap<String, BTreeMap<NationId, Vec<(String, f64)>>>,
}

/// Index of a commodity name in `COMMODITIES`, which is its presence bit and
/// quality column.
pub fn commodity_index(name: &str) -> Option<usize> {
    COMMODITIES.iter().position(|c| *c == name)
}

/// The table. Parsed and validated once; a broken file is a panic with every
/// problem listed, the way `districts::tables` treats `districts.json`.
pub fn tables() -> &'static Tables {
    static T: OnceLock<Tables> = OnceLock::new();
    T.get_or_init(|| {
        let file = parse_and_validate(EMBEDDED_RESOURCES_1990)
            .unwrap_or_else(|e| panic!("{}", render_errors(&e)));
        let mut national = BTreeMap::new();
        for (c, rows) in &file.national_1990 {
            let mut m = BTreeMap::new();
            for (code, fig) in rows {
                let id = NationId::from_code(code).expect("validated above");
                m.insert(id, fig.value);
            }
            national.insert(c.clone(), m);
        }
        let mut located = BTreeMap::new();
        for (c, rows) in &file.located {
            let mut m = BTreeMap::new();
            for (code, list) in rows {
                let id = NationId::from_code(code).expect("validated above");
                m.insert(id, list.clone());
            }
            located.insert(c.clone(), m);
        }
        Tables { file, national, located }
    })
}

/// Both passes over one source string. Errors are collected, not
/// short-circuited: a regenerated file with three problems should show three.
pub fn parse_and_validate(json: &str) -> Result<ResourceFile, Vec<LoadError>> {
    let file = serde_json::from_str::<ResourceFile>(json)
        .map_err(|e| vec![file_level(e.to_string())])?;
    let mut errors = check_file(&file);
    errors.extend(validate(&file));
    if errors.is_empty() {
        Ok(file)
    } else {
        Err(errors)
    }
}

fn file_level(message: impl Into<String>) -> LoadError {
    LoadError { file: FILE.to_string(), nation: None, message: message.into() }
}

fn nation_level(nation: &str, message: impl Into<String>) -> LoadError {
    LoadError { file: FILE.to_string(), nation: Some(nation.to_string()), message: message.into() }
}

// ---------------------------------------------------------------------------
// Pass one — the file against itself
// ---------------------------------------------------------------------------

/// Bounds that are facts about the table rather than opinions about history:
/// a share is a share, a list of shares sums to one, a rank is 0..3 and is 0
/// exactly where nothing is present, and a mined line either has a sourced
/// price or says why it has none.
fn check_file(f: &ResourceFile) -> Vec<LoadError> {
    let mut e = vec![];
    if f.commodities != COMMODITIES {
        e.push(file_level(format!(
            "commodities is {:?}; the twelve lines in this build are {:?}, in that order",
            f.commodities, COMMODITIES
        )));
    }
    if f.tracked != TRACKED {
        e.push(file_level(format!("tracked is {:?}, expected {:?}", f.tracked, TRACKED)));
    }
    let tracked: Vec<&str> = TRACKED.to_vec();
    let unit_keys: Vec<&str> = f.units.keys().map(String::as_str).collect();
    if unit_keys != tracked {
        e.push(file_level(format!("units is keyed {:?}, expected the tracked lines", unit_keys)));
    }
    for (c, u) in &f.units {
        if u.trim().is_empty() {
            e.push(file_level(format!("units.{c} is empty")));
        }
    }
    for (c, p) in &f.price_1990 {
        if !TRACKED.contains(&c.as_str()) || c == "oil" {
            e.push(file_level(format!(
                "price_1990.{c}: only mined tracked lines carry a price; oil is priced at w.oil_price"
            )));
        }
        if !(p.usd_per_unit.is_finite() && p.usd_per_unit > 0.0) {
            e.push(file_level(format!(
                "price_1990.{c}.usd_per_unit is {}, expected a positive dollar figure",
                p.usd_per_unit
            )));
        }
        for (field, s) in [("source", &p.source), ("as_printed", &p.as_printed), ("conversion", &p.conversion)] {
            if s.trim().is_empty() {
                e.push(file_level(format!(
                    "price_1990.{c}.{field} is empty — iron rule 4: a price is transcribed, so say where from"
                )));
            }
        }
        if f.meta.prices_omitted.contains_key(c) {
            e.push(file_level(format!("price_1990.{c} is both priced and listed in prices_omitted")));
        }
    }
    for c in TRACKED.iter().filter(|c| **c != "oil") {
        if !f.price_1990.contains_key(*c) && !f.meta.prices_omitted.contains_key(*c) {
            e.push(file_level(format!(
                "{c} has no price_1990 row and no prices_omitted reason — an unsourced line is omitted AND says so"
            )));
        }
    }
    if f.national_1990.keys().map(String::as_str).collect::<Vec<_>>() != tracked {
        e.push(file_level("national_1990 must be keyed by exactly the tracked lines"));
    }
    if f.located.keys().map(String::as_str).collect::<Vec<_>>() != tracked {
        e.push(file_level("located must be keyed by exactly the tracked lines"));
    }
    for (c, rows) in &f.national_1990 {
        for (n, fig) in rows {
            if !(fig.value.is_finite() && fig.value > 0.0) {
                e.push(nation_level(n, format!(
                    "national_1990.{c} is {}, expected a positive figure (zero rows are omitted)",
                    fig.value
                )));
            }
            if fig.source.trim().is_empty() {
                e.push(nation_level(n, format!("national_1990.{c} has no source")));
            }
        }
    }
    for (c, rows) in &f.located {
        for (n, list) in rows {
            if list.is_empty() {
                e.push(nation_level(n, format!("located.{c} is an empty list; an unlocated producer is absent, not empty")));
                continue;
            }
            let sum: f64 = list.iter().map(|(_, s)| *s).sum();
            if !((sum - 1.0).abs() <= SHARE_SUM_TOLERANCE) {
                e.push(nation_level(n, format!("located.{c} sums to {sum}, expected 1 within {SHARE_SUM_TOLERANCE}")));
            }
            for (d, s) in list {
                if !(s.is_finite() && *s >= LOCATED_MIN_SHARE && *s <= 1.0) {
                    e.push(nation_level(n, format!(
                        "located.{c} share of {d} is {s}, expected {LOCATED_MIN_SHARE}..=1 (below the floor is pruned, not located)"
                    )));
                }
                if !f.presence.contains_key(d) {
                    e.push(nation_level(n, format!("located.{c} names {d}, which carries no presence bit")));
                }
            }
            for w in list.windows(2) {
                let ((d0, s0), (d1, s1)) = (&w[0], &w[1]);
                if s1 > s0 || (s1 == s0 && d1 <= d0) {
                    e.push(nation_level(n, format!("located.{c} is not sorted share desc then id at {d0} / {d1}")));
                    break;
                }
            }
        }
    }
    if f.presence.is_empty() {
        e.push(file_level("presence is empty"));
    }
    for (d, m) in &f.presence {
        if *m == 0 || *m >= 1 << 12 {
            e.push(file_level(format!("presence.{d} is {m}, expected a non-empty 12-bit mask")));
        }
    }
    if f.quality.keys().ne(f.presence.keys()) {
        e.push(file_level("quality must be keyed exactly like presence"));
    }
    for (d, q) in &f.quality {
        let mask = f.presence.get(d).copied().unwrap_or(0);
        for (i, r) in q.iter().enumerate() {
            let present = mask >> i & 1 == 1;
            if *r > 3 || (*r == 0) == present {
                e.push(file_level(format!(
                    "quality.{d}[{i}] ({}) is {r} but the presence bit is {}; a rank is 1..3 where present and 0 where not",
                    COMMODITIES[i], present as u8
                )));
            }
        }
    }
    for (d, s) in &f.pop_share {
        if !(s.is_finite() && (0.0..=1.0).contains(s)) {
            e.push(file_level(format!("pop_share.{d} is {s}, expected a share in 0..=1")));
        }
    }
    if f.pop_1990.keys().ne(f.pop_share.keys()) {
        e.push(file_level("pop_1990 must be keyed exactly like pop_share"));
    }
    if f.meta.dropped_keys != DROPPED_KEYS {
        e.push(file_level(format!(
            "meta.dropped_keys is {:?}; this build expects exactly {:?} to be unseated",
            f.meta.dropped_keys, DROPPED_KEYS
        )));
    }
    let c = &f.meta.counts;
    if c.presence_districts != f.presence.len() || c.pop_districts != f.pop_share.len() {
        e.push(file_level("meta.counts district totals do not describe the file"));
    }
    for t in TRACKED {
        let rows = f.located.get(t).map(|m| m.values().map(Vec::len).sum::<usize>()).unwrap_or(0);
        let nats = f.located.get(t).map(BTreeMap::len).unwrap_or(0);
        let natl = f.national_1990.get(t).map(BTreeMap::len).unwrap_or(0);
        if c.located_rows.get(t) != Some(&rows)
            || c.located_nations.get(t) != Some(&nats)
            || c.national_rows.get(t) != Some(&natl)
        {
            e.push(file_level(format!("meta.counts for {t} do not describe the file")));
        }
    }
    e
}

// ---------------------------------------------------------------------------
// Pass two — the file against the roster
// ---------------------------------------------------------------------------

/// Nothing here can be checked while looking at the file alone: every key
/// must name a nation this build has, that nation must be on the board in
/// January 1990, every located producer must have a figure, and a dropped
/// key must never be a start nation.
fn validate(f: &ResourceFile) -> Vec<LoadError> {
    let mut e = vec![];
    let start = start_nations();
    for (c, rows) in &f.national_1990 {
        for code in rows.keys() {
            match NationId::from_code(code) {
                None => e.push(nation_level(code, format!(
                    "national_1990.{c} names a nation this build does not have — the join is the roster code, and dropped_keys are the only permitted misses"
                ))),
                Some(id) if !start.contains(&id) => e.push(nation_level(code, format!(
                    "national_1990.{c} names a seat that is not on the board in January 1990 — successor states inherit through the located shares, never a row of their own"
                ))),
                Some(_) => {}
            }
        }
    }
    for (c, rows) in &f.located {
        for code in rows.keys() {
            if !f.national_1990.get(c).is_some_and(|m| m.contains_key(code)) {
                e.push(nation_level(code, format!("located.{c} has shares but no national_1990.{c} figure to locate")));
            }
        }
    }
    for code in &f.meta.dropped_keys {
        if let Some(id) = NationId::from_code(code) {
            if start.contains(&id) {
                e.push(nation_level(code, "is listed in dropped_keys but is a 1990 start nation — a transcribed figure was thrown away"));
            }
        }
    }
    e
}

#[cfg(test)]
mod tests {
    use super::*;

    /// D1's gate, from the sim's side: the committed table loads through both
    /// passes, and the facts the spec pins (section 2.4) hold on what loaded.
    /// Nothing here touches `WorldState`; the table is static and unhashed.
    #[test]
    fn the_1990_resource_table_loads_and_holds_its_invariants() {
        let t = tables();
        let f = &t.file;

        // The join: every key seated, exactly one key refused, and it is not a
        // start nation (Namibia is a roster seat that comes alive later).
        assert_eq!(f.meta.dropped_keys, DROPPED_KEYS);
        let namibia = NationId::from_code("Namibia").expect("Namibia is a roster seat");
        assert!(!start_nations().contains(&namibia), "Namibia must not be a start nation while it is dropped");
        for c in TRACKED {
            for code in f.national_1990[c].keys() {
                assert!(NationId::from_code(code).is_some(), "{code} does not resolve");
            }
        }

        // The transcribed figure, exact: the USSR's iron is DS-896's 236,000,000 t.
        let ussr = NationId::from_code("USSR").unwrap();
        assert_eq!(t.national["iron"][&ussr], 236_000_000.0);
        assert_eq!(f.national_1990["iron"]["USSR"].source, "ds896_iron");

        // Shares: sum to one, every one at or above the floor, sorted.
        for c in TRACKED {
            for (code, list) in &f.located[c] {
                let sum: f64 = list.iter().map(|(_, s)| s).sum();
                assert!((sum - 1.0).abs() <= SHARE_SUM_TOLERANCE, "{c}/{code} sums to {sum}");
                assert!(list.iter().all(|(_, s)| *s >= LOCATED_MIN_SHARE), "{c}/{code} carries a pruned share");
            }
        }
        let ussr_iron = &t.located["iron"][&ussr];
        assert!(!ussr_iron.is_empty());
        assert!(ussr_iron.windows(2).all(|w| w[0].1 >= w[1].1));
        // The Soviet coalfield tail was pruned, not carried at 1e-6.
        assert!(f.meta.counts.pruned["coal"]["USSR"] > 0);
        assert!(f.located["coal"]["USSR"].iter().all(|(_, s)| *s >= LOCATED_MIN_SHARE));

        // The USA: an unlocated oil producer (its ledger is oil_mbd, and the
        // shares only say where it sits — nowhere, so nothing can be taken),
        // and no 1990 bauxite row at all.
        let usa = NationId::from_code("USA").unwrap();
        assert!(!t.located["oil"].contains_key(&usa));
        assert!(t.national["oil"].contains_key(&usa));
        assert!(f.meta.counts.unlocated_producers["oil"].iter().any(|n| n == "USA"));
        assert!(!t.national["bauxite"].contains_key(&usa));

        // Presence and quality: 1,471 districts, rank 0 exactly where the bit is 0.
        assert_eq!(f.presence.len(), 1471);
        assert_eq!(f.quality.len(), 1471);
        for (d, q) in &f.quality {
            let mask = f.presence[d];
            for i in 0..12 {
                assert_eq!(q[i] == 0, mask >> i & 1 == 0, "{d}[{i}]");
            }
        }
        assert!(commodity_index("iron") == Some(6) && commodity_index("rice").is_none());

        // Prices: the one new transcription. Oil never has a row; every mined
        // line is priced with a source or named as omitted.
        assert!(!f.price_1990.contains_key("oil"));
        for c in TRACKED.iter().filter(|c| **c != "oil") {
            let priced = f.price_1990.get(*c).is_some_and(|p| p.usd_per_unit > 0.0 && !p.source.trim().is_empty());
            let omitted = f.meta.prices_omitted.contains_key(*c);
            assert!(priced ^ omitted, "{c}: priced={priced} omitted={omitted}");
        }

        // The resolved index agrees with the file.
        for c in TRACKED {
            assert_eq!(t.national[c].len(), f.national_1990[c].len());
            assert_eq!(t.located[c].len(), f.located[c].len());
        }
    }

    /// The loader refuses what it should: an unknown field, a share below the
    /// floor, a key that names nobody, and a dropped key that is a start
    /// nation. Each is a listed error, not a panic and not a silent default.
    #[test]
    fn the_loader_refuses_a_bad_table() {
        let mut v: serde_json::Value = serde_json::from_str(EMBEDDED_RESOURCES_1990).unwrap();
        v["located"]["iron"]["USSR"][0][1] = serde_json::json!(1e-4);
        v["national_1990"]["iron"]["Atlantis"] = serde_json::json!({"value": 1.0, "source": "x"});
        v["national_1990"]["iron"]["Russia"] = serde_json::json!({"value": 1.0, "source": "x"});
        v["meta"]["dropped_keys"] = serde_json::json!(["USA"]);
        let errs = parse_and_validate(&v.to_string()).unwrap_err();
        let text = render_errors(&errs);
        assert!(text.contains("sums to"), "{text}");
        assert!(text.contains("below the floor"), "{text}");
        assert!(text.contains("Atlantis"), "{text}");
        assert!(text.contains("Russia") && text.contains("not on the board"), "{text}");
        assert!(text.contains("dropped_keys"), "{text}");

        let mut v: serde_json::Value = serde_json::from_str(EMBEDDED_RESOURCES_1990).unwrap();
        v["tonnage_per_district"] = serde_json::json!({});
        let errs = parse_and_validate(&v.to_string()).unwrap_err();
        assert!(render_errors(&errs).contains("unknown field"));
    }
}
