//! The resource system, cut one: the 1990 table, the derived HAVE ledger, the
//! stockpile, and the one gate that reads them — at the arsenal's pick.
//!
//! # The table
//!
//! `spheres-sim/data/resources_1990.json` is generated by
//! `tools/resources/make_resources_1990.py` from the web's district artifacts
//! and, for six of the twelve lines, from the transcription file beside the
//! generator (USGS Minerals Yearbook 1990 and the OECD/IAEA Red Book), and
//! committed, the way `districts.json` and the nation files are. It is
//! embedded with `include_str!` for the same reason they are: the library does
//! no file access, the binary is self-contained, and a determinism test cannot
//! fail because a data file moved. It is a STATIC table — never in
//! `WorldState`, never hashed, never saved — so nothing here can move a golden.
//!
//! Two passes, the `data/mod.rs` convention: pass one parses with
//! `deny_unknown_fields` and checks each table against itself (shares sum to
//! one, every share above the pruning floor, quality zero exactly where the
//! presence bit is zero, every transcribed table reconciled to its printed
//! total); pass two resolves every key through `NationId::from_code` and the
//! 1990 roster, so a key that names nobody, or a seat that is not on the board
//! in January 1990, is a refusal addressed to whoever wrote the file rather
//! than a silent zero in somebody's ledger.
//!
//! What the numbers ARE, so no reader multiplies the wrong two:
//! - `national_1990[c][n]` is the transcribed 1990 national figure, verbatim,
//!   in `units[c]`. The USSR's iron is 236,000,000 t (DS-896) and a test says so.
//! - `located[c][n]` is a LOCATION WEIGHT per district — the share of the 1990
//!   owner's figure that sits in that district under one written rule
//!   (`meta.rules.share`). A share is never a tonnage; multiplied by the figure
//!   it says where the output is, which is what changes hands with the ground.
//! - `presence` and `quality` are presence bits and a presence RANK, used to
//!   choose a war aim, never to print a number.
//! - `price_1990[c]` is a 1990 unit value in dollars per `units[c]`, with the
//!   printed figure and its source beside it. Oil has no row; the sim prices
//!   it at `w.oil_price`.
//!
//! # The ledger (spec section 1)
//!
//! HAVE is a FLOW, derived and never stored: a nation's annual own production
//! is the located shares of every district it currently holds times the 1990
//! owner's figure, plus its own figure where the figure was never located.
//! Rebuilt only when the ownership map or the living roster changes (the
//! `districts_epoch` and the alive stamp), refreshed monthly for oil alone,
//! because the oil ledger is `n.oil_mbd` and districts only say where it sits.
//!
//! COVER is the pile: months of NEED in hand, 0..=12, one row per nation only
//! while some line is below twelve. It is written in exactly one place, inside
//! a gate evaluation, and folds back to nothing when every line is full — so
//! an untouched world serializes to the same bytes it did before this module
//! existed, which is the inert invariant the goldens hold.
//!
//! NEED is what this month's attempted gated action wants: one coefficient
//! set per equipment class per billion ordered, for kits that name a
//! technology. The legacy tier is exempt — the transcribed 1990 strength is
//! made of it and the 1990 economy demonstrably fed it — and that exemption is
//! what makes January 1990 inert under any floor.
//!
//! SUPPLY is pure over `&WorldState`: own flow, contract inflow (S2), and an
//! open market that fills the gap whenever any living holder is neither
//! sanctioning nor sanctioned by the buyer, not fighting it, and not below the
//! relation floor. In an open world shortage is an embargo phenomenon, never
//! scarcity; the measured minimum of open holders over 21 seeds and 40 years
//! never fell to zero, which is why the gate costs nothing in every test.
//!
//! The ruling this encodes, verbatim: "It should only hurt if you are trying
//! to do something with the resource and don't have enough of it." Nothing
//! here is read by growth, oil, stability or munitions.

use serde::{Deserialize, Serialize};
use std::borrow::Cow;
use std::collections::BTreeMap;
use std::sync::OnceLock;

use crate::arsenal::{Class, DECK};
use crate::data::{render_errors, LoadError};
use crate::nations::{all_nations, nation_count};
use crate::world::{start_nations, NationId, WorldState};

pub const EMBEDDED_RESOURCES_1990: &str = include_str!("../data/resources_1990.json");
const FILE: &str = "data/resources_1990.json";

/// The twelve lines, alphabetical. Index `i` is bit `i` of a `presence` mask
/// and column `i` of a `quality` row, and the file's `commodities` list must
/// read exactly this. `Commodity` mirrors it variant for variant.
pub const COMMODITIES: [&str; 12] = [
    "bauxite",
    "coal",
    "cobalt",
    "copper",
    "gas",
    "gold",
    "iron",
    "oil",
    "phosphate",
    "platinum_group",
    "rare_earths",
    "uranium",
];

/// The lines with a transcribed 1990 national figure. Since package D2 that
/// is all twelve: six from the web artifact, six from the transcription file
/// (`meta.transcription`). A line is gated, contracted and printed only while
/// it is here; the file's `tracked` must read exactly this.
pub const TRACKED: [&str; 12] = COMMODITIES;

/// `national` keys the generator refuses to seat, and the loader asserts it
/// refused exactly these. Namibia is a roster seat that comes alive after
/// January 1990 and holds no 1990 district; its figures are reported in
/// `meta.counts.dropped_rows` and carried nowhere else. A start nation may
/// never appear here: that would be a transcribed figure thrown away.
pub const DROPPED_KEYS: [&str; 1] = ["Namibia"];

/// The floor a located share must clear. The generator prunes below it and
/// renormalises; "located" means at or above it (spec section 1.2: a 1e-6
/// coalfield sliver must not count as located, as a district, or as a war aim).
pub const LOCATED_MIN_SHARE: f64 = 1e-3;

/// How far a located list's sum may sit from one.
pub const SHARE_SUM_TOLERANCE: f64 = 1e-9;

// ---------------------------------------------------------------------------
// The commodity
// ---------------------------------------------------------------------------

/// One of the twelve lines. Serialized by its file key (`platinum_group`), and
/// its discriminant is its index in `COMMODITIES`.
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum Commodity {
    Bauxite,
    Coal,
    Cobalt,
    Copper,
    Gas,
    Gold,
    Iron,
    Oil,
    Phosphate,
    PlatinumGroup,
    RareEarths,
    Uranium,
}

pub const ALL: [Commodity; 12] = [
    Commodity::Bauxite,
    Commodity::Coal,
    Commodity::Cobalt,
    Commodity::Copper,
    Commodity::Gas,
    Commodity::Gold,
    Commodity::Iron,
    Commodity::Oil,
    Commodity::Phosphate,
    Commodity::PlatinumGroup,
    Commodity::RareEarths,
    Commodity::Uranium,
];

impl Commodity {
    /// 0..11, the presence bit and quality column.
    pub fn idx(self) -> usize {
        self as usize
    }
    pub fn bit(self) -> u16 {
        1 << self.idx()
    }
    pub fn from_idx(i: usize) -> Option<Commodity> {
        ALL.get(i).copied()
    }
    /// The file key: `platinum_group`, `rare_earths`.
    pub fn key(self) -> &'static str {
        COMMODITIES[self.idx()]
    }
    /// The card word: "platinum group", "rare earths".
    pub fn name(self) -> &'static str {
        match self {
            Commodity::Bauxite => "bauxite",
            Commodity::Coal => "coal",
            Commodity::Cobalt => "cobalt",
            Commodity::Copper => "copper",
            Commodity::Gas => "gas",
            Commodity::Gold => "gold",
            Commodity::Iron => "iron",
            Commodity::Oil => "oil",
            Commodity::Phosphate => "phosphate",
            Commodity::PlatinumGroup => "platinum group",
            Commodity::RareEarths => "rare earths",
            Commodity::Uranium => "uranium",
        }
    }
    /// The table's unit — the unit `flow` and every need are counted in. The
    /// loader holds the file's `units` to this.
    pub fn unit(self) -> &'static str {
        match self {
            Commodity::Bauxite => "t",
            Commodity::Coal => "kt",
            Commodity::Cobalt => "t",
            Commodity::Copper => "t",
            Commodity::Gas => "bcf",
            Commodity::Gold => "kg",
            Commodity::Iron => "t",
            Commodity::Oil => "kb/d",
            Commodity::Phosphate => "kt",
            Commodity::PlatinumGroup => "kg",
            Commodity::RareEarths => "t",
            Commodity::Uranium => "t",
        }
    }
    /// Whether the table carries a 1990 figure for this line. Read from the
    /// table so that a line whose figure were ever withdrawn falls back to the
    /// None arm — no consumption, no gate, no contract leg — by itself.
    pub fn tracked(self) -> bool {
        tables().tracked[self.idx()]
    }
    pub fn parse(s: &str) -> Option<Commodity> {
        COMMODITIES.iter().position(|k| *k == s).map(|i| ALL[i])
    }
}

// ---------------------------------------------------------------------------
// The schema
// ---------------------------------------------------------------------------

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct ResourceFile {
    pub meta: Meta,
    pub commodities: Vec<String>,
    pub tracked: Vec<String>,
    /// The sim's unit per tracked line.
    pub units: BTreeMap<String, String>,
    /// Per mined tracked line (never oil): the 1990 unit value.
    pub price_1990: BTreeMap<String, Price>,
    /// commodity -> 1990 start nation code -> the figure, verbatim.
    pub national_1990: BTreeMap<String, BTreeMap<String, Figure>>,
    /// commodity -> 1990 owner code -> [(district, share)], share desc then id.
    pub located: BTreeMap<String, BTreeMap<String, Vec<(String, f64)>>>,
    /// district -> 12-bit mask, bit i = `COMMODITIES[i]` present.
    pub presence: BTreeMap<String, u16>,
    /// district -> presence rank per commodity, 0 absent, 1..3 present.
    pub quality: BTreeMap<String, [u8; 12]>,
    /// district -> share of its 1990 owner's population.
    pub pop_share: BTreeMap<String, f64>,
    /// district -> GHS-POP 1990 count (a modelled surface, not a census line).
    pub pop_1990: BTreeMap<String, u64>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Meta {
    pub generator: String,
    pub upstream: Upstream,
    pub source_sha256: BTreeMap<String, String>,
    pub dropped_keys: Vec<String>,
    pub rules: BTreeMap<String, String>,
    pub counts: Counts,
    /// Mined tracked lines with no sourced 1990 price, and why.
    pub prices_omitted: BTreeMap<String, String>,
    /// The six lines transcribed for this table (package D2): the file they
    /// were read from, its sources, each table reconciled to its printed
    /// total, and every figure the roster could not seat.
    pub transcription: Transcription,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Upstream {
    pub generator: String,
    pub vintage: u32,
    pub sources: BTreeMap<String, UpstreamSource>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct UpstreamSource {
    pub title: String,
    pub url: String,
    pub role: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Counts {
    pub presence_districts: usize,
    pub located_rows: BTreeMap<String, usize>,
    pub located_nations: BTreeMap<String, usize>,
    pub national_rows: BTreeMap<String, usize>,
    pub pruned: BTreeMap<String, BTreeMap<String, usize>>,
    pub unlocated_producers: BTreeMap<String, Vec<String>>,
    pub zero_rows_omitted: BTreeMap<String, usize>,
    pub dropped_rows: BTreeMap<String, BTreeMap<String, f64>>,
    pub pop_districts: usize,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Transcription {
    pub file: String,
    pub lines: Vec<String>,
    pub sources: BTreeMap<String, TranscriptionSource>,
    pub tables: BTreeMap<String, TranscribedTable>,
    /// Figures the source prints for an entity with no roster seat, kept so
    /// nothing is silently lost, seated nowhere.
    pub unmapped_1990: BTreeMap<String, Vec<Unmapped>>,
    /// Producers the source names without a figure: no row, and the board
    /// says "no 1990 figure".
    pub no_figure_1990: BTreeMap<String, Vec<NoFigure>>,
    pub notes: BTreeMap<String, String>,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct TranscriptionSource {
    pub title: String,
    pub licence: String,
    pub url: String,
}

/// One transcribed table reconciled: seated + dropped + unmapped + zero rows
/// equal the total the source prints, or the generator refuses to write.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct TranscribedTable {
    pub table: String,
    pub unit_basis: String,
    pub printed_total_1990: f64,
    pub seated: f64,
    pub dropped: f64,
    pub unmapped: f64,
    pub zero: f64,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Unmapped {
    pub label: String,
    pub value: f64,
    pub unit: String,
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct NoFigure {
    pub roster_key: String,
    pub label: String,
    pub reason: String,
}

/// One transcribed 1990 unit value. `usd_per_unit` is dollars per one
/// `units[c]`, derived from `as_printed` by `conversion`; `source` is the
/// citation verbatim, which the web prints on hover.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Price {
    pub usd_per_unit: f64,
    pub as_printed: String,
    pub conversion: String,
    pub source: String,
}

/// One transcribed 1990 national figure and where it came from: an artifact
/// source key (`meta.upstream.sources` describes it) for the artifact lines,
/// the citation verbatim for the transcribed lines. `flags` are the source's
/// own estimate and footnote flags; `note` is the transcriber's attribution
/// note (a territory folded to its sovereign, a merged row's components).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(deny_unknown_fields)]
pub struct Figure {
    pub value: f64,
    pub source: String,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub flags: Vec<String>,
    #[serde(default, skip_serializing_if = "String::is_empty")]
    pub note: String,
}

/// One located row, flattened for the HAVE build: this district carries
/// `share` of `owner_1990`'s figure for commodity `c`.
#[derive(Clone, Debug)]
pub struct DistrictRow {
    pub district: String,
    pub c: usize,
    pub owner_1990: NationId,
    pub share: f64,
}

/// The parsed file plus the keys resolved to `NationId`, so a consumer never
/// touches a string twice, and the flattened rows `have_table` walks. Built
/// once, behind `tables()`.
#[derive(Clone, Debug)]
pub struct Tables {
    pub file: ResourceFile,
    /// commodity -> nation -> the 1990 figure in the sim's units.
    pub national: BTreeMap<String, BTreeMap<NationId, f64>>,
    /// commodity -> 1990 owner -> located (district, share), share desc.
    pub located: BTreeMap<String, BTreeMap<NationId, Vec<(String, f64)>>>,
    /// By commodity index: whether the file tracks the line.
    pub tracked: [bool; 12],
    /// By `NationId` index: the 1990 figure per commodity, the table's units.
    pub production: Vec<[f64; 12]>,
    /// By `NationId` index: a producer with a figure and no located district,
    /// which keeps its whole figure while it lives.
    pub unlocated: Vec<[bool; 12]>,
    /// Every located (district, commodity, 1990 owner, share) row.
    pub district_rows: Vec<DistrictRow>,
    /// Every (district, presence mask) row.
    pub presence_rows: Vec<(String, u16)>,
    /// By commodity index: the 1990 price in dollars per unit, if priced.
    pub price: [Option<f64>; 12],
}

/// Index of a commodity name in `COMMODITIES`, which is its presence bit and
/// quality column.
pub fn commodity_index(name: &str) -> Option<usize> {
    COMMODITIES.iter().position(|c| *c == name)
}

/// The table. Parsed and validated once; a broken file is a panic with every
/// problem listed, the way `districts::tables` treats `districts.json`.
pub fn tables() -> &'static Tables {
    static T: OnceLock<Tables> = OnceLock::new();
    T.get_or_init(|| {
        let file = parse_and_validate(EMBEDDED_RESOURCES_1990)
            .unwrap_or_else(|e| panic!("{}", render_errors(&e)));
        let nn = nation_count();
        let mut national = BTreeMap::new();
        let mut production = vec![[0.0f64; 12]; nn];
        let mut unlocated = vec![[false; 12]; nn];
        for (c, rows) in &file.national_1990 {
            let ci = commodity_index(c).expect("validated above");
            let mut m = BTreeMap::new();
            for (code, fig) in rows {
                let id = NationId::from_code(code).expect("validated above");
                m.insert(id, fig.value);
                production[id.index()][ci] = fig.value;
                unlocated[id.index()][ci] =
                    !file.located.get(c).is_some_and(|l| l.contains_key(code));
            }
            national.insert(c.clone(), m);
        }
        let mut located = BTreeMap::new();
        let mut district_rows = vec![];
        for (c, rows) in &file.located {
            let ci = commodity_index(c).expect("validated above");
            let mut m = BTreeMap::new();
            for (code, list) in rows {
                let id = NationId::from_code(code).expect("validated above");
                for (d, share) in list {
                    district_rows.push(DistrictRow {
                        district: d.clone(),
                        c: ci,
                        owner_1990: id,
                        share: *share,
                    });
                }
                m.insert(id, list.clone());
            }
            located.insert(c.clone(), m);
        }
        district_rows.sort_by(|a, b| a.district.cmp(&b.district).then(a.c.cmp(&b.c)));
        let presence_rows = file.presence.iter().map(|(d, m)| (d.clone(), *m)).collect();
        let mut tracked = [false; 12];
        for t in &file.tracked {
            tracked[commodity_index(t).expect("validated above")] = true;
        }
        let mut price = [None; 12];
        for (c, p) in &file.price_1990 {
            price[commodity_index(c).expect("validated above")] = Some(p.usd_per_unit);
        }
        Tables {
            file,
            national,
            located,
            tracked,
            production,
            unlocated,
            district_rows,
            presence_rows,
            price,
        }
    })
}

/// Both passes over one source string. Errors are collected, not
/// short-circuited: a regenerated file with three problems should show three.
pub fn parse_and_validate(json: &str) -> Result<ResourceFile, Vec<LoadError>> {
    let file = serde_json::from_str::<ResourceFile>(json)
        .map_err(|e| vec![file_level(e.to_string())])?;
    let mut errors = check_file(&file);
    errors.extend(validate(&file));
    if errors.is_empty() {
        Ok(file)
    } else {
        Err(errors)
    }
}

fn file_level(message: impl Into<String>) -> LoadError {
    LoadError { file: FILE.to_string(), nation: None, message: message.into() }
}

fn nation_level(nation: &str, message: impl Into<String>) -> LoadError {
    LoadError { file: FILE.to_string(), nation: Some(nation.to_string()), message: message.into() }
}

// ---------------------------------------------------------------------------
// Pass one — the file against itself
// ---------------------------------------------------------------------------

/// Bounds that are facts about the table rather than opinions about history:
/// a share is a share, a list of shares sums to one, a rank is 0..3 and is 0
/// exactly where nothing is present, a mined line either has a sourced price
/// or says why it has none, and a transcribed table's rows add up to the
/// total the source prints.
fn check_file(f: &ResourceFile) -> Vec<LoadError> {
    let mut e = vec![];
    if f.commodities != COMMODITIES {
        e.push(file_level(format!(
            "commodities is {:?}; the twelve lines in this build are {:?}, in that order",
            f.commodities, COMMODITIES
        )));
    }
    if f.tracked != TRACKED {
        e.push(file_level(format!("tracked is {:?}, expected {:?}", f.tracked, TRACKED)));
    }
    let tracked: Vec<&str> = TRACKED.to_vec();
    let unit_keys: Vec<&str> = f.units.keys().map(String::as_str).collect();
    if unit_keys != tracked {
        e.push(file_level(format!("units is keyed {:?}, expected the tracked lines", unit_keys)));
    }
    for (c, u) in &f.units {
        if u.trim().is_empty() {
            e.push(file_level(format!("units.{c} is empty")));
        }
        if let Some(k) = Commodity::parse(c) {
            if k.unit() != u {
                e.push(file_level(format!(
                    "units.{c} is {u:?} but this build counts {c} in {:?} — the unit is the enum's, the file must agree",
                    k.unit()
                )));
            }
        }
    }
    for (c, p) in &f.price_1990 {
        if !TRACKED.contains(&c.as_str()) || c == "oil" {
            e.push(file_level(format!(
                "price_1990.{c}: only mined tracked lines carry a price; oil is priced at w.oil_price"
            )));
        }
        if !(p.usd_per_unit.is_finite() && p.usd_per_unit > 0.0) {
            e.push(file_level(format!(
                "price_1990.{c}.usd_per_unit is {}, expected a positive dollar figure",
                p.usd_per_unit
            )));
        }
        for (field, s) in [("source", &p.source), ("as_printed", &p.as_printed), ("conversion", &p.conversion)] {
            if s.trim().is_empty() {
                e.push(file_level(format!(
                    "price_1990.{c}.{field} is empty — iron rule 4: a price is transcribed, so say where from"
                )));
            }
        }
        if f.meta.prices_omitted.contains_key(c) {
            e.push(file_level(format!("price_1990.{c} is both priced and listed in prices_omitted")));
        }
    }
    for c in TRACKED.iter().filter(|c| **c != "oil") {
        if !f.price_1990.contains_key(*c) && !f.meta.prices_omitted.contains_key(*c) {
            e.push(file_level(format!(
                "{c} has no price_1990 row and no prices_omitted reason — an unsourced line is omitted AND says so"
            )));
        }
    }
    if f.national_1990.keys().map(String::as_str).collect::<Vec<_>>() != tracked {
        e.push(file_level("national_1990 must be keyed by exactly the tracked lines"));
    }
    if f.located.keys().map(String::as_str).collect::<Vec<_>>() != tracked {
        e.push(file_level("located must be keyed by exactly the tracked lines"));
    }
    for (c, rows) in &f.national_1990 {
        for (n, fig) in rows {
            if !(fig.value.is_finite() && fig.value > 0.0) {
                e.push(nation_level(n, format!(
                    "national_1990.{c} is {}, expected a positive figure (zero rows are omitted)",
                    fig.value
                )));
            }
            if fig.source.trim().is_empty() {
                e.push(nation_level(n, format!("national_1990.{c} has no source")));
            }
        }
    }
    for (c, rows) in &f.located {
        for (n, list) in rows {
            if list.is_empty() {
                e.push(nation_level(n, format!("located.{c} is an empty list; an unlocated producer is absent, not empty")));
                continue;
            }
            let sum: f64 = list.iter().map(|(_, s)| *s).sum();
            if !((sum - 1.0).abs() <= SHARE_SUM_TOLERANCE) {
                e.push(nation_level(n, format!("located.{c} sums to {sum}, expected 1 within {SHARE_SUM_TOLERANCE}")));
            }
            for (d, s) in list {
                if !(s.is_finite() && *s >= LOCATED_MIN_SHARE && *s <= 1.0) {
                    e.push(nation_level(n, format!(
                        "located.{c} share of {d} is {s}, expected {LOCATED_MIN_SHARE}..=1 (below the floor is pruned, not located)"
                    )));
                }
                if !f.presence.contains_key(d) {
                    e.push(nation_level(n, format!("located.{c} names {d}, which carries no presence bit")));
                }
            }
            for w in list.windows(2) {
                let ((d0, s0), (d1, s1)) = (&w[0], &w[1]);
                if s1 > s0 || (s1 == s0 && d1 <= d0) {
                    e.push(nation_level(n, format!("located.{c} is not sorted share desc then id at {d0} / {d1}")));
                    break;
                }
            }
        }
    }
    if f.presence.is_empty() {
        e.push(file_level("presence is empty"));
    }
    for (d, m) in &f.presence {
        if *m == 0 || *m >= 1 << 12 {
            e.push(file_level(format!("presence.{d} is {m}, expected a non-empty 12-bit mask")));
        }
    }
    if f.quality.keys().ne(f.presence.keys()) {
        e.push(file_level("quality must be keyed exactly like presence"));
    }
    for (d, q) in &f.quality {
        let mask = f.presence.get(d).copied().unwrap_or(0);
        for (i, r) in q.iter().enumerate() {
            let present = mask >> i & 1 == 1;
            if *r > 3 || (*r == 0) == present {
                e.push(file_level(format!(
                    "quality.{d}[{i}] ({}) is {r} but the presence bit is {}; a rank is 1..3 where present and 0 where not",
                    COMMODITIES[i], present as u8
                )));
            }
        }
    }
    for (d, s) in &f.pop_share {
        if !(s.is_finite() && (0.0..=1.0).contains(s)) {
            e.push(file_level(format!("pop_share.{d} is {s}, expected a share in 0..=1")));
        }
    }
    if f.pop_1990.keys().ne(f.pop_share.keys()) {
        e.push(file_level("pop_1990 must be keyed exactly like pop_share"));
    }
    if f.meta.dropped_keys != DROPPED_KEYS {
        e.push(file_level(format!(
            "meta.dropped_keys is {:?}; this build expects exactly {:?} to be unseated",
            f.meta.dropped_keys, DROPPED_KEYS
        )));
    }
    let c = &f.meta.counts;
    if c.presence_districts != f.presence.len() || c.pop_districts != f.pop_share.len() {
        e.push(file_level("meta.counts district totals do not describe the file"));
    }
    for t in TRACKED {
        let rows = f.located.get(t).map(|m| m.values().map(Vec::len).sum::<usize>()).unwrap_or(0);
        let nats = f.located.get(t).map(BTreeMap::len).unwrap_or(0);
        let natl = f.national_1990.get(t).map(BTreeMap::len).unwrap_or(0);
        if c.located_rows.get(t) != Some(&rows)
            || c.located_nations.get(t) != Some(&nats)
            || c.national_rows.get(t) != Some(&natl)
        {
            e.push(file_level(format!("meta.counts for {t} do not describe the file")));
        }
    }
    // The transcribed six: every table reconciles to the total the source
    // prints, and the seated sum is the sum of the rows this file carries.
    let tr = &f.meta.transcription;
    for (c, t) in &tr.tables {
        if !tr.lines.contains(c) {
            e.push(file_level(format!("meta.transcription.tables.{c} is not a transcribed line")));
        }
        let got = t.seated + t.dropped + t.unmapped + t.zero;
        if got != t.printed_total_1990 {
            e.push(file_level(format!(
                "meta.transcription.tables.{c}: seated + dropped + unmapped + zero = {got}, the table prints {}",
                t.printed_total_1990
            )));
        }
        let seated: f64 = f.national_1990.get(c).map(|m| m.values().map(|v| v.value).sum()).unwrap_or(0.0);
        if seated != t.seated {
            e.push(file_level(format!(
                "meta.transcription.tables.{c}: seated {} but the rows carried sum to {seated}",
                t.seated
            )));
        }
    }
    for c in &tr.lines {
        if !tr.tables.contains_key(c) {
            e.push(file_level(format!("meta.transcription.tables has no entry for {c}")));
        }
        if let Some(rows) = f.national_1990.get(c) {
            for (n, fig) in rows {
                if !fig.source.contains("1990") {
                    e.push(nation_level(n, format!("national_1990.{c}: a transcribed row must cite its 1990 table")));
                }
            }
        }
    }
    e
}

// ---------------------------------------------------------------------------
// Pass two — the file against the roster
// ---------------------------------------------------------------------------

/// Nothing here can be checked while looking at the file alone: every key
/// must name a nation this build has, that nation must be on the board in
/// January 1990, every located producer must have a figure, a dropped key
/// must never be a start nation, and a producer named without a figure must
/// be a start nation that indeed has no row.
fn validate(f: &ResourceFile) -> Vec<LoadError> {
    let mut e = vec![];
    let start = start_nations();
    for (c, rows) in &f.national_1990 {
        for code in rows.keys() {
            match NationId::from_code(code) {
                None => e.push(nation_level(code, format!(
                    "national_1990.{c} names a nation this build does not have — the join is the roster code, and dropped_keys are the only permitted misses"
                ))),
                Some(id) if !start.contains(&id) => e.push(nation_level(code, format!(
                    "national_1990.{c} names a seat that is not on the board in January 1990 — successor states inherit through the located shares, never a row of their own"
                ))),
                Some(_) => {}
            }
        }
    }
    for (c, rows) in &f.located {
        for code in rows.keys() {
            if !f.national_1990.get(c).is_some_and(|m| m.contains_key(code)) {
                e.push(nation_level(code, format!("located.{c} has shares but no national_1990.{c} figure to locate")));
            }
        }
    }
    for code in &f.meta.dropped_keys {
        if let Some(id) = NationId::from_code(code) {
            if start.contains(&id) {
                e.push(nation_level(code, "is listed in dropped_keys but is a 1990 start nation — a transcribed figure was thrown away"));
            }
        }
    }
    for (c, list) in &f.meta.transcription.no_figure_1990 {
        for nf in list {
            match NationId::from_code(&nf.roster_key) {
                None => e.push(nation_level(&nf.roster_key, format!(
                    "meta.transcription.no_figure_1990.{c} names a nation this build does not have"
                ))),
                Some(id) if !start.contains(&id) => e.push(nation_level(&nf.roster_key, format!(
                    "meta.transcription.no_figure_1990.{c} names a seat that is not on the board in January 1990"
                ))),
                Some(_) if f.national_1990.get(c).is_some_and(|m| m.contains_key(&nf.roster_key)) => {
                    e.push(nation_level(&nf.roster_key, format!(
                        "meta.transcription.no_figure_1990.{c} lists a nation that has a {c} row"
                    )))
                }
                Some(_) => {}
            }
        }
    }
    e
}

// ---------------------------------------------------------------------------
// The mechanic constants (Appendix A: named, classed, justified)
// ---------------------------------------------------------------------------

/// The pile, in months of need (M). Between the IEA's 90-day civil stock
/// obligation and the Stock Piling Act's three-year war stockpile. No physical
/// decay: cover erodes only when a line asks for what it cannot get.
pub const BUFFER_MONTHS: f64 = 12.0;

/// What a seller keeps of its own draw before it counts a surplus (M). The
/// same year the buyer holds, so neither side of a contract is asked to run
/// on less than the other.
pub const RESERVE_MONTHS: f64 = BUFFER_MONTHS;

/// Below this relation a holder will not sell (M). The zero of
/// `statecraft::propose_trade`'s curve, statecraft.rs 623; −30 and 0 were
/// both measured silent over 21 seeds × 40 years, so the floor sits between
/// two values that change nothing in an open world.
pub const RELATION_FLOOR: f64 = -20.0;

// NEED coefficients, kt per $bn ordered, per equipment class (M; order of
// magnitude, one platform per number). Each is a chain of two transcribed
// facts — a platform's mass and price, and the ore-and-coke burden of a tonne
// of steel — and none pretends to more than its first digit.
//
// Naval: a DDG-51 displaces ~8,300 t at ~$0.9bn FY90, so a naval billion is
// ~9 kt of steel. BF-BOF steel takes ~1.4 t of iron ore and ~0.78 t of coking
// coal per tonne of crude (worldsteel): 9 × 1.4 ≈ 12 kt ore, 9 × 0.78 ≈ 7 kt
// coal — rounded to 6.5 because a hull is not all crude steel.
/// Iron ore per $bn of naval kit, kt.
pub const NAVAL_ORE_KT_PER_BN: f64 = 12.0;
/// Coking coal per $bn of naval kit, kt.
pub const NAVAL_COAL_KT_PER_BN: f64 = 6.5;
// Armour: an M1A1 is ~62 t at ~$4.3m, so an armoured billion is ~14 kt of
// steel; × 1.4 ≈ 20 kt ore, × 0.78 ≈ 11 kt coal.
/// Iron ore per $bn of armour, kt.
pub const ARMOUR_ORE_KT_PER_BN: f64 = 20.0;
/// Coking coal per $bn of armour, kt.
pub const ARMOUR_COAL_KT_PER_BN: f64 = 11.0;
// Air: an F-16C is ~8.6 t empty, ~78% aluminium, at ~$20m; 4.5 t of bauxite
// per tonne of aluminium → ~50 airframes × 6.7 t Al × 4.5 ≈ 1.5 kt of bauxite
// per billion, rounded down.
/// Bauxite per $bn of aircraft, kt.
pub const AIR_BAUXITE_KT_PER_BN: f64 = 1.4;
// Missile and space: cabling and electronics. A Tomahawk is ~1.4 t at ~$1.4m
// and ~5% copper by mass → ~700 rounds × 70 kg ≈ 0.05 kt per billion; a
// satellite bus is denser in copper; 0.1 covers both.
/// Copper per $bn of missiles or spacecraft, kt.
pub const MISSILE_COPPER_KT_PER_BN: f64 = 0.1;
// Infantry: post-1990 infantry kit is electronics (Link 16, C4ISR, Raven);
// negligible tonnage. No coefficient.

// ---------------------------------------------------------------------------
// The derived ledger
// ---------------------------------------------------------------------------

/// Derived HAVE cache. `built == false` IS the None arm: every accessor
/// answers "not gated". Never serialized, never hashed.
#[derive(Clone, Debug, Default)]
pub struct Have {
    /// By `NationId` index; annual; the table's units; oil = kb/d.
    pub flow: Vec<[f64; 12]>,
    /// By `NationId` index: presence bits of every district held, plus every
    /// line with a positive flow.
    pub presence: Vec<u16>,
    pub built: bool,
    pub epoch: u64,
    /// `(nations.len(), alive count)` — a birth or a death rebuilds.
    pub alive_stamp: (usize, usize),
}

const OIL: usize = Commodity::Oil as usize;

fn alive_stamp(w: &WorldState) -> (usize, usize) {
    (w.nations.len(), w.nations.iter().filter(|n| n.alive).count())
}

/// HAVE for every nation: a pure function of the 1990 table and the current
/// ownership map. One pass over the located rows and the presence rows —
/// never over `w.districts`. Measured 0.10 ms at 137 nations, paid only on an
/// ownership change.
pub fn have_table(w: &WorldState) -> Have {
    let t = tables();
    let nn = nation_count();
    let mut flow = vec![[0.0f64; 12]; nn];
    let mut presence = vec![0u16; nn];
    // Unlocated (national-only) production stays with its 1990 owner while it
    // lives. Annexation moves none of it; nothing can, honestly.
    for (i, p) in t.production.iter().enumerate() {
        let alive = NationId::from_index(i)
            .and_then(|id| w.nation_opt(id))
            .is_some_and(|n| n.alive);
        if !alive {
            continue;
        }
        for c in 0..12 {
            if c != OIL && t.unlocated[i][c] {
                flow[i][c] += p[c];
            }
        }
    }
    // Located production follows the district it sits in.
    for r in &t.district_rows {
        if r.c == OIL {
            continue;
        }
        if let Some(cur) = w.districts.get(&r.district) {
            flow[cur.index()][r.c] += r.share * t.production[r.owner_1990.index()][r.c];
        }
    }
    // Oil is the single ledger, kb/d; districts only say where it sits.
    for n in w.nations.iter().filter(|n| n.alive) {
        flow[n.id.index()][OIL] = n.oil_mbd * 1000.0;
    }
    for (d, mask) in &t.presence_rows {
        if let Some(cur) = w.districts.get(d) {
            presence[cur.index()] |= mask;
        }
    }
    for (i, f) in flow.iter().enumerate() {
        for c in 0..12 {
            if f[c] > 0.0 {
                presence[i] |= 1 << c;
            }
        }
    }
    Have { flow, presence, built: true, epoch: w.districts_epoch, alive_stamp: alive_stamp(w) }
}

/// The SYSTEMS entry, between `economy` and `tech`: the cache must exist
/// before tech and arsenal read it. Rebuilds on an ownership or roster change;
/// otherwise refreshes the oil column, which moves monthly.
pub fn tick(w: &mut WorldState) {
    let stamp = alive_stamp(w);
    let stale = !w.resource_have.built
        || w.resource_have.epoch != w.districts_epoch
        || w.resource_have.alive_stamp != stamp;
    if stale {
        w.resource_have = have_table(w);
    } else {
        for n in w.nations.iter().filter(|n| n.alive) {
            w.resource_have.flow[n.id.index()][OIL] = n.oil_mbd * 1000.0;
        }
    }
    if !w.rules.resource_gates {
        return;
    }
    deliver_contracts(w);
    expire_offers(w);
}

/// Contract delivery (package S2). A no-op while `contracts` is empty, which
/// is every world cut one produces; S2 lands the money legs, force majeure
/// and expiry here.
fn deliver_contracts(w: &mut WorldState) {
    if w.resources.contracts.is_empty() {}
}

/// Offer expiry (package S2). A no-op while `offers` is empty.
fn expire_offers(w: &mut WorldState) {
    if w.resources.offers.is_empty() {}
}

// ---------------------------------------------------------------------------
// The persisted state
// ---------------------------------------------------------------------------

fn is_zero(v: &u32) -> bool {
    *v == 0
}

/// Everything the resource system persists. Every member is skipped when
/// empty so an untouched world serializes exactly as it did before this
/// existed. `Vec<Cover>` sorted by nation and `Vec<Refusal>` sorted by key
/// rather than maps: serde_json refuses non-string map keys, and
/// `statecraft.reputation: Vec<(NationId, f64)>` is the house idiom for a
/// sparse per-nation row. Upserts are `binary_search` + insert; iteration is
/// sorted by construction.
#[derive(Clone, Debug, Default, Serialize, Deserialize, PartialEq)]
pub struct Resources {
    /// Sorted by nation. A row exists only while some line is below twelve.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub cover: Vec<Cover>,
    /// Creation order (S2).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub contracts: Vec<Contract>,
    /// Creation order (S2).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub offers: Vec<Offer>,
    /// Sorted by (buyer, seller, commodity) (S3).
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub refusals: Vec<Refusal>,
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub grievances: Vec<Grievance>,
    #[serde(default, skip_serializing_if = "is_zero")]
    pub next_id: u32,
}

impl Resources {
    pub fn is_empty(&self) -> bool {
        self.cover.is_empty()
            && self.contracts.is_empty()
            && self.offers.is_empty()
            && self.refusals.is_empty()
            && self.grievances.is_empty()
            && self.next_id == 0
    }
}

/// Months of need in hand per line, 0..=12. Materialised on the first write
/// below twelve; removed when every line is back at twelve.
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Cover {
    pub nation: NationId,
    pub months: [f64; 12],
}

/// One side of a bundle (S2).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum Leg {
    /// The table's units per month; oil is kb/d and settles as money.
    Commodity { c: Commodity, per_month: f64 },
    Money { bn_per_year: f64 },
    /// One-shot at signing.
    District { id: String },
}

#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Contract {
    pub id: u32,
    pub from: NationId,
    pub to: NationId,
    /// from → to.
    pub give: Vec<Leg>,
    /// to → from.
    pub take: Vec<Leg>,
    pub months_left: u32,
    pub months_total: u32,
    /// `month_abs` at signing.
    pub since: i32,
    pub depth: f64,
}

/// An AI buyer's standing offer to the player (S3).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Offer {
    pub id: u32,
    pub from: NationId,
    pub to: NationId,
    pub give: Vec<Leg>,
    pub take: Vec<Leg>,
    pub months: u32,
    /// `month_abs`.
    pub expires: i32,
}

/// A torn-up contract, remembered by the victim (S2).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Grievance {
    pub victim: NationId,
    pub breaker: NationId,
    /// `month_abs`.
    pub until: i32,
}

/// Why a receiver refuses. Each carries fixed prose (S2 pins it).
#[derive(Clone, Copy, Debug, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum Reason {
    AtWar,
    Embargoed,
    BrokeContract,
    Distrust,
    NoSurplus,
    LandContested,
    NotForSale,
    LandDistrust,
    GovernmentWouldFall,
    LastDistrict,
    NotForThatPrice,
    Unanswered,
}

/// A seller's refusal, as the buyer remembers it (S3 writes it).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Refusal {
    pub buyer: NationId,
    pub seller: NationId,
    pub c: Commodity,
    pub reason: Reason,
    pub heat: f64,
    pub asks: u32,
}

/// What a resource war is for: the district and the line (S3 writes it;
/// declared here so the save shape settles once).
#[derive(Clone, Debug, Serialize, Deserialize, PartialEq)]
pub struct Aim {
    pub district: String,
    pub commodity: Commodity,
}

// ---------------------------------------------------------------------------
// Accessors — pure; every one answers the None arm when the cache is unbuilt
// ---------------------------------------------------------------------------

/// The cache, or a local build when it is unbuilt (the month after a load,
/// before the first tick).
pub fn have(w: &WorldState) -> Cow<'_, Have> {
    if w.resource_have.built {
        Cow::Borrowed(&w.resource_have)
    } else {
        Cow::Owned(have_table(w))
    }
}

/// Annual own production of `c`, the table's units; 0 when unbuilt.
pub fn flow(w: &WorldState, id: NationId, c: Commodity) -> f64 {
    if !w.resource_have.built {
        return 0.0;
    }
    w.resource_have.flow.get(id.index()).map_or(0.0, |f| f[c.idx()])
}

/// Months of need in hand; `BUFFER_MONTHS` when no row exists.
pub fn cover(w: &WorldState, id: NationId, c: Commodity) -> f64 {
    match w.resources.cover.binary_search_by_key(&id, |r| r.nation) {
        Ok(i) => w.resources.cover[i].months[c.idx()],
        Err(_) => BUFFER_MONTHS,
    }
}

/// This month's need: what the kit procurement would pick wants, at the
/// nation's line. Zero for the legacy tier and for a nation with nothing to
/// buy.
pub fn draw(w: &WorldState, id: NationId) -> [f64; 12] {
    let n = w.nation(id);
    match crate::arsenal::pick(n) {
        Some(kit) => kit_need(kit, crate::arsenal::line_of(n)),
        None => [0.0; 12],
    }
}

/// Σ contract legs `id` gives of `c` this month (S2; zero while no contracts).
pub fn committed_out(w: &WorldState, id: NationId, c: Commodity) -> f64 {
    contract_legs(w, id, c, true)
}

/// Σ contract legs `id` receives of `c` this month (S2; zero while no contracts).
pub fn contracted_in(w: &WorldState, id: NationId, c: Commodity) -> f64 {
    contract_legs(w, id, c, false)
}

fn contract_legs(w: &WorldState, id: NationId, c: Commodity, giving: bool) -> f64 {
    let mut q = 0.0;
    for k in &w.resources.contracts {
        let (from_legs, to_legs) = (&k.give, &k.take);
        let legs: &[Leg] = if giving {
            if k.from == id { from_legs } else if k.to == id { to_legs } else { continue }
        } else if k.to == id {
            from_legs
        } else if k.from == id {
            to_legs
        } else {
            continue;
        };
        for l in legs {
            if let Leg::Commodity { c: lc, per_month } = l {
                if *lc == c {
                    q += per_month;
                }
            }
        }
    }
    q
}

/// What `id` could sell of `c` this month: own flow less its own draw, its
/// commitments, and a year of its draw held in reserve.
pub fn surplus(w: &WorldState, id: NationId, c: Commodity) -> f64 {
    let d = draw(w, id)[c.idx()];
    flow(w, id, c) / 12.0 - d - committed_out(w, id, c) - d * RESERVE_MONTHS / 12.0
}

fn holds(h: &Have, id: NationId, c: Commodity) -> bool {
    h.flow.get(id.index()).is_some_and(|f| f[c.idx()] > 0.0)
}

fn open_to(w: &WorldState, buyer: NationId, h: NationId) -> bool {
    !w.is_sanctioning(h, buyer)
        && !w.is_sanctioning(buyer, h)
        && !crate::statecraft::belligerents(w, buyer, h)
        && w.relation(buyer, h) >= RELATION_FLOOR
}

/// The first living holder of `c`, in `NationId` order, that is open to
/// `buyer`: not sanctioning it, not sanctioned by it, not fighting it, and
/// not below the relation floor.
pub fn open_holder(w: &WorldState, buyer: NationId, c: Commodity) -> Option<NationId> {
    let h = have(w);
    all_nations()
        .iter()
        .copied()
        .filter(|id| *id != buyer && holds(&h, *id, c))
        .filter(|id| w.nation_opt(*id).is_some_and(|n| n.alive))
        .find(|id| open_to(w, buyer, *id))
}

/// Every living producer of `c`, `NationId` order.
pub fn producers(w: &WorldState, c: Commodity) -> Vec<NationId> {
    let h = have(w);
    all_nations()
        .iter()
        .copied()
        .filter(|id| holds(&h, *id, c) && w.nation_opt(*id).is_some_and(|n| n.alive))
        .collect()
}

/// Who feeds `need` of `c` to `buyer` this month, and how much of it.
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Supply {
    pub own: f64,
    pub contracts: f64,
    pub market: f64,
    pub available: f64,
    pub holder: Option<NationId>,
    /// Some living producer other than the buyer exists at all — the
    /// difference between "every producer refuses" and "nobody produces it".
    pub any_producer: bool,
}

/// Pure over `&WorldState`, no RNG. Own flow, contract inflow, and an open
/// market that fills the gap while any holder is open. `ration` is 0 in cut
/// one (spec section 1.4; cut two adds the sanction ration).
pub fn supply(w: &WorldState, buyer: NationId, c: Commodity, need: f64) -> Supply {
    if !c.tracked() || !w.resource_have.built {
        return Supply { own: 0.0, contracts: 0.0, market: 0.0, available: 0.0, holder: None, any_producer: false };
    }
    let own = flow(w, buyer, c) / 12.0;
    let contracts = contracted_in(w, buyer, c);
    let h = &w.resource_have;
    let mut any_producer = false;
    let mut holder = None;
    for id in all_nations().iter().copied() {
        if id == buyer || !holds(h, id, c) || !w.nation_opt(id).is_some_and(|n| n.alive) {
            continue;
        }
        any_producer = true;
        if open_to(w, buyer, id) {
            holder = Some(id);
            break;
        }
    }
    let market = if holder.is_some() { (need - own - contracts).max(0.0) } else { 0.0 };
    Supply { own, contracts, market, available: own + contracts + market, holder, any_producer }
}

/// What ordering `kit` with `line_bn` this month wants, in the table's units
/// per month. Zero for the legacy tier (`tech: None`).
pub fn kit_need(kit: u16, line_bn: f64) -> [f64; 12] {
    let mut need = [0.0; 12];
    let Some(def) = DECK.get(kit as usize) else { return need };
    if def.tech.is_none() || line_bn <= 0.0 {
        return need;
    }
    match def.class {
        Class::Naval => {
            need[Commodity::Iron.idx()] = line_bn * NAVAL_ORE_KT_PER_BN * 1000.0;
            need[Commodity::Coal.idx()] = line_bn * NAVAL_COAL_KT_PER_BN;
        }
        Class::Armour => {
            need[Commodity::Iron.idx()] = line_bn * ARMOUR_ORE_KT_PER_BN * 1000.0;
            need[Commodity::Coal.idx()] = line_bn * ARMOUR_COAL_KT_PER_BN;
        }
        Class::Air => {
            need[Commodity::Bauxite.idx()] = line_bn * AIR_BAUXITE_KT_PER_BN * 1000.0;
        }
        Class::Missile | Class::Space => {
            need[Commodity::Copper.idx()] = line_bn * MISSILE_COPPER_KT_PER_BN * 1000.0;
        }
        Class::Infantry => {}
    }
    need
}

/// `(year − 1990) × 12 + (month − 1)`, the web's `month_index`.
pub fn month_abs(w: &WorldState) -> i32 {
    (w.year - 1990) * 12 + (w.month as i32 - 1)
}

// ---------------------------------------------------------------------------
// The gate
// ---------------------------------------------------------------------------

/// A line that asked for what it could not get.
#[derive(Clone, Debug, PartialEq)]
pub struct Stall {
    pub nation: NationId,
    pub kit: u16,
    pub commodity: Commodity,
    /// "every producer refuses" | "nobody produces it"
    pub why: &'static str,
}

impl Stall {
    pub fn headline(&self) -> String {
        format!(
            "{}: {} line delayed - needs {}; {}.",
            self.nation.name(),
            DECK[self.kit as usize].name,
            self.commodity.name(),
            self.why
        )
    }
}

/// The only writer of `cover`. Spec section 1.3: a shortfall month takes
/// `1 − available/need` off the pile; a surplus month puts back
/// `min(1, (available − need)/need)`, capped at twelve. The row is
/// materialised on the first write below twelve and removed when every line
/// is back at twelve, so a full pile is no row and no bytes.
pub(crate) fn write_cover(w: &mut WorldState, id: NationId, c: Commodity, available: f64, need: f64) -> f64 {
    let cur = cover(w, id, c);
    let next = if need <= 0.0 {
        cur
    } else if available < need {
        cur - (1.0 - available / need)
    } else {
        cur + ((available - need) / need).min(1.0)
    }
    .clamp(0.0, BUFFER_MONTHS);
    let ci = c.idx();
    match w.resources.cover.binary_search_by_key(&id, |r| r.nation) {
        Ok(i) => {
            w.resources.cover[i].months[ci] = next;
            if w.resources.cover[i].months.iter().all(|m| *m >= BUFFER_MONTHS) {
                w.resources.cover.remove(i);
            }
        }
        Err(i) => {
            if next < BUFFER_MONTHS {
                let mut months = [BUFFER_MONTHS; 12];
                months[ci] = next;
                w.resources.cover.insert(i, Cover { nation: id, months });
            }
        }
    }
    next
}

/// Read-only: could `id` feed `kit` at `line` this month?
fn inputs_held(w: &WorldState, id: NationId, kit: u16, line: f64) -> bool {
    let need = kit_need(kit, line);
    ALL.iter()
        .filter(|c| c.tracked() && need[c.idx()] > 0.0)
        .all(|c| supply(w, id, *c, need[c.idx()]).available >= need[c.idx()])
}

/// The gate at the arsenal's pick. Checks only the chosen kit (≤ four
/// queries); writes the pile for each line it asked about; stalls only when a
/// line is short AND the pile is empty. Then: a player's stated preference
/// stalls with the message and the money banks; the AI ranks the rest — sort
/// only now — and takes the best kit whose inputs are held. Returns the kit
/// to order and, if the chosen kit was skipped or the preference stalled,
/// why. Charges nothing.
pub fn gate(w: &mut WorldState, id: NationId, kit: u16, line: f64) -> (Option<u16>, Option<Stall>) {
    let need = kit_need(kit, line);
    if need.iter().all(|q| *q <= 0.0) {
        return (Some(kit), None);
    }
    let mut short: Option<(Commodity, &'static str)> = None;
    for c in ALL.iter().filter(|c| c.tracked() && need[c.idx()] > 0.0) {
        let s = supply(w, id, *c, need[c.idx()]);
        let cv = write_cover(w, id, *c, s.available, need[c.idx()]);
        if s.available < need[c.idx()] && cv <= 0.0 && short.is_none() {
            short = Some((*c, if s.any_producer { "every producer refuses" } else { "nobody produces it" }));
        }
    }
    let Some((c, why)) = short else { return (Some(kit), None) };
    let stall = Stall { nation: id, kit, commodity: c, why };
    let preferred = w
        .nation(id)
        .arsenal
        .preference
        .as_deref()
        .and_then(crate::arsenal::index_of)
        == Some(kit);
    if preferred {
        return (None, Some(stall));
    }
    for alt in crate::arsenal::ranked(w.nation(id)).into_iter().filter(|k| *k != kit) {
        if inputs_held(w, id, alt, line) {
            return (Some(alt), Some(stall));
        }
    }
    (None, Some(stall))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::init::world_1990;
    use crate::world::GameRules;

    /// D1's gate, from the sim's side: the committed table loads through both
    /// passes, and the facts the spec pins (section 2.4) hold on what loaded.
    /// Nothing here touches `WorldState`; the table is static and unhashed.
    #[test]
    fn the_1990_resource_table_loads_and_holds_its_invariants() {
        let t = tables();
        let f = &t.file;

        // The join: every key seated, exactly one key refused, and it is not a
        // start nation (Namibia is a roster seat that comes alive later).
        assert_eq!(f.meta.dropped_keys, DROPPED_KEYS);
        let namibia = NationId::from_code("Namibia").expect("Namibia is a roster seat");
        assert!(!start_nations().contains(&namibia), "Namibia must not be a start nation while it is dropped");
        for c in TRACKED {
            for code in f.national_1990[c].keys() {
                assert!(NationId::from_code(code).is_some(), "{code} does not resolve");
            }
        }
        // All twelve lines are tracked since D2, and the enum agrees with the file.
        assert_eq!(f.tracked.len(), 12);
        for c in ALL {
            assert!(c.tracked(), "{} is not tracked", c.key());
            assert_eq!(f.units[c.key()], c.unit());
            assert_eq!(Commodity::parse(c.key()), Some(c));
            assert_eq!(c.idx(), commodity_index(c.key()).unwrap());
        }

        // The transcribed figure, exact: the USSR's iron is DS-896's 236,000,000 t.
        let ussr = NationId::from_code("USSR").unwrap();
        assert_eq!(t.national["iron"][&ussr], 236_000_000.0);
        assert_eq!(f.national_1990["iron"]["USSR"].source, "ds896_iron");

        // SPEC 7.3's named assertion: THE USSR MUST HOLD URANIUM THROUGH THE
        // UNLOCATED-PRODUCER RULE. No Soviet district carries a uranium site
        // (a survey hole), so the 14,000 tU the Red Book prints stays with
        // the USSR while it lives, and would vanish if "located" were the
        // only way to hold a figure.
        assert_eq!(t.national["uranium"][&ussr], 14_000.0);
        assert!(!t.located["uranium"].contains_key(&ussr));
        assert!(t.unlocated[ussr.index()][Commodity::Uranium.idx()]);
        assert!(f.meta.counts.unlocated_producers["uranium"].iter().any(|n| n == "USSR"));
        assert!(f.national_1990["uranium"]["USSR"].flags.iter().any(|x| x.contains("Secretariat estimate")));

        // Every transcribed table reconciles to the total its source prints.
        for c in &f.meta.transcription.lines {
            let tb = &f.meta.transcription.tables[c];
            assert_eq!(tb.seated + tb.dropped + tb.unmapped + tb.zero, tb.printed_total_1990, "{c}");
        }

        // Shares: sum to one, every one at or above the floor, sorted.
        for c in TRACKED {
            for (code, list) in &f.located[c] {
                let sum: f64 = list.iter().map(|(_, s)| s).sum();
                assert!((sum - 1.0).abs() <= SHARE_SUM_TOLERANCE, "{c}/{code} sums to {sum}");
                assert!(list.iter().all(|(_, s)| *s >= LOCATED_MIN_SHARE), "{c}/{code} carries a pruned share");
            }
        }
        let ussr_iron = &t.located["iron"][&ussr];
        assert!(!ussr_iron.is_empty());
        assert!(ussr_iron.windows(2).all(|w| w[0].1 >= w[1].1));
        // The Soviet coalfield tail was pruned, not carried at 1e-6.
        assert!(f.meta.counts.pruned["coal"]["USSR"] > 0);
        assert!(f.located["coal"]["USSR"].iter().all(|(_, s)| *s >= LOCATED_MIN_SHARE));

        // The USA: an unlocated oil producer (its ledger is oil_mbd, and the
        // shares only say where it sits — nowhere, so nothing can be taken),
        // and no 1990 bauxite row at all.
        let usa = NationId::from_code("USA").unwrap();
        assert!(!t.located["oil"].contains_key(&usa));
        assert!(t.national["oil"].contains_key(&usa));
        assert!(f.meta.counts.unlocated_producers["oil"].iter().any(|n| n == "USA"));
        assert!(!t.national["bauxite"].contains_key(&usa));

        // Presence and quality: 1,471 districts, rank 0 exactly where the bit is 0.
        assert_eq!(f.presence.len(), 1471);
        assert_eq!(f.quality.len(), 1471);
        for (d, q) in &f.quality {
            let mask = f.presence[d];
            for i in 0..12 {
                assert_eq!(q[i] == 0, mask >> i & 1 == 0, "{d}[{i}]");
            }
        }
        assert!(commodity_index("iron") == Some(6) && commodity_index("rice").is_none());

        // Prices: oil never has a row; every mined line is priced with a
        // source or named as omitted.
        assert!(!f.price_1990.contains_key("oil"));
        assert!(t.price[OIL].is_none());
        for c in TRACKED.iter().filter(|c| **c != "oil") {
            let priced = f.price_1990.get(*c).is_some_and(|p| p.usd_per_unit > 0.0 && !p.source.trim().is_empty());
            let omitted = f.meta.prices_omitted.contains_key(*c);
            assert!(priced ^ omitted, "{c}: priced={priced} omitted={omitted}");
        }

        // The resolved index agrees with the file.
        for c in TRACKED {
            assert_eq!(t.national[c].len(), f.national_1990[c].len());
            assert_eq!(t.located[c].len(), f.located[c].len());
        }
        assert_eq!(t.district_rows.len(), f.meta.counts.located_rows.values().sum::<usize>());
        assert_eq!(t.presence_rows.len(), 1471);
    }

    /// The loader refuses what it should: an unknown field, a share below the
    /// floor, a key that names nobody, a dropped key that is a start nation,
    /// and a transcribed table that no longer adds up. Each is a listed error,
    /// not a panic and not a silent default.
    #[test]
    fn the_loader_refuses_a_bad_table() {
        let mut v: serde_json::Value = serde_json::from_str(EMBEDDED_RESOURCES_1990).unwrap();
        v["located"]["iron"]["USSR"][0][1] = serde_json::json!(1e-4);
        v["national_1990"]["iron"]["Atlantis"] = serde_json::json!({"value": 1.0, "source": "x"});
        v["national_1990"]["iron"]["Russia"] = serde_json::json!({"value": 1.0, "source": "x"});
        v["meta"]["dropped_keys"] = serde_json::json!(["USA"]);
        v["national_1990"]["uranium"]["USSR"]["value"] = serde_json::json!(14001.0);
        let errs = parse_and_validate(&v.to_string()).unwrap_err();
        let text = render_errors(&errs);
        assert!(text.contains("sums to"), "{text}");
        assert!(text.contains("below the floor"), "{text}");
        assert!(text.contains("Atlantis"), "{text}");
        assert!(text.contains("Russia") && text.contains("not on the board"), "{text}");
        assert!(text.contains("dropped_keys"), "{text}");
        assert!(text.contains("rows carried sum to"), "{text}");

        let mut v: serde_json::Value = serde_json::from_str(EMBEDDED_RESOURCES_1990).unwrap();
        v["tonnage_per_district"] = serde_json::json!({});
        let errs = parse_and_validate(&v.to_string()).unwrap_err();
        assert!(render_errors(&errs).contains("unknown field"));
    }

    fn built(mut w: WorldState) -> WorldState {
        w.reindex();
        tick(&mut w);
        w
    }

    fn code(s: &str) -> NationId {
        NationId::from_code(s).unwrap()
    }

    /// HAVE is the transcribed figure, located and summed back: the USSR's
    /// iron is 236,000,000 t after renormalisation, the USA's oil is its
    /// `oil_mbd` ledger and nothing else, the USA mines no bauxite, and the
    /// three figures the spec names read as the table prints them. (The
    /// spec's sketch wrote Chile's copper as 1,588,000; the artifact carries
    /// DS-896's 1,590,000 and the table is what is pinned.) Every located
    /// share is at or above the floor and each nation's shares sum to one.
    #[test]
    fn have_is_the_transcribed_figure() {
        let w = built(world_1990(GameRules::default()));
        let (ussr, usa, china, chile) = (code("USSR"), code("USA"), code("China"), code("Chile"));
        let near = |a: f64, b: f64, tol: f64| (a - b).abs() <= tol;
        assert!(near(flow(&w, ussr, Commodity::Iron), 236_000_000.0, 1.0), "{}", flow(&w, ussr, Commodity::Iron));
        assert_eq!(flow(&w, usa, Commodity::Oil), w.nation(usa).oil_mbd * 1000.0);
        assert_eq!(flow(&w, usa, Commodity::Bauxite), 0.0);
        assert!(near(flow(&w, china, Commodity::Coal), 1_079_300.0, 1.0), "{}", flow(&w, china, Commodity::Coal));
        assert!(near(flow(&w, chile, Commodity::Copper), 1_590_000.0, 1.0), "{}", flow(&w, chile, Commodity::Copper));
        assert!(near(flow(&w, ussr, Commodity::Gas), 28_782.0, 1.0), "{}", flow(&w, ussr, Commodity::Gas));
        // Every 1990 producer's HAVE equals its national figure in January
        // 1990: located shares sum to one and the unlocated keep the whole.
        let t = tables();
        for c in ALL.iter().filter(|c| **c != Commodity::Oil) {
            for (id, v) in &t.national[c.key()] {
                assert!(near(flow(&w, *id, *c), *v, v.abs() * 1e-9 + 1e-6), "{} {}: {} vs {}", id.code(), c.key(), flow(&w, *id, *c), v);
            }
            for (id, list) in &t.located[c.key()] {
                let sum: f64 = list.iter().map(|(_, s)| s).sum();
                assert!((sum - 1.0).abs() <= SHARE_SUM_TOLERANCE, "{} {}", id.code(), c.key());
                assert!(list.iter().all(|(_, s)| *s >= LOCATED_MIN_SHARE));
            }
        }
        // The France of the transcription: cobalt unlocated (New Caledonia
        // has no district), gold located to three districts incl. Guiana.
        let france = code("France");
        assert_eq!(flow(&w, france, Commodity::Cobalt), 800.0);
        assert!(near(flow(&w, france, Commodity::Gold), 4150.0, 1e-6));
        assert!(w.resource_have.presence[france.index()] & Commodity::Gold.bit() != 0);
        assert_eq!(flow(&w, ussr, Commodity::Uranium), 14_000.0);
    }

    /// HAVE follows the ground. Iraq annexing Kuwait gains Kuwait's 147.97
    /// bcf of gas (six located districts); Iran ceding IR-15, IR-13, IR-30
    /// and IR-25 hands Iraq all of Iran's bauxite, 61% of its copper and 54%
    /// of its iron; the USSR dissolving leaves Russia 0.808 of its iron,
    /// Ukraine 0.115, Kazakhstan 0.058 — successor splits fall out of
    /// `dissolve_to` with no new code.
    #[test]
    fn ownership_moves_have() {
        let (iraq, kuwait, iran, ussr) = (code("Iraq"), code("Kuwait"), code("Iran"), code("USSR"));
        let near = |a: f64, b: f64, tol: f64| (a - b).abs() <= tol;

        let mut w = built(world_1990(GameRules::default()));
        let gas_before = flow(&w, iraq, Commodity::Gas);
        let epoch = w.districts_epoch;
        assert_eq!(crate::districts::annex_all(&mut w, iraq, kuwait), 6);
        assert_eq!(w.districts_epoch, epoch.wrapping_add(1));
        tick(&mut w);
        assert!(near(flow(&w, iraq, Commodity::Gas) - gas_before, 147.97, 1e-9), "{}", flow(&w, iraq, Commodity::Gas) - gas_before);
        assert_eq!(flow(&w, kuwait, Commodity::Gas), 0.0);
        // Kuwait's oil is its ledger and did not move: annexation of ground
        // is not a transfer of `oil_mbd`, which the settlement handles.
        assert_eq!(flow(&w, kuwait, Commodity::Oil), w.nation(kuwait).oil_mbd * 1000.0);

        let mut w = built(world_1990(GameRules::default()));
        let (bx, cu, fe) = (
            flow(&w, iran, Commodity::Bauxite),
            flow(&w, iran, Commodity::Copper),
            flow(&w, iran, Commodity::Iron),
        );
        for d in ["IR-15", "IR-13", "IR-30", "IR-25"] {
            assert_eq!(w.districts.get(d), Some(&iran));
            w.districts.insert(d.to_string(), iraq);
        }
        w.districts_epoch = w.districts_epoch.wrapping_add(1);
        tick(&mut w);
        assert!(near(flow(&w, iraq, Commodity::Bauxite), bx, 1e-6));
        assert!(near(flow(&w, iraq, Commodity::Copper) / cu, 0.6111, 5e-4), "{}", flow(&w, iraq, Commodity::Copper) / cu);
        assert!(near(flow(&w, iraq, Commodity::Iron) / fe, 0.5385, 5e-4), "{}", flow(&w, iraq, Commodity::Iron) / fe);
        assert!(near(flow(&w, iran, Commodity::Bauxite), 0.0, 1e-9));
        assert!(near(flow(&w, iran, Commodity::Copper) + flow(&w, iraq, Commodity::Copper), cu, 1e-6));

        let mut w = built(world_1990(GameRules::default()));
        let fe = flow(&w, ussr, Commodity::Iron);
        let heirs: Vec<NationId> = crate::districts::SUCCESSOR_PARENTS
            .iter()
            .filter(|(_, p)| *p == ussr)
            .map(|(h, _)| *h)
            .collect();
        crate::districts::dissolve_to(&mut w, ussr, &heirs);
        tick(&mut w);
        let share = |h: &str| flow(&w, code(h), Commodity::Iron) / fe;
        assert!(near(share("Russia"), 0.808, 1e-3), "{}", share("Russia"));
        assert!(near(share("Ukraine"), 0.115, 1e-3), "{}", share("Ukraine"));
        assert!(near(share("Kazakhstan"), 0.058, 1e-3), "{}", share("Kazakhstan"));
        assert!(near(share("Azerbaijan"), 0.019, 1e-3), "{}", share("Azerbaijan"));
        // The USSR still lives here (nothing killed it), so its unlocated
        // uranium stays; its located iron has all gone to the heirs.
        assert_eq!(flow(&w, ussr, Commodity::Iron), 0.0);
        assert_eq!(flow(&w, ussr, Commodity::Uranium), 14_000.0);
    }

    /// The pile: twelve shortfall evaluations at zero available take cover
    /// from 12 to 0 — the twelfth write lands on 0 and binds (a gate binds
    /// when cover ≤ 0 after this month's write), and so does the thirteenth;
    /// then twelve surplus evaluations, each worth `min(1, surplus/need) = 1`,
    /// refill it to 12, the row folds away, and the save loses the key.
    #[test]
    fn cover_counts_down_and_folds_back() {
        let mut w = built(world_1990(GameRules::default()));
        let iraq = code("Iraq");
        let c = Commodity::Copper;
        assert_eq!(cover(&w, iraq, c), BUFFER_MONTHS);
        assert!(crate::save(&w).find("\"resources\"").is_none());
        for i in 1..=11 {
            let cv = write_cover(&mut w, iraq, c, 0.0, 100.0);
            assert!((cv - (12.0 - i as f64)).abs() < 1e-12, "{i}: {cv}");
            assert!(cv > 0.0);
        }
        assert_eq!(w.resources.cover.len(), 1);
        assert!(crate::save(&w).contains("\"resources\""));
        let cv = write_cover(&mut w, iraq, c, 0.0, 100.0);
        assert_eq!(cv, 0.0, "the twelfth write lands on zero and the gate binds");
        let cv = write_cover(&mut w, iraq, c, 0.0, 100.0);
        assert_eq!(cv, 0.0, "the thirteenth stays bound; the pile never goes negative");
        for i in 1..=12 {
            let cv = write_cover(&mut w, iraq, c, 200.0, 100.0);
            assert!((cv - i as f64).abs() < 1e-12, "{i}: {cv}");
        }
        assert_eq!(cover(&w, iraq, c), BUFFER_MONTHS);
        assert!(w.resources.cover.is_empty() && w.resources.is_empty());
        assert!(crate::save(&w).find("\"resources\"").is_none());
        // A surplus month with no row writes nothing: the pile is full and
        // stays unmaterialised.
        assert_eq!(write_cover(&mut w, iraq, c, 200.0, 100.0), BUFFER_MONTHS);
        assert!(w.resources.is_empty());
        // Exactly enough is neither shortfall nor surplus.
        assert_eq!(write_cover(&mut w, iraq, c, 100.0, 100.0), BUFFER_MONTHS);
        assert!(w.resources.is_empty());
    }

    /// Ruling 2, in the one place a shortage can hurt. Every living nation
    /// sanctions France — every copper producer among them — and France, which
    /// knows laser-guided munitions in 1990, prefers the Paveway line. France
    /// mines 300 t of copper a year against a draw near 76 t a month, so
    /// under section 1.3's arithmetic the pile falls by `1 − 25/76 ≈ 0.67` a
    /// month and binds in the eighteenth evaluation (the spec's sketch said
    /// thirteen, which assumed nothing of its own; the arithmetic is the
    /// model). The month it binds the headline reads exactly
    /// `France: GBU-24 Paveway III line delayed - needs copper; every producer
    /// refuses.`; the order book gains nothing, the money banks under the
    /// 24-line cap, and the gate touched no political capital. With no
    /// preference the staff order the best kit whose inputs are held — the
    /// light infantry formation — and the same sentence prints.
    #[test]
    fn a_closed_market_delays_the_line_and_says_so() {
        let france = code("France");
        let paveway = crate::arsenal::index_of("paveway").unwrap();
        let inf_light = crate::arsenal::index_of("inf_light").unwrap();
        let expected = "France: GBU-24 Paveway III line delayed - needs copper; every producer refuses.";

        let close = |w: &mut WorldState| {
            let ids: Vec<NationId> = w.nations.iter().filter(|n| n.alive && n.id != france).map(|n| n.id).collect();
            for h in ids {
                if !w.is_sanctioning(h, france) {
                    w.sanctions.push((h, france));
                }
            }
        };

        // The preference stalls.
        let mut w = world_1990(GameRules::default());
        assert!(w.nation(france).tech.knows("aero_precision_munitions"));
        w.nation_mut(france).arsenal.preference = Some("paveway".into());
        assert_eq!(crate::arsenal::pick(w.nation(france)), Some(paveway));
        let mut first = None;
        let mut banked_at_stall = 0.0;
        for m in 1..=24 {
            close(&mut w);
            let heads = crate::tick_month(&mut w, &[]);
            let printed = heads.iter().filter(|h| h.as_str() == expected).count();
            assert!(printed <= 1, "{heads:?}");
            // A fresh order carries its kit's full lead time; a month that
            // ordered nothing leaves no such row.
            let fresh = |a: &crate::arsenal::Arsenal| {
                a.orders.iter().any(|o| o.due == DECK[o.kit as usize].lead_months)
            };
            if printed == 1 && first.is_none() {
                first = Some(m);
                // The order book gained nothing this month; the money banked.
                let a = &w.nation(france).arsenal;
                assert!(!fresh(a), "a stalled line placed an order");
                assert!(a.banked > 0.0, "the stalled line's money did not bank");
                banked_at_stall = a.banked;
            } else if let Some(f) = first {
                if m == f + 1 {
                    let a = &w.nation(france).arsenal;
                    assert!(!fresh(a), "a stalled line placed an order the month after");
                    assert!(a.banked > banked_at_stall, "banked money did not grow while the line stayed stalled");
                    assert!(a.banked <= crate::arsenal::budget_of(w.nation(france)) * 24.0 + 1e-9, "banked money escaped the 24-line cap");
                }
            }
            for h in &heads {
                assert!(!h.contains("line delayed") || h == expected, "{h}");
            }
        }
        let first = first.expect("the Paveway line never stalled in 24 months");
        // The arithmetic's own prediction, from the ledger as January read it.
        let mut p = world_1990(GameRules::default());
        close(&mut p);
        let p = built(p);
        let need = kit_need(paveway, crate::arsenal::line_of(p.nation(france)))[Commodity::Copper.idx()];
        let own = flow(&p, france, Commodity::Copper) / 12.0;
        assert!(own > 0.0 && own < need, "France should be short of copper: own {own} need {need}");
        let per_month = 1.0 - own / need;
        let predicted = (BUFFER_MONTHS / per_month).ceil() as usize;
        assert!((first as i64 - predicted as i64).abs() <= 1, "stalled in month {first}, the arithmetic predicts {predicted}");
        assert!(first >= 12, "a stall can never bind before the pile is spent");
        assert_eq!(cover(&w, france, Commodity::Copper), 0.0);

        // The gate itself charges nothing: run it by hand on a bound pile,
        // with the doors closed again (politics may have reopened one in the
        // last tick's statecraft, which runs after the arsenal).
        close(&mut w);
        let pc = w.nation(france).political_capital;
        let line = crate::arsenal::line_of(w.nation(france));
        let (choice, stall) = gate(&mut w, france, paveway, line);
        assert_eq!(choice, None);
        assert_eq!(stall.as_ref().map(|s| s.headline()).as_deref(), Some(expected));
        assert_eq!(w.nation(france).political_capital, pc);

        // With no preference the staff buy the best kit whose inputs are held.
        let mut w = world_1990(GameRules::default());
        assert!(w.nation(france).arsenal.preference.is_none());
        let mut seen = false;
        for _ in 1..=24 {
            close(&mut w);
            let heads = crate::tick_month(&mut w, &[]);
            if heads.iter().any(|h| h == expected) {
                seen = true;
                let last = w.nation(france).arsenal.orders.last().expect("the staff ordered something");
                assert_eq!(last.kit, inf_light, "the fallback is the best kit whose inputs are held");
                assert_eq!(last.due, DECK[inf_light as usize].lead_months, "the fallback order is this month's");
                break;
            }
        }
        assert!(seen, "the AI's delayed line was not headlined");
        close(&mut w);
        let line = crate::arsenal::line_of(w.nation(france));
        assert_eq!(crate::arsenal::ranked(w.nation(france)).first(), Some(&paveway));
        let (choice, stall) = gate(&mut w, france, paveway, line);
        assert_eq!(choice, Some(inf_light));
        assert_eq!(stall.map(|s| s.headline()).as_deref(), Some(expected));
    }

    /// The coefficients are an order of magnitude, and the check the spec
    /// names holds: the whole United States line ordered as naval kit draws
    /// under 2% of the ore the United States mines; the legacy tier draws
    /// nothing at any line.
    #[test]
    fn kit_need_magnitudes() {
        let w = built(world_1990(GameRules::default()));
        let usa = code("USA");
        let line = crate::arsenal::line_of(w.nation(usa));
        assert!(line > 4.0 && line < 7.0, "US line {line} $bn/month");
        let naval = crate::arsenal::index_of("la_ssn").unwrap();
        let need = kit_need(naval, line);
        let ore_month = flow(&w, usa, Commodity::Iron) / 12.0;
        let share = need[Commodity::Iron.idx()] / ore_month;
        assert!(share > 0.005 && share < 0.02, "US naval line draws {:.2}% of US ore", share * 100.0);
        assert!(need[Commodity::Coal.idx()] > 0.0 && need[Commodity::Bauxite.idx()] == 0.0);
        let air = crate::arsenal::index_of("f15e").unwrap();
        assert!(kit_need(air, line)[Commodity::Bauxite.idx()] > 0.0);
        let missile = crate::arsenal::index_of("tomahawk").unwrap();
        assert!(kit_need(missile, line)[Commodity::Copper.idx()] > 0.0);
        let infantry = crate::arsenal::index_of("c4isr").unwrap();
        assert!(kit_need(infantry, line).iter().all(|q| *q == 0.0));
        for (i, def) in DECK.iter().enumerate() {
            if def.tech.is_none() {
                assert!(kit_need(i as u16, 100.0).iter().all(|q| *q == 0.0), "{} draws", def.id);
            }
        }
        assert!(kit_need(naval, 0.0).iter().all(|q| *q == 0.0));
        assert!(kit_need(u16::MAX, 1.0).iter().all(|q| *q == 0.0));
    }

    /// The accessors answer the None arm before the first tick and the real
    /// ledger after it; the market reads sanctions, war and the floor.
    #[test]
    fn supply_is_pure_and_reads_the_closed_doors() {
        let mut w = world_1990(GameRules::default());
        w.reindex();
        assert!(!w.resource_have.built);
        assert_eq!(flow(&w, code("USSR"), Commodity::Iron), 0.0);
        let s = supply(&w, code("Japan"), Commodity::Iron, 1.0);
        assert_eq!(s.available, 0.0);
        assert!(!s.any_producer);
        assert!(matches!(have(&w), Cow::Owned(_)));
        tick(&mut w);
        assert!(matches!(have(&w), Cow::Borrowed(_)));
        // Japan mines 34,000 t of iron ore a year — 2,833 t a month — so a
        // draw of 10,000 t is two-thirds market, and the market fills it.
        let japan = code("Japan");
        let need = 10_000.0;
        let s = supply(&w, japan, Commodity::Iron, need);
        assert!(s.any_producer && s.holder.is_some());
        assert!(s.own > 0.0 && s.own < need, "{}", s.own);
        assert_eq!(s.available, need);
        assert_eq!(s.market, need - s.own);
        // Own flow alone covers a smaller draw and the market sells nothing.
        let s0 = supply(&w, japan, Commodity::Iron, 1000.0);
        assert_eq!(s0.market, 0.0);
        assert_eq!(s0.available, s0.own);
        let holder = s.holder.unwrap();
        assert_eq!(open_holder(&w, japan, Commodity::Iron), Some(holder));
        assert!(producers(&w, Commodity::Iron).contains(&holder));
        // Sanctions in either direction close a door; the next holder opens.
        w.sanctions.push((japan, holder));
        let s2 = supply(&w, japan, Commodity::Iron, need);
        assert_ne!(s2.holder, Some(holder));
        assert!(s2.holder > Some(holder));
        // Relations below the floor close it too.
        let mut w2 = w.clone();
        let ps = producers(&w2, Commodity::Iron);
        for p in &ps {
            w2.set_relation(japan, *p, RELATION_FLOOR - 1.0);
        }
        w2.sanctions.clear();
        let s3 = supply(&w2, japan, Commodity::Iron, need);
        assert!(s3.any_producer && s3.holder.is_none());
        assert_eq!(s3.available, s3.own);
        // Same state, same answer, no RNG: twice over.
        assert_eq!(supply(&w2, japan, Commodity::Iron, need), s3);
        assert_eq!(month_abs(&w), 0);
    }
}
