#!/usr/bin/env python3
"""Build the web PNG allowlist from reviewed exact-person art, never approve art."""
import argparse
import json
from pathlib import Path
import person_art_pipeline as pipeline
import fictional_art_pipeline as fiction

ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / 'spheres-web/src/person_avatar_assets.rs'

def render(manifest, registry, root=ROOT, fictional_manifest=None, fictional_catalog=None):
    checked = pipeline.validate_manifest(manifest, root, pipeline.people_from_registry(registry))
    if not checked['valid']:
        raise ValueError('\n'.join(checked['errors']))
    if fictional_manifest is None:
        fictional_manifest = pipeline.read_json(root / 'spheres-web/data/fictional_portraits.json')
    if fictional_catalog is None:
        fictional_catalog = pipeline.read_json(root / 'spheres-web/data/future_candidates_2035.json')
    future = fiction.validate(fictional_manifest, fictional_catalog, root, manifest)
    if not future['valid']:
        raise ValueError('\n'.join(future['errors']))
    files = set()
    for records in checked['ready'].values():
        for art in records:
            if (art.get('style'), art.get('method'), art.get('status')) != ('cartoon', 'generated', 'illustrated-likeness'):
                raise ValueError('Active person art must be a generated cartoon illustrated likeness')
            path = pipeline.safe_path(root, art['asset'], ('spheres-web/ui/person-portraits',))
            relative = path.relative_to(root / 'spheres-web/ui/person-portraits').as_posix()
            if path.suffix != '.png' or '/' in relative:
                raise ValueError('Active avatars must be versioned top-level PNG files')
            files.add(relative)
    for records in future['ready'].values():
        for portrait in records:
            path = pipeline.safe_path(root, portrait['asset'], ('spheres-web/ui/person-portraits',))
            files.add(path.relative_to(root / 'spheres-web/ui/person-portraits').as_posix())
    lines = ['// Generated by tools/avatars/build_person_avatar_assets.py; do not edit.',
             '// Reviewed historical likenesses and separately validated fictional designs only.',
             "fn cartoon_asset(name: &str) -> Option<&'static [u8]> {", '    match name {']
    for name in sorted(files):
        lines.append(f'        {json.dumps(name)} => Some(include_bytes!("../ui/person-portraits/{name}")),')
    lines += ['        _ => None,', '    }', '}', '']
    return '\n'.join(lines)

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    text = render(pipeline.read_json(pipeline.DEFAULT_MANIFEST), pipeline.read_json(pipeline.DEFAULT_REGISTRY))
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding='utf-8').replace('\r\n', '\n') != text:
            raise SystemExit('Avatar allowlist differs. Run build_person_avatar_assets.py after reviewing manifest changes.')
        print('Reviewed avatar allowlist matches the manifest.')
    else:
        OUTPUT.write_text(text, encoding='utf-8', newline='\n')
        print('Wrote', OUTPUT)

if __name__ == '__main__':
    main()
