// Exercise the shipped people desk against authoritative server snapshots.
const {test}=require('node:test'),assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const root=path.resolve(__dirname,'../..');
const source=fs.readFileSync(path.join(root,'spheres-web/ui/population-ui.js'),'utf8');
const page=fs.readFileSync(path.join(root,'spheres-web/ui/index.html'),'utf8');
const plain=x=>JSON.parse(JSON.stringify(x));
function snapshot(extra={}){return {session_id:'one',nation:'USA',name:'United States',enabled:true,population_m:250,children_m:50,working_age_m:160,retirees_m:40,labor_force_m:100,employed_m:91,unemployed_m:9,students_m:38,outside_workforce_m:59,military_m:1,unemployment_rate:.09,participation_rate:.625,employment_rate:.56875,underemployment_rate:.03,vacancies_m:4,skilled_vacancies_m:1.25,living_standards:103.2,social_mobility:.025,research_multiplier:1.04,education_budget_bn:150,school_coverage:.92,training_capacity_m:1.2,annual_graduates_m:.6,policy:'balanced',policies:[['balanced','Balanced opportunity'],['trade_schools','Trade schools'],['universities','University drive'],['back_to_work','Back to work']].map(([policy,name])=>({policy,name,description:`${name} outcomes from the server.`,political_cost:7,cooldown_days:0,available:policy!=='balanced',reason:null,selected:policy==='balanced'})),education:[{key:'basic',name:'Basic education',people_m:80,share:.5}],classes:['Agricultural households','Wage workers','Skilled workers','Professionals & managers','Small business owners','Capital owners'].map((name,i)=>({key:'class'+i,name,people_m:250/6,share:1/6,income_index:85,living_standards:103,wealth_index:65,discontent:.08})),sectors:[{key:'manufacturing',name:'Manufacturing',jobs_m:20,employed_m:19,vacancies_m:1,staffing:.95,wage_index:105}],provinces:[{district:'US-CA',name:'California',population_m:30,employed_m:10,unemployed_m:2,vacancies_m:1,unemployment_rate:1/6,living_standards:104,students_m:4}],notes:['Game estimates; measured source labels are supplied by the simulation.'],...extra};}
function fixture(){const calls=[],requests=[];let open=true;const c=vm.createContext({console,window:{},document:{activeElement:null,querySelector:()=>null},S:{session_id:'one',player:'USA'},CAB:{tab:'people',busy:false},SESSION:{busy:false},COMP:{busy:false},COMMAND_CHANNEL:{busy:false,pending:null},advancing:false,pendingAdvance:null,cabinetIsOpen:()=>open,api:async(url,body)=>{requests.push([url,plain(body??null)]);return body?{session_id:'one',player:'USA',errors:[]}:snapshot();},adopt:async state=>{calls.push(plain(state));c.S=state;},renderLeft:()=>{},me:()=>({}),selectCabinetTab:()=>{},toggleGameDrawer:()=>{}});vm.runInContext(source,c);c.people=vm.runInContext('PEOPLE',c);Object.assign(c.people,{session:'one',nation:'USA',state:c.S,data:snapshot(),stale:false});Object.assign(c,{calls,requests,close:()=>{open=false;}});return c;}

test('People displays authoritative values with correct million and rate units',()=>{const c=fixture(),before=plain(c.people.data),html=c.peopleContentHtml();for(const text of ['A good job.','People at work','91.0m','9.0% unemployment','103','1.3m','92.0%','Six ways to make a living','Trade schools','7 PC','95.0% staffed','62.5%','56.9%','3.0%','California','50.0m','40.0m','Income &amp; wealth'])assert(html.includes(text),text);assert.equal((html.match(/data-people-class=/g)||[]).length,6);assert.equal((html.match(/data-people-policy-card=/g)||[]).length,4);assert.deepEqual(plain(c.people.data),before);assert.equal(c.requests.length,0);assert.equal(c.peopleCount(.000042), '42');assert.equal(c.peopleCount(.0125), '12.5k');assert.equal(c.peoplePercent(null),'—');});
test('server labels, policy descriptions, blockers and source notes are escaped',()=>{const c=fixture();c.people.data.name='<script>x</script>';c.people.data.classes[0].name='<img src=x onerror=evil()>';c.people.data.policies[1].description='<b>effect</b>';c.people.data.policies[1].reason='Need "capital" & time';c.people.data.policies[1].available=false;c.people.data.notes=['<iframe>'];const html=c.peopleContentHtml();assert(!html.includes('<script>'));assert(!html.includes('<img'));assert(!html.includes('<iframe>'));assert(html.includes('&lt;b&gt;effect&lt;/b&gt;'));assert(html.includes('Need &quot;capital&quot; &amp; time'));assert.match(html,/data-people-policy="trade_schools" disabled/);});
test('legacy saves offer an explicit upgrade without inventing population readings',()=>{const c=fixture();c.people.data=snapshot({enabled:false,reason:'Earlier rules in this save.'});const html=c.peopleContentHtml();assert(html.includes('Earlier rules in this save.'));assert(html.includes('Enable people &amp; jobs'));assert(!html.includes('data-people-class='));assert.equal(c.calls.length,0);assert.equal(c.requests.length,0);});
test('education progress uses served course completion and funded days without predicting graduates',()=>{const c=fixture();c.people.data.courses=[{name:'Trade qualifications',people_m:.043,progress:.253,days_remaining:257}];const html=c.peopleEducationHtml(c.people.data);assert(html.includes('43.0k enrolled · 25.3% complete'));assert(html.includes('Next graduates in 257 funded days'));assert(html.includes('recent completions / year'));assert(!html.includes('0.6m expected'));assert.equal(c.requests.length,0);});
test('secondary catch-up appears beside all other courses without creating a fifth national focus',()=>{
  const c=fixture();
  c.people.data.courses=['Foundation courses','Secondary catch-up','Trade qualifications','University degrees'].map(name=>({name,people_m:.021,progress:0,days_remaining:730}));
  const description='Foundation and secondary courses help adults qualify for their next opportunity.';
  c.people.data.policies.find(row=>row.policy==='back_to_work').description=description;
  const before=plain(c.people.data),html=c.peopleContentHtml();
  for(const course of c.people.data.courses)assert(html.includes(`<h3>${course.name}</h3>`));
  assert.equal((html.match(/Next graduates in 730 funded days/g)||[]).length,4);
  assert.equal((html.match(/data-people-policy-card=/g)||[]).length,4);
  assert(html.includes(description));
  assert.deepEqual(plain(c.people.data),before);
  assert.equal(c.requests.length,0);
});
test('policy uses the shared command channel and adopts its acknowledged state',async()=>{const c=fixture();assert.equal(await c.peopleSubmit({kind:'set_population_policy',policy:'trade_schools'}),true);assert.deepEqual(c.requests,[['/api/command',{commands:[{kind:'set_population_policy',policy:'trade_schools'}]}]]);assert.equal(c.calls.length,1);assert(c.people.message.includes('Trade schools is your national focus'));assert.equal(c.people.busy,false);});
test('stale, unavailable, selected and pending orders never submit',async()=>{for(const reason of ['stale','unavailable','selected','pending','other-state','unknown']){const c=fixture();if(reason==='stale')c.people.stale=true;if(reason==='unavailable')c.people.data.policies[1].available=false;if(reason==='pending')c.COMMAND_CHANNEL.pending={};if(reason==='other-state')c.people.state={...c.S};assert.equal(await c.peopleSubmit({kind:'set_population_policy',policy:reason==='selected'?'balanced':reason==='unknown'?'free_degrees':'trade_schools'}),false,reason);assert.equal(c.requests.length,0,reason);}});
test('refused orders surface their real reason and do not claim success',async()=>{const c=fixture();c.api=async()=>({errors:['Wait 179 days before choosing another focus.']});assert.equal(await c.peopleSubmit({kind:'set_population_policy',policy:'trade_schools'}),false);assert(c.people.error.includes('179 days'));assert.equal(c.calls.length,0);assert.equal(c.people.message,'');assert.equal(c.people.stale,true);});
test('reads bind the campaign and reject mismatched or outdated snapshots',async()=>{const c=fixture();c.people.stale=true;assert.equal(await c.peopleFetch(),true);assert.equal(c.requests[0][0],'/api/population?session_id=one');c.api=async()=>snapshot({session_id:'other'});assert.equal(await c.peopleFetch(true),false);assert(c.people.error.includes('did not match'));let done;c.api=()=>new Promise(resolve=>done=resolve);const request=c.peopleFetch(true);c.S={session_id:'two',player:'France'};c.close();c.peopleOnStateChanged();done(snapshot());assert.equal(await request,false);assert.notEqual(c.people.data?.nation,'USA');});
test('closing the room cancels adoption of an in-flight reading',async()=>{const c=fixture();let done;c.api=()=>new Promise(resolve=>done=resolve);c.people.stale=true;const request=c.peopleFetch();c.close();c.peopleClose();done(snapshot({living_standards:900}));assert.equal(await request,false);assert.notEqual(c.people.data.living_standards,900);});
test('Cabinet has a discoverable People entry and keyboard tab destination',()=>{assert(page.includes('data-cab-tab="people"'));assert(page.includes('data-cab-go="people"'));assert(page.includes('id="cabinet-people"'));assert(page.includes('"construction", "industry", "companies", "policy", "people"'));assert(page.includes('peopleOnStateChanged()'));});
