// Exercise the shipped company directory, identity renderer and command lifecycle.
const {test}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const base=path.resolve(__dirname,'../..');
const source=fs.readFileSync(path.join(base,'spheres-web/ui/companies-ui.js'),'utf8');
const plain=value=>JSON.parse(JSON.stringify(value));
function firm(extra={}){return {id:7,nation:'USA',name:'Continental Works',sector:'construction',specialty:'Heavy infrastructure',description:'Founded around an infrastructure expansion.',strength:'Delivers funded construction work faster.',weakness:'Premium fees and limited contract capacity.',logo:{seed:'1827465831023',mark:7,palette:0,initials:'CW'},capacity:2,used_capacity:0,work_bonus:.15,input_saving:.03,fee_rate:.02,experience:120,level:'Established',home_name:'California',founded_label:'1990',assignments:[],...extra};}
function reading(extra={}){return {session_id:'one',nation:'USA',name:'United States',enabled:true,companies:[firm()],targets:[{target:{kind:'construction',project:3},label:'California power grid',sector:'construction',current_company_id:null}],growth:[{sector:'construction',qualifying_months:6,required_months:12}],...extra};}
function fixture(){const requests=[],c=vm.createContext({console,window:{},document:{querySelector:()=>null,activeElement:null},S:{session_id:'one',player:'USA'},CAB:{tab:'companies',busy:false},COMMAND_CHANNEL:{busy:false,pending:null},SESSION:{busy:false},PROD:{busy:false},COMP:{busy:false},advancing:false,pendingAdvance:null,cabinetIsOpen:()=>true,openCompaniesCabinet(){c.CAB.tab='companies';},api:async(...args)=>{requests.push(plain(args));return args[0].startsWith('/api/companies')?reading():{session_id:'one',player:'USA'};},adopt:async value=>{c.S=value;}});vm.runInContext(source,c);c.desk=vm.runInContext('CDESK',c);Object.assign(c.desk,{open:true,session:'one',nation:'USA'});c.requests=requests;return c;}
function loaded(c,data=reading()){Object.assign(c.desk,{data,state:c.S,stale:false,loading:false,error:''});return data;}

test('company directory displays server roster, strengths, costs, origins and growth',()=>{const c=fixture(),data=loaded(c),before=plain(data),html=c.companiesContentHtml();for(const expected of ['Continental Works','Heavy infrastructure','Premium fees','15%','3%','2%','2 / 2 slots free','120 XP','California','6 / 12 growth months','Company story &amp; experience'])assert(html.includes(expected),expected);assert.deepEqual(plain(data),before);assert.equal(c.requests.length,0);assert.doesNotMatch(html,/GDP bonus|Guaranteed growth/);});
test('logo geometry is persistent and distinct across companies with the same palette, mark and initials',()=>{const c=fixture(),marks=new Set();for(let i=0;i<800;i++){const company=firm({id:i,name:`Continental Works ${i}`}),logo=c.companyLogo(company);assert.equal(logo,c.companyLogo(plain(company)));const geometry=[...logo.matchAll(/<path d="([^"]+)"/g)].map(m=>m[1]).join('|');marks.add(geometry);assert.match(logo,/role="img"/);assert.match(logo,/company logo/);}assert.equal(marks.size,800,'Identity changes actual vector paths, not only color or text');});
test('all user-visible company text is escaped in cards, stories and logo labels',()=>{const c=fixture();loaded(c);const html=c.companyCardHtml(firm({name:'<script>alert(1)</script>',specialty:'" onmouseover="bad',description:'<img src=x onerror=bad>',logo:{seed:1,mark:2,palette:1,initials:'<x>'}}));assert.doesNotMatch(html,/<script>|<img src=x|<x>/);assert.match(html,/&lt;script&gt;/);assert.match(html,/&quot; onmouseover=&quot;bad/);});
test('search combines accent-insensitive terms and sector/capacity filters',()=>{const c=fixture();loaded(c,reading({companies:[firm({home_name:'São Paulo'}),firm({id:8,name:'Kalahari Freight',sector:'logistics',capacity:1,used_capacity:1})]}));c.desk.query='SAO continental';assert.equal(c.companyRows().filter(c.companyMatches).length,1);c.desk.query='';c.desk.onlyAvailable=true;assert.equal(c.companyRows().filter(c.companyMatches).length,1);c.desk.onlyAvailable=false;c.desk.sector='logistics';assert.equal(c.companyRows().filter(c.companyMatches)[0].name,'Kalahari Freight');c.desk.query='does not exist';assert.match(c.companiesContentHtml(),/No companies match your search/);});
test('eligible targets are server supplied, sanitized and never cross sectors',()=>{const c=fixture();loaded(c,reading({targets:[{target:{kind:'construction',project:3,ignored:'extra'},label:'Grid',sector:'construction'},{target:{kind:'facility',district:'BW-CE',sector:'mining'},label:'Mine',sector:'mining'},{target:{kind:'unknown',project:9},label:'Unknown',sector:'construction'}]}));assert.equal(c.companyTargets(firm()).length,1);assert.deepEqual(plain(c.companyTarget({kind:'construction',project:3,ignored:'extra'})),{kind:'construction',project:3});assert.deepEqual(plain(c.companyTarget({kind:'custom_equipment',project:14})),{kind:'custom_equipment',project:14});for(const bad of [{kind:'construction',project:-1},{kind:'construction',project:'3'},{kind:'facility',district:'CA',sector:'defense'},{kind:'research',domain:7}])assert.equal(c.companyTarget(bad),null);});
test('contract assignment rejects occupied, incompatible, full and stale targets',async()=>{const c=fixture(),data=loaded(c);c.desk.selected.set('7',c.companyTargetKey(data.targets[0].target));data.targets[0].current_company_id=8;assert.equal(c.companiesAssign('7'),false);data.targets[0].current_company_id=null;data.companies[0].used_capacity=2;assert.equal(c.companiesAssign('7'),false);data.companies[0].used_capacity=0;c.desk.stale=true;assert.equal(c.companiesAssign('7'),false);c.desk.stale=false;c.S={session_id:'one',player:'USA'};assert.equal(c.companiesAssign('7',data,c.desk.state),false);assert.equal(c.requests.length,0);});
test('assignment dispatch uses selected server target and one command; repeated clicks are blocked',async()=>{const c=fixture(),data=loaded(c);c.desk.selected.set('7',c.companyTargetKey(data.targets[0].target));let finish;c.api=async(path,body)=>{c.requests.push([path,plain(body)]);return new Promise(resolve=>finish=resolve);};const sent=c.companiesAssign('7');assert.equal(c.desk.busy,true);assert.equal(c.companiesAssign('7'),false);assert.equal(c.requests.length,1);assert.deepEqual(c.requests[0],['/api/command',{commands:[{kind:'assign_company',company:7,target:{kind:'construction',project:3}}]}]);c.desk.open=false;finish({session_id:'one',player:'USA'});assert.equal(await sent,true);assert.equal(c.desk.busy,false);assert.match(c.desk.message,/Contract assigned/);});
test('uncertain commands keep the pending receipt and do not adopt or replay an order',async()=>{const c=fixture(),data=loaded(c);let adopted=false;c.adopt=async()=>{adopted=true;};c.api=async(path,body)=>{if(body){c.desk.open=false;return {command_pending:true};}return data;};assert.equal(await c.companiesIssue({kind:'enable_companies'}),false);assert.equal(adopted,false);assert.match(c.desk.message,/awaiting confirmation/);});
test('contract cancellation uses the recorded target, including custom equipment',async()=>{const c=fixture();loaded(c,reading({companies:[firm({assignments:[{target:{kind:'custom_equipment',project:14},assigned_day:4,last_day:4,work_today:2,bonus_today:.2,fees_today_bn:.001}]})]}));c.api=async(path,body)=>{c.requests.push(plain(body));c.desk.open=false;return {session_id:'one',player:'USA'};};assert.equal(await c.companiesRelease('7',0),true);assert.deepEqual(c.requests[0],{commands:[{kind:'unassign_company',target:{kind:'custom_equipment',project:14}}]});});
test('contract receipts separate unknown work from recorded zero output and spending',()=>{const c=fixture();loaded(c);const pending=c.companyContractHtml(firm(),{target:{kind:'construction',project:3},assigned_day:4,last_day:-1,bonus_today:0,fees_today_bn:0},0);assert.match(pending,/after funded work is delivered/);assert.doesNotMatch(pending,/Latest work receipt|Contractor fees/);const receipt=c.companyContractHtml(firm(),{label:'Power grid',assigned_day:4,last_day:4,work_today:0,bonus_today:0,fees_today_bn:0},0);assert.match(receipt,/Latest work receipt/);assert.match(receipt,/No delivered work/);assert.match(receipt,/Contractor fees/);});
test('fetch ignores old responses after the campaign or request changes',async()=>{const c=fixture();let finish;c.api=async()=>new Promise(resolve=>finish=resolve);const request=c.companiesFetch();c.S={session_id:'two',player:'Botswana'};c.companiesResetCampaign();finish(reading());assert.equal(await request,false);assert.equal(c.desk.data,null);assert.equal(c.desk.session,'two');assert.equal(c.desk.selected.size,0);});
test('fetch rejects the wrong nation/session and allows explicit retry',async()=>{const c=fixture();c.api=async()=>reading({nation:'Botswana'});assert.equal(await c.companiesFetch(),false);assert.match(c.desk.error,/did not match/);assert.equal(c.desk.stale,true);c.api=async()=>reading();assert.equal(await c.companiesFetch(true),true);assert.equal(c.desk.error,'');assert.equal(c.companiesCurrent(),true);});
test('all external mutation channels make contracts unavailable',()=>{const c=fixture();loaded(c);assert.equal(c.companiesCurrent(),true);for(const [object,key,value] of [[c.COMMAND_CHANNEL,'pending',{}],[c.COMMAND_CHANNEL,'busy',true],[c.SESSION,'busy',true],[c.CAB,'busy',true],[c.PROD,'busy',true],[c.COMP,'busy',true],[c,'advancing',true],[c,'pendingAdvance',{}]]){const old=object[key];object[key]=value;assert.equal(c.companiesCurrent(),false,key);object[key]=old;}assert.equal(c.companiesCurrent(),true);});
test('legacy campaigns expose an explicit enable action and new campaigns do not',()=>{const c=fixture();loaded(c,reading({enabled:false,companies:[]}));assert.match(c.companiesContentHtml(),/data-company-enable/);loaded(c);assert.doesNotMatch(c.companiesContentHtml(),/data-company-enable/);});
test('experienced companies show effective bonuses and capacity, and negative savings are a visible cost',()=>{const c=fixture();loaded(c);const html=c.companyCardHtml(firm({capacity:2,effective_capacity:3,effective_work_bonus:.2,effective_input_saving:-.04,fee_basis:'Fees use modeled extraction operating cost.'}));for(const expected of ['3 / 3 slots free','20%','Extra inputs','4%','Fees use modeled extraction operating cost.'])assert(html.includes(expected),expected);assert.doesNotMatch(html,/2 \/ 2 slots free/);});
test('the real growth snapshot exposes progress without promising a company',()=>{const c=fixture();loaded(c,reading({growth:{months_observed:15,required_months:18,growing_months:13,cumulative_growth:.17,required_growth:.12,entrants:1,cooldown_months_remaining:8,eligible_sector:'construction'},news:[{message:'Kgale Engineering has opened after sustained expansion.'}]}));const html=c.companyGrowthHtml();for(const expected of ['15 / 18 months','17%','12% needed','8 months until another opportunity','may appear','Kgale Engineering has opened'])assert(html.includes(expected),expected);});
test('active contracts reuse the matching server label instead of an opaque project number',()=>{const c=fixture();loaded(c);assert.equal(c.companyTargetLabel({kind:'construction',project:3}),'California power grid');});
test('cabinet integration loads assets, includes keyboard tab navigation and invalidates state',()=>{const html=fs.readFileSync(path.join(base,'spheres-web/ui/index.html'),'utf8');for(const expected of ['/companies-ui.js','/companies.css','id="cab-tab-companies"','id="cabinet-companies"','"industry", "companies", "policy"','companiesOnStateChanged();','companiesClose();','companiesBind();'])assert(html.includes(expected),expected);});
