'use strict';
const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),zlib=require('node:zlib');
const lib=require('./worldwide-startup-lib.cjs'),copy=value=>JSON.parse(JSON.stringify(value));
function fixture(){const roster=Array.from({length:137},(_,i)=>({id:'Country'+i,name:'Country '+i})).sort((a,b)=>a.id.localeCompare(b.id)),nation=roster[0].id,initial=Date.UTC(1990,0,1)/86400000;
  const layout={width:370,scroll:370},view={map:{draws_before:0,draws_after:1,width:1440,height:900,visible:true,in_viewport:true,camera:{cx:1,cy:1,yaw:1,pitch:1,zoom:1},owned_districts:1,player:nation},government:{nation,hero:roster[0].name,officeholder:'Fixture person',layout},budget:{nation,ministries:[...lib.MINISTRIES],summary:'Fixture budget',kicker:roster[0].name,layout},guidance:{player:nation,cards:'Fixture advice',layout}};
  const c={nation,name:roster[0].name,passed:true,checks:[...lib.CHECKS],before:{year:1990,month:1,day:1,player:nation},after:{year:1990,month:1,day:8,player:nation},advances:Array.from({length:7},(_,i)=>({before:initial+i,after:initial+i+1,days:1,player:nation,errors:[]})),before_save:{campaign_sha256:'b'.repeat(64)},after_save:{campaign_sha256:'b'.repeat(64)},old_session:'old',new_session:'new',page_errors:[],views:{opening:copy(view),reloaded:copy(view)},requests:['/api/new',...Array(7).fill('/api/advance'),'/api/save','/api/load','/api/save'].map(route=>({path:route,payload:route==='/api/new'?{seed:17,nation:roster[0].name}:{days:1,commands:[]}})),screenshots:['opening','reloaded'].flatMap(phase=>['map','government','budget','guidance'].map(room=>({stage:phase+'-'+room,viewport:{width:phase==='opening'?1440:390,height:phase==='opening'?1000:844}})))};
  return {format:'spheres-worldwide-browser/v1',passed:true,seed:17,coverage:'pilot',pilot:true,attached_server:false,canonical_roster:{rows:copy(roster),git_blob:'c'.repeat(40)},roster,requested_ids:[nation],cases:[c],runtime:{expected_revision:'a'.repeat(40),build:{full_revision:'a'.repeat(40)},binary_sha256:'b'.repeat(64),binary_sha256_after:'b'.repeat(64)},cleanup:{browser_closed:true,server_stopped:true},immutable_inputs_unchanged:true};
}
test('complete synthetic pilot validates without awarding full coverage',()=>assert.deepEqual(lib.validate(fixture()),[]));
test('full run rejects subset, duplicate or omitted starter cells',()=>{for(const mutate of [r=>{r.coverage='all_starters';r.pilot=false;},r=>r.requested_ids.push(r.requested_ids[0]),r=>r.cases=[],r=>r.roster.pop(),r=>r.cases.push(copy(r.cases[0]))]){const r=fixture();mutate(r);assert(lib.validate(r).length);}});
test('failures, fake draws, missing rooms, source drift and unclosed process cannot pass',()=>{for(const mutate of [r=>r.cases[0].passed=false,r=>r.cases[0].checks.pop(),r=>r.cases[0].views.opening.map.draws_after=0,r=>r.cases[0].views.reloaded.budget.nation='Other',r=>r.cases[0].page_errors.push('boom'),r=>r.cleanup.server_stopped=false,r=>r.immutable_inputs_unchanged=false,r=>r.runtime.build.full_revision='c'.repeat(40),r=>r.cases[0].screenshots.pop()]){const r=fixture();mutate(r);assert(lib.validate(r).length);}});
test('seven actual one-day advances preserve pauses but reject skips and duplicate days',()=>{const good=fixture();good.cases[0].advances[1].interrupt='Leadership event';assert.deepEqual(lib.validate(good),[]);for(const mutate of [r=>r.cases[0].advances.pop(),r=>r.cases[0].advances[3].after++,r=>r.cases[0].advances[1].before--,r=>r.cases[0].advances[2].errors=['refused'],r=>r.cases[0].after.day=7]){const r=fixture();mutate(r);assert(lib.validate(r).length);}});
test('unexpected mutations fail while the native read-only budget preview is retained',()=>{const r=fixture();r.cases[0].requests.splice(1,0,{path:'/api/program-preview',payload:{}});assert.deepEqual(lib.validate(r),[]);r.cases[0].requests.push({path:'/api/command',payload:{}});assert(lib.validate(r).length);});
function native(timestamp,extra=''){return Buffer.from('{"format":"spheres-campaign","version":1,"world":{"format":"spheres-integrated-save","world":{"rng":18446744073709551615,"value":-0.0,"player":"Country0","year":1990,"month":1,"day":8}},"history":[],"log":[],"journey":{},"history_epoch":0,"saved_date":"8 Jan 1990","player":"Country 0"'+extra+',"saved_unix":'+timestamp+'}');}
test('archive equality preserves integer, float, history and key bytes except terminal timestamp',()=>{const a=lib.archive(native(1)),b=lib.archive(native(2));assert.equal(a.campaign_sha256,b.campaign_sha256);assert.notEqual(a.sha256,b.sha256);for(const change of [s=>s.replace('18446744073709551615','18446744073709551614'),s=>s.replace('-0.0','0.0'),s=>s.replace('"history":[]','"history":[1]'),s=>s.replace('"log":[]','"log":[2]')])assert.notEqual(a.campaign_sha256,lib.archive(Buffer.from(change(native(1).toString()))).campaign_sha256);assert.throws(()=>lib.archive(Buffer.from('{}')));});
test('exact ministry identities, layout, visible map, roster and ordinary seed are required',()=>{for(const mutate of [r=>r.cases[0].views.opening.budget.ministries.fill('health'),r=>r.cases[0].views.opening.government.layout.scroll=900,r=>r.cases[0].views.reloaded.guidance.layout.width=0,r=>r.cases[0].views.opening.map.visible=false,r=>r.cases[0].views.opening.map.in_viewport=false,r=>r.cases[0].requests[0].payload.seed=18,r=>r.roster[0].name='Unpinned',r=>r.cases[0].screenshots[0].viewport.height=10]){const r=fixture();mutate(r);assert(lib.validate(r).length);}});
function evidence(run){const root=fs.mkdtempSync(path.join(os.tmpdir(),'spheres-worldwide-evidence-'));try{const r=fixture(),c=r.cases[0],pin=(file,bytes)=>{fs.writeFileSync(path.join(root,file),bytes);return {path:file,bytes:bytes.length,sha256:lib.hash(bytes)};};r.harness={sources:lib.SOURCES.map((p,i)=>({...pin('source'+i,Buffer.from('synthetic '+p)),source_path:p}))};const nations=Buffer.from(r.roster.map(row=>`row("${row.id}", "${row.name}", &[], "Fixture", &[], &[], true, false, false)`).join('\n'));r.canonical_roster={...r.canonical_roster,...pin('nations.rs',nations),git_blob:require('node:crypto').createHash('sha1').update(Buffer.from('blob '+nations.length+'\0')).update(nations).digest('hex')};for(const key of ['before_save','after_save']){const raw=native(key==='before_save'?1:2),compressed=zlib.gzipSync(raw),file=key+'.gz';fs.writeFileSync(path.join(root,file),compressed);c[key]={...lib.archive(raw),path:file,gzip_bytes:compressed.length,gzip_sha256:lib.hash(compressed)};}c.screenshots=c.screenshots.map((shot,i)=>({...shot,...pin('shot'+i+'.jpg',Buffer.from('synthetic screenshot '+i))}));run(r,root,pin);}finally{assert(path.resolve(root).startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(root,{recursive:true});}}
test('retained verifier checks actual gzip/raw, frozen sources and every screenshot',()=>evidence((r,root)=>{assert.equal(lib.verifyEvidence(r,root).files_verified,16);fs.appendFileSync(path.join(root,'shot1.jpg'),'changed');assert.throws(()=>lib.verifyEvidence(r,root));}));
test('retained verifier rejects failed attempts and changed frozen dependency',()=>evidence((r,root)=>{r.passed=false;assert.throws(()=>lib.verifyEvidence(r,root));r.passed=true;r.error='preserved error';assert.throws(()=>lib.verifyEvidence(r,root));delete r.error;fs.appendFileSync(path.join(root,'source0'),'changed');assert.throws(()=>lib.verifyEvidence(r,root));}));
test('display name differs from ID; stale same-country archives cannot pass',()=>evidence((r,root)=>{assert.equal(r.cases[0].before_save.player,'Country 0');assert.equal(r.cases[0].before_save.world_player,'Country0');assert(lib.verifyEvidence(r,root).passed);for(const key of ['before_save','after_save']){const raw=Buffer.from(native(1).toString().replace('"day":8','"day":7')),compressed=zlib.gzipSync(raw),file=key+'.gz';fs.writeFileSync(path.join(root,file),compressed);r.cases[0][key]={...lib.archive(raw),path:file,gzip_bytes:compressed.length,gzip_sha256:lib.hash(compressed)};}assert.throws(()=>lib.verifyEvidence(r,root));}));
