const {test}=require('node:test'),assert=require('node:assert/strict');
const ui=require('../../spheres-web/ui/campaign-journey.js');
const fixture=()=>({summary:{nation_name:'France',date:'1 Jan 1990',title:'A new chapter',detail:'Model result',actions:[],horizon:'31 Dec 2035',alive:true,transitions:[]},metrics:[],history_note:'Recorded events only',legacy_aims:[],aims:{note:'No rewards',active:null,offers:[{aim:'prosperity',title:'Shared prosperity',description:'Grow output',unavailable:null}],history:[]}});
test('unavailable aims cannot present an enabled review',()=>{const d=fixture();d.aims.offers[0].unavailable='Requires daily simulation';assert.match(ui.goals(d),/data-journey-aim="prosperity" disabled/);});
test('finished aims retain the result while current metrics can be below target',()=>{const d=fixture();d.aims.active={aim:'prosperity',target:100,held_days:90,hold_days:90,completed_day:100};d.aims.evaluation={value:50,metric:'output',progress:0,blockers:['Reach 100']};const html=ui.goals(d);assert.match(html,/Achieved/);assert.match(html,/value="1"/);assert.doesNotMatch(html,/Reach 100/);assert.match(html,/retained even if conditions change/);});
test('active blockers and consecutive days are displayed, never converted to bonuses',()=>{const d=fixture();d.aims.active={aim:'prosperity',target:100,held_days:12,hold_days:90,completed_day:null};d.aims.evaluation={value:80,metric:'output',progress:.5,blockers:['Be at peace.']};const html=ui.goals(d);assert.match(html,/Be at peace/);assert.match(html,/12 \/ 90/);assert.match(html,/fixed target 100/);});
test('a lost country cannot choose another goal but keeps its record and military access',()=>{const d=fixture();d.summary.alive=false;d.legacy_aims=[{goal:{nation:'USSR',aim:'prosperity',held_days:2},outcome:'government ended'}];const html=ui.goals(d);assert.doesNotMatch(html,/data-journey-aim=/);assert.match(html,/USSR/);assert.match(html,/government ended/);});
test('archive output escapes saved event and identity text',()=>{const text='<img src=x onerror=alert(1)>';assert.doesNotMatch(ui.events({total:1,before:0,events:[{text,date:text,cat:'war'}]}),/<img/);const d=fixture();d.summary.nation_name=text;d.summary.actions=[{label:text}];assert.doesNotMatch(ui.overview(d),/<img/);});
test('old archive pages remain reachable with a server cursor',()=>{assert.match(ui.events({total:4001,before:3960,events:[]}),/journeyOlder/);assert.doesNotMatch(ui.events({total:0,before:0,events:[]}),/journeyOlder/);});
