'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{test}=require('node:test');
const ui=path.resolve(__dirname,'../../spheres-web/ui'),html=fs.readFileSync(path.join(ui,'index.html'),'utf8');
const sandbox=vm.createContext({window:{},document:{documentElement:{classList:{add(){},remove(){}}}}});
vm.runInContext(fs.readFileSync(path.join(ui,'globe3d.js'),'utf8'),sandbox);
const Globe=sandbox.window.Globe3D;
function globe(){return Object.assign(Object.create(Globe.prototype),{lastSize:{width:800,height:600},canvas:{getBoundingClientRect:()=>({left:20,top:40,width:400,height:300})},nationLabelHits:[{id:'Bahrain',box:[200,160,80,24]}],nationLabelOcclusions:[]});}
test('actual drawn label picking converts CSS coordinates to backing pixels',()=>{const g=globe();assert.equal(g.nationLabelAt(120,120),'Bahrain');assert.equal(g.nationLabelAt(140,126),'Bahrain');assert.equal(g.nationLabelAt(141,126),null);assert.equal(g.nationLabelAt(10,120),null);assert.equal(g.nationLabelAt(NaN,120),null);});
test('covered labels, missing targets and hidden canvases cannot be picked',()=>{const g=globe();g.nationLabelOcclusions=[[200,160,40,40]];assert.equal(g.nationLabelAt(120,120),null);g.nationLabelOcclusions=[];g.nationLabelHits=[];assert.equal(g.nationLabelAt(120,120),null);g.canvas.getBoundingClientRect=()=>({left:0,top:0,width:0,height:0});assert.equal(g.nationLabelAt(0,0),null);});
test('every rendered frame discards prior hit boxes and occlusion rectangles',()=>{const g=globe();Object.assign(g,{destroyed:false,frame:0,resize:()=>({width:800,height:600}),view:()=>({}),overlayContext:{clearRect(){}},options:{onOverlay(){assert.equal(g.nationLabelHits.length,0);assert.equal(g.nationLabelOcclusions.length,0);}},drawCities(){}});g.render();assert.equal(g.nationLabelAt(120,120),null);});
test('real label drawing creates targets only for visible unoccluded absent-geometry nations',()=>{const start=html.indexOf('  // ---- nation labels'),end=html.indexOf('  // Nations reserve space',start);assert(start>0&&end>start);const seen=[],hits=[],ctx={measureText:()=>({width:30}),strokeText(){},fillText:(text)=>seen.push(text)};const env=vm.createContext({ctx,r:1,view:{},m:null,ui:{mapDetails:{labels:true},cam:{k:1}},S:{nations:[{id:'Bahrain',name:'Bahrain',gdp:10},{id:'France',name:'France',gdp:8},{id:'Hidden',name:'Hidden',gdp:7},{id:'Overlap',name:'Overlap',gdp:6}]},hoverNation:null,selected:null,ZB2:4,mapSub:()=>'',smoothFade:()=>1,TERRITORY:{Bahrain:[],France:['FRA'],Hidden:[],Overlap:[]},WORLD:{countries:{FRA:'actual polygon'}},anchorOf:id=>({Bahrain:[50,50],France:[150,50],Hidden:[250,50],Overlap:[50,50]})[id],globe:{labelBoxes:[],nationLabelHits:hits,facingWorld:x=>x===250?0:1,projectWorld:(x,y)=>[x,y]}});vm.runInContext(html.slice(start,end),env);assert.deepEqual(seen,['Bahrain','France']);assert.deepEqual(hits.map(x=>x.id),['Bahrain']);env.ui.mapDetails.labels=false;hits.length=0;vm.runInContext('{'+html.slice(start,end)+'}',env);assert.deepEqual(hits,[]);});
function pick({label=null,code='FRA',district={id:'FRA-1'},route=null,work=null,city=null}={}){const actions=[],env=vm.createContext({GLOBE:{nationLabelAt:()=>label,worldAt:()=>[5,6],cityFrame:city?{}:null},CityDetail:{pick:()=>city},window:{CityDetail:!!city},GLCV:{getBoundingClientRect:()=>({left:0,top:0})},logisticsHitAt:()=>route,logisticsSelect:id=>actions.push(['route',id]),logisticsLaneId:()=>1,productionHitAt:()=>work,manufacturingSelect:id=>actions.push(['line',id]),productionSelect:id=>actions.push(['project',id]),selectProvince:id=>actions.push(['province',id]),selectMapCity:()=>actions.push(['city']),nationById:id=>id==='Bahrain'?{id}:null,openNation:id=>actions.push(['nation',id]),ui:{},renderMapCity(){},countryAt:()=>code,districtAt:()=>district,nationOfCode:()=> 'France',nationOfDistrict:()=> 'France'});const start=html.indexOf('function onMapPick(e) {'),end=html.indexOf('window.selectMapCity',start);vm.runInContext(html.slice(start,end)+'\nonMapPick({clientX:120,clientY:120});',env);return actions;}
test('ordinary map handler opens the label country without inventing territory',()=>{assert.deepEqual(pick({label:'Bahrain',code:null,district:null}),[['nation','Bahrain']]);assert.deepEqual(pick({label:'Bahrain',code:'SAU',district:null}),[['nation','Bahrain']]);assert.deepEqual(pick({label:'Dead',code:null,district:null}),[]);});
test('normal polygon/province picking and existing route/work/city priority remain intact',()=>{assert.deepEqual(pick(),[['province','FRA-1']]);assert.deepEqual(pick({district:null}),[['nation','France']]);assert.deepEqual(pick({code:null}),[]);assert.deepEqual(pick({label:'Bahrain',route:{}}),[['route',1]]);assert.deepEqual(pick({label:'Bahrain',work:{project:{id:2}}}),[['project',2]]);assert.deepEqual(pick({label:'Bahrain',city:{id:3}}),[['city']]);});
