const {test}=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const source=fs.readFileSync(path.resolve(__dirname,'../../spheres-web/ui/performance-ui.js'),'utf8');
function fixture(){let time=0,id=0;const frames=new Map(),listeners={};const c=vm.createContext({S:{session_id:'one',player:'France',date:'1 Jan 1990'},innerWidth:390,innerHeight:844,Date,Promise,
  document:{hidden:false,addEventListener:(kind,fn)=>listeners[kind]=fn},performance:{now:()=>time},requestAnimationFrame:fn=>{frames.set(++id,fn);return id;},cancelAnimationFrame:id=>frames.delete(id),api:async()=>({revision:'pinned',version:'test',branch:'candidate',built_at_unix_seconds:1})});
  vm.runInContext(source+'\nglobalThis.sample=PerformanceSample;',c);return {c,s:c.sample,listeners,frame(now){time=now;const pending=[...frames.values()];frames.clear();for(const fn of pending)fn(now);},frames};}
const event=(time=0)=>({isTrusted:true,timeStamp:time,target:{closest:()=>null}});
test('restart drops pending input callbacks from the prior sample',()=>{const f=fixture();f.s.start();f.c.observePerformanceInput(event());f.frame(10);f.s.start();f.frame(20);assert.equal(f.s.input.length,0);f.c.observePerformanceInput(event(20));f.frame(30);f.frame(40);assert.equal(f.s.input.length,1);assert.equal(f.s.input[0],20);});
test('input spanning a visibility transition is excluded even after returning',()=>{const f=fixture();f.s.start();f.c.observePerformanceInput(event());f.frame(10);f.c.document.hidden=true;f.listeners.visibilitychange();f.c.document.hidden=false;f.listeners.visibilitychange();f.frame(1000);assert.equal(f.s.input.length,0);});
test('hidden periods and a campaign switch cannot contaminate frame timings',()=>{const f=fixture();f.s.start();f.frame(10);f.frame(26);assert.equal(f.s.frames[0],16);f.c.document.hidden=true;f.listeners.visibilitychange();f.frame(5000);f.c.document.hidden=false;f.listeners.visibilitychange();f.frame(6000);f.frame(6016);assert.equal(f.s.frames.length,2);f.c.S.session_id='two';f.frame(6032);assert.equal(f.s.enabled,false);assert.equal(f.s.stopReason,'campaign changed');assert.equal(f.frames.size,0);});
test('records keep a bounded tail, count discarded observations and export copies',()=>{const f=fixture();for(let i=0;i<300;i++)f.s.record('frames',i);f.s.record('frames',NaN);f.s.record('frames',-1);f.s.record('enabled',1);assert.equal(f.s.frames.length,256);assert.equal(f.s.frames[0],44);assert.equal(f.s.dropped.frames,44);const r=f.s.report();r.observations_ms.visible_frame_intervals[0]=999;assert.equal(f.s.frames[0],44);assert.equal(r.visible_frame_intervals.p95_ms,287);});
test('disabled, synthetic and dialog inputs create no samples',()=>{const f=fixture();f.c.observePerformanceInput(event());assert.equal(f.frames.size,0);f.s.start();f.c.observePerformanceInput({...event(),isTrusted:false});f.c.observePerformanceInput({...event(),target:{closest:()=>true}});f.frame(10);f.frame(20);assert.equal(f.s.input.length,0);f.s.stop();assert.equal(f.frames.size,0);});
test('render measurement preserves values and thrown errors without recording after stop',()=>{const f=fixture();f.s.start();assert.equal(f.s.measureRender(()=>7),7);assert.throws(()=>f.s.measureRender(()=>{throw Error('render failed')}),/render failed/);assert.equal(f.s.render.length,2);f.s.measureRender(()=>f.s.stop());assert.equal(f.s.render.length,2);});
test('native build identity is read without commands and unavailable identity stays explicit',async()=>{const f=fixture();f.s.start();await new Promise(r=>setImmediate(r));assert.equal(f.s.build.revision,'pinned');f.c.api=async()=>{throw Error('offline')};f.s.start();await new Promise(r=>setImmediate(r));assert.equal(f.s.build,null);assert.match(f.s.buildError,/unavailable/);});
