'use strict';
// Engineering preflight only. Every campaign mutation uses ordinary browser controls.
// node tools/ui/worldwide_startup_browser.cjs --binary EXE --expected-revision FULL --out NEW --source-root CHECKOUT
// --pilot --countries France,Tonga,Congo permits a diagnostic subset. Only a pilot may attach to --url URL --server-root OWNED.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),cp=require('node:child_process'),net=require('node:net'),zlib=require('node:zlib');
const {chromium}=require('playwright'),{verifyBuild}=require('./ci-integrated.cjs'),lib=require('./worldwide-startup-lib.cjs');
const HOME=path.resolve(__dirname,'../..'),MINISTRIES=lib.MINISTRIES;
const RUNTIME=['spheres-sim','spheres-web','spheres-cli','Cargo.toml','Cargo.lock'];
function args(argv){const o={pilot:false,seed:17};for(let i=0;i<argv.length;i++){const key=argv[i];if(key==='--pilot'){o.pilot=true;continue;}assert(['--binary','--expected-revision','--out','--source-root','--countries','--url','--server-root','--seed'].includes(key),'Unknown argument '+key);assert(argv[i+1]);o[key.slice(2).replace(/-([a-z])/g,(_,c)=>c.toUpperCase())]=argv[++i];}assert(o.binary&&o.expectedRevision&&o.out);assert(/^[a-f0-9]{40}$/.test(o.expectedRevision));assert(!o.countries||o.pilot,'A subset is a pilot');assert(!o.url||o.pilot&&o.serverRoot,'An attached server is a pilot with an explicit owned save root');o.seed=Number(o.seed);assert(Number.isSafeInteger(o.seed)&&o.seed>=0);return o;}
function git(root,...a){return cp.execFileSync('git',a,{cwd:root,windowsHide:true,maxBuffer:32*1024*1024,encoding:'utf8'}).trim();}
function safe(root,file){const relative=path.relative(root,file);assert(relative&&!relative.startsWith('..')&&!path.isAbsolute(relative));return file;}
function regular(file){assert(fs.lstatSync(file).isFile()&&!fs.lstatSync(file).isSymbolicLink());assert.equal(fs.realpathSync(file),file);return file;}
function pins(root,revision){return Object.fromEntries(RUNTIME.map(p=>[p,git(root,'rev-parse',revision+':'+p)]));}
function retainSource(out,sourcePath,bytes,extra={}){const relative='sources/'+sourcePath,target=safe(out,path.join(out,relative));fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,bytes,{flag:'wx'});return {source_path:sourcePath,path:relative,bytes:bytes.length,sha256:lib.hash(bytes),...extra};}
const hashFile=file=>lib.hash(fs.readFileSync(file)),post=(r,p)=>r.request().method()==='POST'&&new URL(r.url()).pathname===p;
const idle=page=>page.waitForFunction(()=>!SESSION.busy&&!advancing&&!pendingAdvance&&!COMMAND_CHANNEL.busy&&!COMMAND_CHANNEL.pending&&!AGENCY.busy&&!gov.busy);
async function get(page,url,route){const r=await page.request.get(url+route);try{assert(r.ok(),route+' '+r.status());return await r.json();}finally{await r.dispose();}}
async function response(page,route,action){const waiting=page.waitForResponse(r=>post(r,route));await action();const r=await waiting;const body=await r.json();assert(r.ok(),route+' '+r.status()+': '+JSON.stringify(body));assert.deepEqual(body.errors||[],[]);return {payload:r.request().postDataJSON(),body};}
async function campaigns(page){if(await page.locator('#app').isVisible()){if(!await page.locator('#campaignsBtn').isVisible())await page.locator('.arc-time-menu > summary').click();await page.locator('#campaignsBtn').click();}if(!await page.locator('#campaignHome').isVisible())await page.locator('#savedCampaigns [data-menu-back]').click();}
async function saves(page){await campaigns(page);await page.locator('#openSavesBtn').click();await page.locator('#savedCampaigns').waitFor({state:'visible'});}
async function save(page,slot){await saves(page);await page.locator('#saveName').fill(slot);const r=await response(page,'/api/save',()=>page.locator('#saveNamedBtn').click());assert.equal(r.body.ok,true);await page.waitForFunction(()=>!document.getElementById('saveNamedBtn').disabled);return r;}
async function load(page,slot){await page.locator('#saveSlots').selectOption(slot);const r=await response(page,'/api/load',async()=>{await page.locator('#loadBtn').click();await page.locator('#campaignConfirmAccept').click();});await page.locator('#app').waitFor({state:'visible'});await idle(page);return r;}
function observeMap(){
  window.__worldwideMap={draws:0};const original=HTMLCanvasElement.prototype.getContext;
  HTMLCanvasElement.prototype.getContext=function(kind,...rest){const gl=original.call(this,kind,...rest);if(gl&&['webgl','webgl2','experimental-webgl'].includes(kind)&&!gl.__worldwideObserved){gl.__worldwideObserved=true;for(const name of ['drawElements','drawArrays','drawElementsInstanced','drawArraysInstanced'])if(typeof gl[name]==='function'){const draw=gl[name];gl[name]=function(...v){const result=draw.apply(this,v),count=name.startsWith('drawElements')?v[1]:v[2];if(this.canvas.id==='glmap'&&count>0&&!this.isContextLost())window.__worldwideMap.draws++;return result;};}}return gl;};
}
async function layout(locator){const b=await locator.evaluate(e=>({width:e.clientWidth,scroll:e.scrollWidth}));assert(b.width>0&&b.scroll<=b.width+1,'Room horizontal overflow');assert(!/\bNaN\b|\bundefined\b/.test(await locator.innerText()),'Invalid room label');return b;}
async function capture(ctx,c,page,label){const relative='screenshots/'+c.nation.toLowerCase()+'-'+label+'.jpg',file=safe(ctx.out,path.join(ctx.out,relative));fs.mkdirSync(path.dirname(file),{recursive:true});await page.screenshot({path:file,type:'jpeg',quality:65,animations:'disabled'});c.screenshots.push({stage:label,path:relative,bytes:fs.statSync(file).size,sha256:hashFile(file),viewport:page.viewportSize()});}
async function views(ctx,c,page,row,phase){
  const state=await get(page,ctx.url,'/api/state');assert.equal(state.player,row.id);assert((await page.locator('#hdrYou').innerText()).includes(row.name));
  const record=c.views[phase]={};
  await page.waitForFunction(()=>GL.ok&&GL.ready&&GLOBE?.lastSize);
  const before=await page.evaluate(()=>window.__worldwideMap.draws);
  await page.locator('[data-map-action="world"]').click();await page.locator('[data-map-action="home"]').click();
  await page.waitForFunction(()=>camAnim===0);
  await page.waitForFunction(n=>window.__worldwideMap.draws>n,before);
  record.map=await page.evaluate(({before,nation})=>{const box=GLCV.getBoundingClientRect(),style=getComputedStyle(GLCV);return {draws_before:before,draws_after:__worldwideMap.draws,width:GLCV.width,height:GLCV.height,visible:GLCV.checkVisibility({checkOpacity:true,checkVisibilityCSS:true})&&style.display!=='none'&&box.width>0&&box.height>0,in_viewport:box.bottom>0&&box.right>0&&box.top<innerHeight&&box.left<innerWidth,owned_districts:Object.keys(DINDEX).filter(id=>nationOfDistrict(id)===nation).length,camera:{cx:ui.cam.cx,cy:ui.cam.cy,yaw:GLOBE.yaw,pitch:GLOBE.pitch,zoom:GLOBE.zoom},player:S.player};},{before,nation:row.id});
  assert(record.map.width>0&&record.map.height>0&&record.map.visible&&record.map.in_viewport);assert(Object.values(record.map.camera).every(Number.isFinite));await capture(ctx,c,page,phase+'-map');
  if(ctx.zeroDistricts.includes(row.id)){
    assert.equal(record.map.owned_districts,0);const label=await page.evaluate(id=>{const target=GLOBE.nationLabelHits.find(h=>h.id===id);if(!target)return null;const rect=GLCV.getBoundingClientRect(),client_x=rect.left+target.box[0]*rect.width/GLOBE.lastSize.width,client_y=rect.top+target.box[1]*rect.height/GLOBE.lastSize.height;return {...target,client_x,client_y,hit_nation:GLOBE.nationLabelAt(client_x,client_y),canvas_topmost:document.elementFromPoint(client_x,client_y)===GLCV};},row.id);assert(label&&label.id===row.id&&label.hit_nation===row.id&&label.canvas_topmost,'Canonical island label must be visible and selectable');
    record.map.label=label;await page.mouse.click(label.client_x,label.client_y);await page.locator('#sheet').waitFor({state:'visible'});label.opened_nation=await page.evaluate(()=>selected);label.dossier_title=(await page.locator('#sheet .arc-nation-hero h1').innerText()).trim();assert.equal(label.opened_nation,row.id);assert.equal(label.dossier_title,row.name);await page.getByRole('button',{name:'Close national dossier',exact:true}).click();
  }else assert(record.map.owned_districts>0,'Country missing its canonical district geometry');c.checks.push(phase+'_map');
  await page.locator('#govBtn').click();await page.waitForFunction(()=>gov.open&&gov.data&&gov.dataState===S&&!gov.data.error);
  const data=await page.evaluate(()=>gov.data),native=await get(page,ctx.url,'/api/government?nation='+encodeURIComponent(row.id));assert.deepEqual(data,native);assert.equal(data.nation,row.id);assert.equal(data.mine,true);
  const hero=(await page.locator('#govScreen .gov-ui-hero h1').innerText()).trim(),holder=data.leader&&(data.leader.name||data.leader.described)||data.ruling_institution;
  assert.equal(hero,row.name);assert(holder&&(await page.locator('#gov-panel-overview').innerText()).includes(holder));
  const tab=(await page.locator('#gov-tab-politics').innerText()).trim();assert.equal(tab,data.electoral?'Parliament & parties':'Regime & institutions');
  record.government={nation:data.nation,hero,officeholder:holder,electoral:data.electoral,politics_tab:tab,native_reading_sha256:lib.hash(JSON.stringify(native)),layout:await layout(page.locator('#govScreen .gov-ui'))};
  c.checks.push(phase+'_government');await capture(ctx,c,page,phase+'-government');await page.locator('#govScreen .tbar .x').click();
  await page.locator('[data-drawer="cabinetDrawer"]').click();await page.locator('#cab-tab-budget').click();await page.locator('#cabinet-budget').waitFor({state:'visible'});
  const tiles=await page.locator('#cabinet-budget [data-cab-ministry]').evaluateAll(es=>es.map(e=>e.dataset.cabMinistry)),summary=(await page.locator('#cabinetBudgetSummary').innerText()).trim(),kicker=(await page.locator('#cabinetNationDetails .cab-kicker').first().textContent()).trim();
  assert.deepEqual([...tiles].sort(),[...MINISTRIES].sort());assert(summary&&kicker.includes(row.name));const cash=await get(page,ctx.url,'/api/cash-flow?session_id='+encodeURIComponent(state.session_id));assert.equal(cash.nation,row.id);
  record.budget={nation:cash.nation,ministries:tiles,summary,kicker,layout:await layout(page.locator('#cabinet-budget'))};c.checks.push(phase+'_budget');await capture(ctx,c,page,phase+'-budget');await page.locator('#cabinetDrawer [data-close-drawers]').click();
  const reading=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/guidance'&&r.request().method()==='GET');await page.locator('.decision-nav').getByRole('button',{name:'Advisors',exact:true}).click();
  await page.locator('#guidanceDialog .guidance-cards[aria-busy="false"]').waitFor();const r=await reading,guidance=await r.json();assert(r.ok());assert.equal(guidance.state.player,row.id);assert.equal(guidance.state.session_id,state.session_id);
  const cards=(await page.locator('#guidanceDialog .guidance-cards').innerText()).trim();assert(cards);record.guidance={player:guidance.state.player,cards:cards.slice(0,1500),layout:await layout(page.locator('#guidanceDialog'))};c.checks.push(phase+'_guidance');await capture(ctx,c,page,phase+'-guidance');await page.getByRole('button',{name:'Close tutorial and advisors',exact:true}).click();
  assert.deepEqual(await get(page,ctx.url,'/api/state'),state,'Read-only UI changed live campaign');
}
function retain(ctx,c,slot,label){const file=safe(ctx.run,path.join(ctx.run,'saves',slot+'.json')),bytes=fs.readFileSync(regular(file)),record=lib.archive(bytes),relative='archives/'+c.nation.toLowerCase()+'-'+label+'.json.gz',target=safe(ctx.out,path.join(ctx.out,relative));fs.mkdirSync(path.dirname(target),{recursive:true});const compressed=zlib.gzipSync(bytes,{level:6});fs.writeFileSync(target,compressed,{flag:'wx'});assert.equal(lib.hash(zlib.gunzipSync(compressed)),record.sha256);return {...record,path:relative,gzip_bytes:compressed.length,gzip_sha256:lib.hash(compressed)};}
async function caseRun(ctx,browser,row){const c={nation:row.id,name:row.name,passed:false,checks:[],views:{},advances:[],requests:[],page_errors:[],screenshots:[],started_utc:new Date().toISOString()},start=Date.now();let context,page,stage='context';
  try{context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});page=await context.newPage();page.setDefaultTimeout(30000);await page.addInitScript(observeMap);page.on('pageerror',error=>c.page_errors.push(error.message));page.on('request',r=>{if(r.method()==='POST')c.requests.push({stage,path:new URL(r.url()).pathname,payload:r.postDataJSON()});});
    await page.goto(ctx.url,{waitUntil:'domcontentloaded'});await page.waitForFunction(()=>!!SESSION.live?.session_id);await campaigns(page);
    stage='ordinary_selection';await page.locator('#newCampaignBtn').click();await page.locator('#nationPick .opt').filter({has:page.locator('.nm').getByText(row.name,{exact:true})}).click();
    const seed=page.locator('#seed');if(!await seed.isVisible())await page.locator('details').filter({has:seed}).locator('summary').click();await seed.fill(String(ctx.options.seed));
    const replacing=await page.evaluate(()=>!!SESSION.live.player);const started=await response(page,'/api/new',async()=>{await page.locator('#startBtn').click();if(replacing)await page.locator('#campaignConfirmAccept').click();});
    await page.locator('#app').waitFor({state:'visible'});await idle(page);c.before={player:started.body.player,year:started.body.year,month:started.body.month,day:started.body.day};assert.equal(c.before.player,row.id);assert.equal(lib.day(c.before),Date.UTC(1990,0,1)/86400000);assert.equal(await page.evaluate(()=>clock.running),false);c.checks.push(stage);
    stage='opening_views';await views(ctx,c,page,row,'opening');
    stage='seven_visible_days';for(let i=0;i<7;i++){const previous=await get(page,ctx.url,'/api/state');const r=await response(page,'/api/advance',()=>page.locator('#stepBtn').click());await idle(page);assert.equal(r.payload.days,1);assert.equal(r.body.player,row.id);assert.equal(lib.day(r.body),lib.day(previous)+1);c.advances.push({before:lib.day(previous),after:lib.day(r.body),days:r.payload.days,player:r.body.player,errors:r.body.errors||[],interrupt:r.body.interrupt||null,session_id:r.body.session_id});}c.checks.push(stage);
    stage='named_save';const slot='startup-before';await save(page,slot);c.before_save=retain(ctx,c,slot,'before');c.old_session=(await get(page,ctx.url,'/api/state')).session_id;c.checks.push(stage);
    stage='ordinary_reload';const loaded=await load(page,slot);c.new_session=loaded.body.session_id;assert.notEqual(c.old_session,c.new_session);c.after={player:loaded.body.player,year:loaded.body.year,month:loaded.body.month,day:loaded.body.day};c.checks.push(stage);
    stage='reloaded_views';await page.setViewportSize({width:390,height:844});await views(ctx,c,page,row,'reloaded');
    stage='exact_archive_roundtrip';await save(page,'startup-after');c.after_save=retain(ctx,c,'startup-after','after');assert.equal(c.after_save.campaign_sha256,c.before_save.campaign_sha256);c.checks.push(stage);
    assert.deepEqual(c.page_errors,[]);c.checks.push('no_page_errors');stage='ordinary_mutations_only';assert.deepEqual(c.requests.filter(r=>r.path!=='/api/program-preview').map(r=>r.path),['/api/new',...Array(7).fill('/api/advance'),'/api/save','/api/load','/api/save']);assert(c.requests.filter(r=>r.path==='/api/advance').every(r=>r.payload.commands?.length===0));c.checks.push(stage);c.passed=true;
  }catch(error){c.error=error.stack||String(error);c.failed_stage=stage;if(page)await capture(ctx,c,page,'failure').catch(e=>{c.failure_capture_error=String(e);});c.retained_failure_slots=[];for(const slot of ['startup-before','startup-after'])if(fs.existsSync(path.join(ctx.run,'saves',slot+'.json')))try{c.retained_failure_slots.push(retain(ctx,c,slot,slot+'-failure'));}catch(e){c.failure_retention_error=String(e);}}
  finally{if(context)await context.close();c.elapsed_seconds=(Date.now()-start)/1000;c.finished_utc=new Date().toISOString();}
  return c;
}
async function freePort(){const s=net.createServer();await new Promise(resolve=>s.listen(0,'127.0.0.1',resolve));const port=s.address().port;await new Promise(resolve=>s.close(resolve));return port;}
async function main(){const o=args(process.argv.slice(2)),root=path.resolve(o.sourceRoot||HOME),out=path.resolve(o.out),binary=regular(path.resolve(o.binary));assert(!fs.existsSync(out),'Keep prior evidence; choose a new output');fs.mkdirSync(out,{recursive:true});assert.equal(fs.realpathSync(out),out);
  const run=o.url?path.resolve(o.serverRoot):safe(out,path.join(out,'server'));if(!o.url)fs.mkdirSync(run);else assert.equal(fs.realpathSync(run),run);
  const originalPins=pins(root,o.expectedRevision),originalDriver=hashFile(__filename),originalHelper=hashFile(path.join(__dirname,'worldwide-startup-lib.cjs'));
  if(!o.pilot){assert.equal(git(HOME,'status','--porcelain','--',...lib.SOURCES),'','Commit the harness before a full run');}
  const result={format:'spheres-worldwide-browser/v1',scope:'Bounded startup engineering preflight; no historical, S24 or CP1 qualification',pilot:o.pilot,attached_server:!!o.url,coverage:o.pilot?'pilot':'all_starters',seed:o.seed,runtime:{expected_revision:o.expectedRevision,binary_sha256:hashFile(binary),source_trees:originalPins},harness:{revision:git(HOME,'rev-parse','HEAD'),driver_sha256:originalDriver,helper_sha256:originalHelper,verifier_sha256:hashFile(path.join(__dirname,'ci-integrated.cjs'))},source_checkout_head_before:git(root,'rev-parse','HEAD'),started_utc:new Date().toISOString(),roster:[],requested_ids:[],cases:[],passed:false,all_137_passed:false,cleanup:{browser_closed:false,server_stopped:false}};
  result.harness.sources=lib.SOURCES.map(p=>retainSource(out,p,fs.readFileSync(path.join(HOME,p))));
  const nationSource=cp.execFileSync('git',['show',o.expectedRevision+':spheres-sim/src/nations.rs'],{cwd:root,windowsHide:true,maxBuffer:4*1024*1024});result.canonical_roster={...retainSource(out,'runtime/nations.rs',nationSource),git_blob:git(root,'rev-parse',o.expectedRevision+':spheres-sim/src/nations.rs'),revision:o.expectedRevision,rows:lib.canonicalRoster(nationSource)};
  const districtSource=cp.execFileSync('git',['show',o.expectedRevision+':spheres-sim/data/districts.json'],{cwd:root,windowsHide:true,maxBuffer:4*1024*1024});result.canonical_geometry={...retainSource(out,'runtime/districts.json',districtSource),git_blob:git(root,'rev-parse',o.expectedRevision+':spheres-sim/data/districts.json'),revision:o.expectedRevision,zero_district_ids:lib.zeroDistricts(districtSource,result.canonical_roster.rows)};
  result.provenance_scope='The frozen binary is rehashed at both boundaries; served assets are verified at start against the exact runtime commit. Immutable Git tree IDs are pinned. Mutable checkout HEAD is documentary, not an unchanged-checkout claim. Campaign archives have no original seed field; the seed is bound to each ordinary new-campaign request.';
  const write=()=>fs.writeFileSync(path.join(out,'result.json'),JSON.stringify(result,null,2)+'\n');let server,browser,log,url=o.url;
  try{if(!url){url='http://127.0.0.1:'+await freePort();log=fs.openSync(path.join(out,'server.log'),'wx');server=cp.spawn(binary,['--port',new URL(url).port,'--no-open'],{cwd:run,windowsHide:true,stdio:['ignore',log,log]});}else assert(['127.0.0.1','localhost'].includes(new URL(url).hostname));result.url=url;result.run=run;
    let build;for(let i=0;i<300;i++){try{const r=await fetch(url+'/api/build');if(r.ok){build=await r.json();break;}}catch{}await new Promise(resolve=>setTimeout(resolve,100));}assert(build,'Server did not start');assert.equal(build.full_revision,o.expectedRevision);assert.equal(path.resolve(build.save_directory),run);result.runtime.build=build;
    browser=await chromium.launch({headless:true,...(process.env.SPHERES_BROWSER_CHANNEL?{channel:process.env.SPHERES_BROWSER_CHANNEL}:{})});result.browser_version=browser.version();const p=await browser.newPage();process.env.SPHERES_EXPECTED_REVISION=o.expectedRevision;result.runtime.verification=await verifyBuild({page:p,url,root,run,binary});
    const listing=await get(p,url,'/api/roster');result.roster=lib.roster(listing.nations);assert.deepEqual(result.roster,result.canonical_roster.rows,'Served starter roster must equal the exact runtime source');await p.close();const wanted=o.countries?o.countries.split(','):result.roster.map(r=>r.id);assert.equal(new Set(wanted).size,wanted.length);assert(wanted.every(id=>result.roster.some(r=>r.id===id)));result.requested_ids=wanted;write();
    for(const id of wanted){const c=await caseRun({options:o,out,run,url,zeroDistricts:result.canonical_geometry.zero_district_ids},browser,result.roster.find(r=>r.id===id));result.cases.push(c);write();console.log(`${result.cases.length}/${wanted.length} ${id}: ${c.passed?'PASS':'FAIL '+c.failed_stage} (${c.elapsed_seconds.toFixed(1)}s)`);}
  }catch(error){result.error=error.stack||String(error);}
  finally{if(browser)await browser.close();result.cleanup.browser_closed=true;if(server){server.kill();await Promise.race([new Promise(resolve=>server.exitCode!==null?resolve():server.once('exit',resolve)),new Promise(resolve=>setTimeout(resolve,10000))]);result.cleanup.server_stopped=server.exitCode!==null||server.signalCode!==null;}else result.cleanup.server_left_running=!!o.url;if(log!==undefined)fs.closeSync(log);result.runtime.binary_sha256_after=hashFile(binary);result.source_checkout_head_after=git(root,'rev-parse','HEAD');result.immutable_inputs_unchanged=JSON.stringify(pins(root,o.expectedRevision))===JSON.stringify(originalPins)&&result.harness.sources.every(pin=>hashFile(path.join(HOME,pin.source_path))===pin.sha256)&&result.runtime.binary_sha256_after===result.runtime.binary_sha256;result.finished_utc=new Date().toISOString();result.validation_errors=lib.validate(result);result.passed=!result.error&&result.validation_errors.length===0;result.all_137_passed=result.passed&&!o.pilot;write();}
  if(result.passed)try{const verified=lib.verifyEvidence(result,out);fs.writeFileSync(path.join(out,'retained-verification.json'),JSON.stringify(verified,null,2)+'\n',{flag:'wx'});result.retained_verification=verified;}catch(error){result.error='Retained evidence verification failed: '+(error.stack||error);result.passed=false;result.all_137_passed=false;}
  write();assert(result.passed,'Startup run failed; inspect '+path.join(out,'result.json'));
}
if(require.main===module)main().catch(error=>{console.error(error.stack||error);process.exitCode=1;});
module.exports={args,observeMap};
