import pathlib,json,subprocess,datetime,hashlib
root=pathlib.Path('D:/spheres-offload/codex-next-20260928/c01-ordered-integration');out=pathlib.Path('D:/spheres-offload/codex-next-20260928/c01-combined-validation');out.mkdir(exist_ok=False)
commands=[('france',['python','-B','-X','utf8','-m','unittest','discover','-s','tools/avatars','-p','test_france*.py']),('tonga',['python','-B','-X','utf8','-m','unittest','discover','-s','tools/avatars','-p','test_tonga*.py']),('saudi',['python','-B','-X','utf8','-m','unittest','discover','-s','tools/avatars','-p','test_saudi*.py']),('india',['python','-B','-X','utf8','-m','unittest','discover','-s','tools/avatars','-p','test_india*.py']),('research',['python','-B','-X','utf8','-m','unittest','discover','-s','tools/avatars','-p','test_*research*.py']),('importer',['python','-B','-X','utf8','-m','unittest','discover','-s','tools/avatars','-p','test_import_cnccfp_census.py']),('campaign',['python','-B','-X','utf8','-m','unittest','discover','-s','tools/avatars','-p','test_campaign*.py']),('atlas',['node','tools/ui/check_leadership_research_review.cjs']),('importer-check',['python','-B','-X','utf8','tools/avatars/import_cnccfp_census.py','--check']),('census',['python','-B','-X','utf8','tools/avatars/campaign_census.py','--check']),('index',['python','-B','-X','utf8','tools/avatars/campaign_research.py','--check']),('workboard',['python','-B','-X','utf8','tools/planning/workboard.py','--check']),('diff',['git','diff','--check','8d338dd2','HEAD'])]
rows=[]
for name,args in commands:
 start=datetime.datetime.now(datetime.timezone.utc).isoformat()
 with (out/(name+'.log')).open('wb') as f:r=subprocess.run(args,cwd=root,stdout=f,stderr=subprocess.STDOUT,timeout=300)
 b=(out/(name+'.log')).read_bytes();rows.append({'name':name,'command':args,'exit_code':r.returncode,'started_utc':start,'finished_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'log':name+'.log','bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()});print(name,r.returncode,flush=True)
 (out/'commands.json').write_bytes((json.dumps({'source_revision':subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip(),'commands':rows},indent=2)+'\n').encode())
