//! Generated by tools/avatars/fetch_commons_portraits.py. Do not edit by hand.

pub struct PortraitAsset {
    pub bytes: &'static [u8],
    pub content_type: &'static str,
}

pub fn get(name: &str) -> Option<PortraitAsset> {
    match name {
        "Afghanistan-fce177144639.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Afghanistan-fce177144639.webp"),
            content_type: "image/webp",
        }),
        "Afghanistan-leader-f86caeb10c1d.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Afghanistan-leader-f86caeb10c1d.png"),
            content_type: "image/png",
        }),
        "Albania-dc27557adba1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Albania-dc27557adba1.webp"),
            content_type: "image/webp",
        }),
        "Albania-leader-903811fcd953.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Albania-leader-903811fcd953.png"),
            content_type: "image/png",
        }),
        "Algeria-0b9c67b3580c.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Algeria-0b9c67b3580c.webp"),
            content_type: "image/webp",
        }),
        "Algeria-leader-40fd7af2f732.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Algeria-leader-40fd7af2f732.png"),
            content_type: "image/png",
        }),
        "Angola-leader-f4e74b240157.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Angola-leader-f4e74b240157.png"),
            content_type: "image/png",
        }),
        "Argentina-b91623db6af3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Argentina-b91623db6af3.webp"),
            content_type: "image/webp",
        }),
        "Argentina-leader-a101d5f078a3.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Argentina-leader-a101d5f078a3.png"),
            content_type: "image/png",
        }),
        "Armenia-a368e4ff55d1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Armenia-a368e4ff55d1.webp"),
            content_type: "image/webp",
        }),
        "Armenia-leader-ca833833a698.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Armenia-leader-ca833833a698.png"),
            content_type: "image/png",
        }),
        "Australia-leader-f55526a0d34c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Australia-leader-f55526a0d34c.png"),
            content_type: "image/png",
        }),
        "Austria-8654c9cef838.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Austria-8654c9cef838.webp"),
            content_type: "image/webp",
        }),
        "Austria-leader-df62375be251.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Austria-leader-df62375be251.png"),
            content_type: "image/png",
        }),
        "Azerbaijan-2f640fd15e9b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Azerbaijan-2f640fd15e9b.webp"),
            content_type: "image/webp",
        }),
        "Azerbaijan-leader-5c9cd794afa1.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Azerbaijan-leader-5c9cd794afa1.png"),
            content_type: "image/png",
        }),
        "Bahamas-1c8efdb481a3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Bahamas-1c8efdb481a3.webp"),
            content_type: "image/webp",
        }),
        "Bahamas-leader-8572851d48cb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Bahamas-leader-8572851d48cb.png"),
            content_type: "image/png",
        }),
        "Bahrain-948f22793ce8.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Bahrain-948f22793ce8.webp"),
            content_type: "image/webp",
        }),
        "Bahrain-leader-85ca829f1fb7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Bahrain-leader-85ca829f1fb7.png"),
            content_type: "image/png",
        }),
        "Bangladesh-c46c7660231d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Bangladesh-c46c7660231d.webp"),
            content_type: "image/webp",
        }),
        "Bangladesh-leader-22739f7701b4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Bangladesh-leader-22739f7701b4.png"),
            content_type: "image/png",
        }),
        "Belarus-30cc563e5afb.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Belarus-30cc563e5afb.webp"),
            content_type: "image/webp",
        }),
        "Belarus-leader-c9f31ded4c1a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Belarus-leader-c9f31ded4c1a.png"),
            content_type: "image/png",
        }),
        "Belgium-leader-e9b24afba072.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Belgium-leader-e9b24afba072.png"),
            content_type: "image/png",
        }),
        "Belize-leader-3228c097c1df.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Belize-leader-3228c097c1df.png"),
            content_type: "image/png",
        }),
        "Bhutan-ae31c54f2ad4.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Bhutan-ae31c54f2ad4.webp"),
            content_type: "image/webp",
        }),
        "Bhutan-leader-b2cf694ebed0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Bhutan-leader-b2cf694ebed0.png"),
            content_type: "image/png",
        }),
        "Bolivia-bba86fa3bff1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Bolivia-bba86fa3bff1.webp"),
            content_type: "image/webp",
        }),
        "Bolivia-leader-2ea566d44234.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Bolivia-leader-2ea566d44234.png"),
            content_type: "image/png",
        }),
        "Bosnia-cca8507f915e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Bosnia-cca8507f915e.webp"),
            content_type: "image/webp",
        }),
        "Bosnia-leader-e78227c3f1b4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Bosnia-leader-e78227c3f1b4.png"),
            content_type: "image/png",
        }),
        "Botswana-6957bece838d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Botswana-6957bece838d.webp"),
            content_type: "image/webp",
        }),
        "Botswana-leader-1bd3e888ee42.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Botswana-leader-1bd3e888ee42.png"),
            content_type: "image/png",
        }),
        "Brazil-dd81b9e75b6c.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Brazil-dd81b9e75b6c.webp"),
            content_type: "image/webp",
        }),
        "Brazil-leader-d0f6f3b52a10.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Brazil-leader-d0f6f3b52a10.png"),
            content_type: "image/png",
        }),
        "Brunei-148342c02d15.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Brunei-148342c02d15.webp"),
            content_type: "image/webp",
        }),
        "Brunei-leader-740096a4e925.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Brunei-leader-740096a4e925.png"),
            content_type: "image/png",
        }),
        "Bulgaria-673e684ff947.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Bulgaria-673e684ff947.webp"),
            content_type: "image/webp",
        }),
        "Bulgaria-leader-df60ef4ca603.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Bulgaria-leader-df60ef4ca603.png"),
            content_type: "image/png",
        }),
        "Cambodia-1fef6e1ef9b7.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Cambodia-1fef6e1ef9b7.webp"),
            content_type: "image/webp",
        }),
        "Cambodia-leader-36a4db761f64.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Cambodia-leader-36a4db761f64.png"),
            content_type: "image/png",
        }),
        "Cameroon-bd66e3ef1a63.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Cameroon-bd66e3ef1a63.webp"),
            content_type: "image/webp",
        }),
        "Cameroon-leader-fbdadb6d80fa.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Cameroon-leader-fbdadb6d80fa.png"),
            content_type: "image/png",
        }),
        "Canada-e1b5c394ad55.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Canada-e1b5c394ad55.webp"),
            content_type: "image/webp",
        }),
        "Canada-leader-5e8ec77bcd18.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Canada-leader-5e8ec77bcd18.png"),
            content_type: "image/png",
        }),
        "CapeVerde-4436e5afadf5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/CapeVerde-4436e5afadf5.webp"),
            content_type: "image/webp",
        }),
        "CapeVerde-leader-35a141178c3b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/CapeVerde-leader-35a141178c3b.png"),
            content_type: "image/png",
        }),
        "CentralAfricanRepublic-d2777cd71eeb.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/CentralAfricanRepublic-d2777cd71eeb.webp"),
            content_type: "image/webp",
        }),
        "CentralAfricanRepublic-leader-c57ccb06fdc7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/CentralAfricanRepublic-leader-c57ccb06fdc7.png"),
            content_type: "image/png",
        }),
        "Chad-leader-4bc000d7aee9.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Chad-leader-4bc000d7aee9.png"),
            content_type: "image/png",
        }),
        "Chile-8ca8a4c797a3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Chile-8ca8a4c797a3.webp"),
            content_type: "image/webp",
        }),
        "Chile-leader-ee0b701ecc5a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Chile-leader-ee0b701ecc5a.png"),
            content_type: "image/png",
        }),
        "China-a8ba380d17c6.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/China-a8ba380d17c6.webp"),
            content_type: "image/webp",
        }),
        "China-leader-350f76603ff5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/China-leader-350f76603ff5.png"),
            content_type: "image/png",
        }),
        "Colombia-8857df09c470.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Colombia-8857df09c470.webp"),
            content_type: "image/webp",
        }),
        "Colombia-leader-b33336138ce5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Colombia-leader-b33336138ce5.png"),
            content_type: "image/png",
        }),
        "Comoros-leader-0cbc3b8182b8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Comoros-leader-0cbc3b8182b8.png"),
            content_type: "image/png",
        }),
        "Congo-11dca3605869.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Congo-11dca3605869.webp"),
            content_type: "image/webp",
        }),
        "Congo-leader-e306732110d9.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Congo-leader-e306732110d9.png"),
            content_type: "image/png",
        }),
        "CostaRica-eabce8094e78.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/CostaRica-eabce8094e78.webp"),
            content_type: "image/webp",
        }),
        "CostaRica-leader-99717561cd37.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/CostaRica-leader-99717561cd37.png"),
            content_type: "image/png",
        }),
        "Croatia-40e31abb08ec.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Croatia-40e31abb08ec.webp"),
            content_type: "image/webp",
        }),
        "Croatia-leader-a02aa5a96157.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Croatia-leader-a02aa5a96157.png"),
            content_type: "image/png",
        }),
        "Cuba-ec84e0920b43.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Cuba-ec84e0920b43.webp"),
            content_type: "image/webp",
        }),
        "Cuba-leader-72a2d0148fef.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Cuba-leader-72a2d0148fef.png"),
            content_type: "image/png",
        }),
        "Cyprus-739821002edf.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Cyprus-739821002edf.webp"),
            content_type: "image/webp",
        }),
        "Cyprus-leader-554396a51feb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Cyprus-leader-554396a51feb.png"),
            content_type: "image/png",
        }),
        "Czechoslovakia-d2402dd13b8d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Czechoslovakia-d2402dd13b8d.webp"),
            content_type: "image/webp",
        }),
        "Czechoslovakia-leader-9fca0a08f5ca.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Czechoslovakia-leader-9fca0a08f5ca.png"),
            content_type: "image/png",
        }),
        "Denmark-1d8d01f03ea7.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Denmark-1d8d01f03ea7.webp"),
            content_type: "image/webp",
        }),
        "Denmark-leader-7db97be7511b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Denmark-leader-7db97be7511b.png"),
            content_type: "image/png",
        }),
        "DominicanRepublic-f876ab0536fd.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/DominicanRepublic-f876ab0536fd.webp"),
            content_type: "image/webp",
        }),
        "DominicanRepublic-leader-338e895731fa.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/DominicanRepublic-leader-338e895731fa.png"),
            content_type: "image/png",
        }),
        "EastTimor-803175d13879.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/EastTimor-803175d13879.webp"),
            content_type: "image/webp",
        }),
        "EastTimor-leader-f1dd388f69b7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/EastTimor-leader-f1dd388f69b7.png"),
            content_type: "image/png",
        }),
        "Ecuador-625d480e50f7.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Ecuador-625d480e50f7.webp"),
            content_type: "image/webp",
        }),
        "Ecuador-leader-a83ed4f7cde5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Ecuador-leader-a83ed4f7cde5.png"),
            content_type: "image/png",
        }),
        "Egypt-9002995e92ea.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Egypt-9002995e92ea.webp"),
            content_type: "image/webp",
        }),
        "Egypt-leader-a9767e906d23.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Egypt-leader-a9767e906d23.png"),
            content_type: "image/png",
        }),
        "ElSalvador-3f5bddcbf46c.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/ElSalvador-3f5bddcbf46c.webp"),
            content_type: "image/webp",
        }),
        "ElSalvador-leader-106251a76796.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/ElSalvador-leader-106251a76796.png"),
            content_type: "image/png",
        }),
        "EquatorialGuinea-5fbe4aec0a0a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/EquatorialGuinea-5fbe4aec0a0a.webp"),
            content_type: "image/webp",
        }),
        "EquatorialGuinea-leader-3709a2e9b864.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/EquatorialGuinea-leader-3709a2e9b864.png"),
            content_type: "image/png",
        }),
        "Estonia-eefc03c6692e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Estonia-eefc03c6692e.webp"),
            content_type: "image/webp",
        }),
        "Estonia-leader-d7c769b9b9c7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Estonia-leader-d7c769b9b9c7.png"),
            content_type: "image/png",
        }),
        "Ethiopia-a078474d6dc1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Ethiopia-a078474d6dc1.webp"),
            content_type: "image/webp",
        }),
        "Ethiopia-leader-cab15e7748e8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Ethiopia-leader-cab15e7748e8.png"),
            content_type: "image/png",
        }),
        "Fiji-e526b1a13c3a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Fiji-e526b1a13c3a.webp"),
            content_type: "image/webp",
        }),
        "Fiji-leader-c636a3f231f6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Fiji-leader-c636a3f231f6.png"),
            content_type: "image/png",
        }),
        "Finland-85477212a438.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Finland-85477212a438.webp"),
            content_type: "image/webp",
        }),
        "Finland-leader-0a2cdb94da79.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Finland-leader-0a2cdb94da79.png"),
            content_type: "image/png",
        }),
        "France-fcd6b90d4338.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/France-fcd6b90d4338.webp"),
            content_type: "image/webp",
        }),
        "France-leader-45efa5125248.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/France-leader-45efa5125248.png"),
            content_type: "image/png",
        }),
        "Gabon-leader-a07a1ecd636f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Gabon-leader-a07a1ecd636f.png"),
            content_type: "image/png",
        }),
        "Georgia-616c410a0127.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Georgia-616c410a0127.webp"),
            content_type: "image/webp",
        }),
        "Georgia-leader-a68f4b0660b0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Georgia-leader-a68f4b0660b0.png"),
            content_type: "image/png",
        }),
        "Germany-leader-82e3ff0675fe.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Germany-leader-82e3ff0675fe.png"),
            content_type: "image/png",
        }),
        "Ghana-1c298c7d5d5a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Ghana-1c298c7d5d5a.webp"),
            content_type: "image/webp",
        }),
        "Ghana-leader-2ccab2063dd4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Ghana-leader-2ccab2063dd4.png"),
            content_type: "image/png",
        }),
        "Greece-8630f8dc9e62.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Greece-8630f8dc9e62.webp"),
            content_type: "image/webp",
        }),
        "Greece-leader-63df4fe43beb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Greece-leader-63df4fe43beb.png"),
            content_type: "image/png",
        }),
        "Guatemala-b4499f3121d1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Guatemala-b4499f3121d1.webp"),
            content_type: "image/webp",
        }),
        "Guatemala-leader-ad689e066275.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Guatemala-leader-ad689e066275.png"),
            content_type: "image/png",
        }),
        "Guyana-d84ea0bada0e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Guyana-d84ea0bada0e.webp"),
            content_type: "image/webp",
        }),
        "Guyana-leader-38003ef82d27.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Guyana-leader-38003ef82d27.png"),
            content_type: "image/png",
        }),
        "Haiti-17fd6a98fbd3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Haiti-17fd6a98fbd3.webp"),
            content_type: "image/webp",
        }),
        "Haiti-leader-e5fe31935f13.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Haiti-leader-e5fe31935f13.png"),
            content_type: "image/png",
        }),
        "Honduras-f9e7b2b05ab5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Honduras-f9e7b2b05ab5.webp"),
            content_type: "image/webp",
        }),
        "Honduras-leader-30a3fd9e88a0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Honduras-leader-30a3fd9e88a0.png"),
            content_type: "image/png",
        }),
        "Hungary-05087255cb00.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Hungary-05087255cb00.webp"),
            content_type: "image/webp",
        }),
        "Hungary-leader-275b3ae1a8ec.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Hungary-leader-275b3ae1a8ec.png"),
            content_type: "image/png",
        }),
        "Iceland-596ee2ad62a5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Iceland-596ee2ad62a5.webp"),
            content_type: "image/webp",
        }),
        "Iceland-leader-84b7f895d85f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Iceland-leader-84b7f895d85f.png"),
            content_type: "image/png",
        }),
        "India-262b7848a6c1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/India-262b7848a6c1.webp"),
            content_type: "image/webp",
        }),
        "India-leader-d2045da0dd8b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/India-leader-d2045da0dd8b.png"),
            content_type: "image/png",
        }),
        "Indonesia-b05c91d384ff.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Indonesia-b05c91d384ff.webp"),
            content_type: "image/webp",
        }),
        "Indonesia-leader-263c706699ed.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Indonesia-leader-263c706699ed.png"),
            content_type: "image/png",
        }),
        "Iran-2a433b6f832a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Iran-2a433b6f832a.webp"),
            content_type: "image/webp",
        }),
        "Iran-leader-ec534fac151c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Iran-leader-ec534fac151c.png"),
            content_type: "image/png",
        }),
        "Iraq-703752196158.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Iraq-703752196158.webp"),
            content_type: "image/webp",
        }),
        "Iraq-leader-caf35a654595.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Iraq-leader-caf35a654595.png"),
            content_type: "image/png",
        }),
        "Ireland-951a29fd9759.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Ireland-951a29fd9759.webp"),
            content_type: "image/webp",
        }),
        "Ireland-leader-3fd7b6772f15.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Ireland-leader-3fd7b6772f15.png"),
            content_type: "image/png",
        }),
        "Israel-694f2fc34915.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Israel-694f2fc34915.webp"),
            content_type: "image/webp",
        }),
        "Israel-leader-adeb621a7630.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Israel-leader-adeb621a7630.png"),
            content_type: "image/png",
        }),
        "Italy-490fd77a886a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Italy-490fd77a886a.webp"),
            content_type: "image/webp",
        }),
        "Italy-leader-43d2007c1cf4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Italy-leader-43d2007c1cf4.png"),
            content_type: "image/png",
        }),
        "Jamaica-d2ad974f38b6.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Jamaica-d2ad974f38b6.webp"),
            content_type: "image/webp",
        }),
        "Jamaica-leader-f23541a20f37.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Jamaica-leader-f23541a20f37.png"),
            content_type: "image/png",
        }),
        "Japan-ce625f760d02.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Japan-ce625f760d02.webp"),
            content_type: "image/webp",
        }),
        "Japan-leader-e8f07cf89b13.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Japan-leader-e8f07cf89b13.png"),
            content_type: "image/png",
        }),
        "Jordan-c34f095391d1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Jordan-c34f095391d1.webp"),
            content_type: "image/webp",
        }),
        "Jordan-leader-ff0d08eac2bb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Jordan-leader-ff0d08eac2bb.png"),
            content_type: "image/png",
        }),
        "Kazakhstan-4da7e6dcc5ce.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Kazakhstan-4da7e6dcc5ce.webp"),
            content_type: "image/webp",
        }),
        "Kazakhstan-leader-2ee19cb92075.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Kazakhstan-leader-2ee19cb92075.png"),
            content_type: "image/png",
        }),
        "Kenya-9808bce561b8.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Kenya-9808bce561b8.webp"),
            content_type: "image/webp",
        }),
        "Kenya-leader-fcd01befb37f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Kenya-leader-fcd01befb37f.png"),
            content_type: "image/png",
        }),
        "Kuwait-1312e894a527.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Kuwait-1312e894a527.webp"),
            content_type: "image/webp",
        }),
        "Kuwait-leader-53e78d23f848.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Kuwait-leader-53e78d23f848.png"),
            content_type: "image/png",
        }),
        "Kyrgyzstan-f11115fe3b50.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Kyrgyzstan-f11115fe3b50.webp"),
            content_type: "image/webp",
        }),
        "Kyrgyzstan-leader-f955e90d88bf.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Kyrgyzstan-leader-f955e90d88bf.png"),
            content_type: "image/png",
        }),
        "Laos-d9171488de98.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Laos-d9171488de98.webp"),
            content_type: "image/webp",
        }),
        "Laos-leader-c006e05428e8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Laos-leader-c006e05428e8.png"),
            content_type: "image/png",
        }),
        "Latvia-2af3992e0329.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Latvia-2af3992e0329.webp"),
            content_type: "image/webp",
        }),
        "Latvia-leader-945f3683ace4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Latvia-leader-945f3683ace4.png"),
            content_type: "image/png",
        }),
        "Lebanon-5ac96440fd0a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Lebanon-5ac96440fd0a.webp"),
            content_type: "image/webp",
        }),
        "Lebanon-leader-daa1bdfcdd35.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Lebanon-leader-daa1bdfcdd35.png"),
            content_type: "image/png",
        }),
        "Lesotho-f84b8249569d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Lesotho-f84b8249569d.webp"),
            content_type: "image/webp",
        }),
        "Lesotho-leader-25fb37ce645c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Lesotho-leader-25fb37ce645c.png"),
            content_type: "image/png",
        }),
        "Libya-30d504bf7617.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Libya-30d504bf7617.webp"),
            content_type: "image/webp",
        }),
        "Libya-leader-84e7af913b21.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Libya-leader-84e7af913b21.png"),
            content_type: "image/png",
        }),
        "Lithuania-d0da5887380a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Lithuania-d0da5887380a.webp"),
            content_type: "image/webp",
        }),
        "Lithuania-leader-b3a8a7f8813e.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Lithuania-leader-b3a8a7f8813e.png"),
            content_type: "image/png",
        }),
        "Luxembourg-3df6ae969f9e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Luxembourg-3df6ae969f9e.webp"),
            content_type: "image/webp",
        }),
        "Luxembourg-leader-0f084bf6b375.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Luxembourg-leader-0f084bf6b375.png"),
            content_type: "image/png",
        }),
        "Macedonia-b885c99f5cdc.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Macedonia-b885c99f5cdc.webp"),
            content_type: "image/webp",
        }),
        "Macedonia-leader-e5e39a810e5d.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Macedonia-leader-e5e39a810e5d.png"),
            content_type: "image/png",
        }),
        "Madagascar-6bfdb03d052d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Madagascar-6bfdb03d052d.webp"),
            content_type: "image/webp",
        }),
        "Madagascar-leader-49a878ed910e.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Madagascar-leader-49a878ed910e.png"),
            content_type: "image/png",
        }),
        "Malawi-3ea5ca1b10e1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Malawi-3ea5ca1b10e1.webp"),
            content_type: "image/webp",
        }),
        "Malawi-leader-9918ee88e318.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Malawi-leader-9918ee88e318.png"),
            content_type: "image/png",
        }),
        "Malaysia-c8b5e83391aa.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Malaysia-c8b5e83391aa.webp"),
            content_type: "image/webp",
        }),
        "Malaysia-leader-ebc5fabaddf2.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Malaysia-leader-ebc5fabaddf2.png"),
            content_type: "image/png",
        }),
        "Maldives-fb6d44c5c534.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Maldives-fb6d44c5c534.webp"),
            content_type: "image/webp",
        }),
        "Maldives-leader-4a0dbdafbfb5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Maldives-leader-4a0dbdafbfb5.png"),
            content_type: "image/png",
        }),
        "Malta-leader-7eee9b6631a2.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Malta-leader-7eee9b6631a2.png"),
            content_type: "image/png",
        }),
        "Mauritius-be395bdefbe3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Mauritius-be395bdefbe3.webp"),
            content_type: "image/webp",
        }),
        "Mauritius-leader-141599545a72.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Mauritius-leader-141599545a72.png"),
            content_type: "image/png",
        }),
        "Mexico-8030c7281e1b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Mexico-8030c7281e1b.webp"),
            content_type: "image/webp",
        }),
        "Mexico-leader-61c5830fa230.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Mexico-leader-61c5830fa230.png"),
            content_type: "image/png",
        }),
        "Moldova-0199410bd728.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Moldova-0199410bd728.webp"),
            content_type: "image/webp",
        }),
        "Moldova-leader-b3efadfbaee6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Moldova-leader-b3efadfbaee6.png"),
            content_type: "image/png",
        }),
        "Mongolia-f3c139ce91ca.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Mongolia-f3c139ce91ca.webp"),
            content_type: "image/webp",
        }),
        "Mongolia-leader-9b7faaf35c88.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Mongolia-leader-9b7faaf35c88.png"),
            content_type: "image/png",
        }),
        "Montenegro-393df428fe2e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Montenegro-393df428fe2e.webp"),
            content_type: "image/webp",
        }),
        "Montenegro-leader-b0ab96c2fd44.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Montenegro-leader-b0ab96c2fd44.png"),
            content_type: "image/png",
        }),
        "Morocco-50c11f9dd586.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Morocco-50c11f9dd586.webp"),
            content_type: "image/webp",
        }),
        "Morocco-leader-b7d54d4363c6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Morocco-leader-b7d54d4363c6.png"),
            content_type: "image/png",
        }),
        "Mozambique-d91375a47ed5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Mozambique-d91375a47ed5.webp"),
            content_type: "image/webp",
        }),
        "Mozambique-leader-9ae0fab19167.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Mozambique-leader-9ae0fab19167.png"),
            content_type: "image/png",
        }),
        "Myanmar-6422b1cada0e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Myanmar-6422b1cada0e.webp"),
            content_type: "image/webp",
        }),
        "Myanmar-leader-8ab70720325f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Myanmar-leader-8ab70720325f.png"),
            content_type: "image/png",
        }),
        "Namibia-becf3dbb0829.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Namibia-becf3dbb0829.webp"),
            content_type: "image/webp",
        }),
        "Namibia-leader-8ed44252fafd.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Namibia-leader-8ed44252fafd.png"),
            content_type: "image/png",
        }),
        "Nepal-667c97815649.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Nepal-667c97815649.webp"),
            content_type: "image/webp",
        }),
        "Nepal-leader-b34225e7a67d.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Nepal-leader-b34225e7a67d.png"),
            content_type: "image/png",
        }),
        "Netherlands-2c3fb66f19be.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Netherlands-2c3fb66f19be.webp"),
            content_type: "image/webp",
        }),
        "Netherlands-leader-767f75c73e9f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Netherlands-leader-767f75c73e9f.png"),
            content_type: "image/png",
        }),
        "NewZealand-931ef513b810.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/NewZealand-931ef513b810.webp"),
            content_type: "image/webp",
        }),
        "NewZealand-leader-e01a6f19ff24.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/NewZealand-leader-e01a6f19ff24.png"),
            content_type: "image/png",
        }),
        "Nicaragua-c696d20a1e21.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Nicaragua-c696d20a1e21.webp"),
            content_type: "image/webp",
        }),
        "Nicaragua-leader-d759757dd883.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Nicaragua-leader-d759757dd883.png"),
            content_type: "image/png",
        }),
        "Nigeria-4ad4d17426a5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Nigeria-4ad4d17426a5.webp"),
            content_type: "image/webp",
        }),
        "Nigeria-leader-47783b146ea5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Nigeria-leader-47783b146ea5.png"),
            content_type: "image/png",
        }),
        "NorthKorea-ada9424cc241.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/NorthKorea-ada9424cc241.webp"),
            content_type: "image/webp",
        }),
        "NorthKorea-leader-6e8f560c6d32.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/NorthKorea-leader-6e8f560c6d32.png"),
            content_type: "image/png",
        }),
        "Norway-leader-69d39eb268ea.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Norway-leader-69d39eb268ea.png"),
            content_type: "image/png",
        }),
        "Oman-leader-9ed97b2ff48a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Oman-leader-9ed97b2ff48a.png"),
            content_type: "image/png",
        }),
        "Pakistan-leader-3ddd4356bc37.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Pakistan-leader-3ddd4356bc37.png"),
            content_type: "image/png",
        }),
        "Panama-0bd09f557ac9.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Panama-0bd09f557ac9.webp"),
            content_type: "image/webp",
        }),
        "Panama-leader-c656f5adb5c8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Panama-leader-c656f5adb5c8.png"),
            content_type: "image/png",
        }),
        "PapuaNewGuinea-2798c565d3bc.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/PapuaNewGuinea-2798c565d3bc.webp"),
            content_type: "image/webp",
        }),
        "PapuaNewGuinea-leader-182b40264e85.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/PapuaNewGuinea-leader-182b40264e85.png"),
            content_type: "image/png",
        }),
        "Paraguay-8f6ca0d5b95f.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Paraguay-8f6ca0d5b95f.webp"),
            content_type: "image/webp",
        }),
        "Paraguay-leader-e9dd37d369c0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Paraguay-leader-e9dd37d369c0.png"),
            content_type: "image/png",
        }),
        "Peru-2760db6ca168.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Peru-2760db6ca168.webp"),
            content_type: "image/webp",
        }),
        "Peru-leader-b8a168df7dd2.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Peru-leader-b8a168df7dd2.png"),
            content_type: "image/png",
        }),
        "Philippines-09d6fa43d875.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Philippines-09d6fa43d875.webp"),
            content_type: "image/webp",
        }),
        "Philippines-leader-28d07dd2fac6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Philippines-leader-28d07dd2fac6.png"),
            content_type: "image/png",
        }),
        "Poland-1b4ccc3cc292.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Poland-1b4ccc3cc292.webp"),
            content_type: "image/webp",
        }),
        "Poland-leader-312bcf73faff.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Poland-leader-312bcf73faff.png"),
            content_type: "image/png",
        }),
        "Portugal-leader-4976924da894.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Portugal-leader-4976924da894.png"),
            content_type: "image/png",
        }),
        "Qatar-d30b81d6d372.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Qatar-d30b81d6d372.webp"),
            content_type: "image/webp",
        }),
        "Qatar-leader-6b7135cc0429.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Qatar-leader-6b7135cc0429.png"),
            content_type: "image/png",
        }),
        "Romania-dc48f86150b3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Romania-dc48f86150b3.webp"),
            content_type: "image/webp",
        }),
        "Romania-leader-1c1b3769bef0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Romania-leader-1c1b3769bef0.png"),
            content_type: "image/png",
        }),
        "Russia-88e3be89087e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Russia-88e3be89087e.webp"),
            content_type: "image/webp",
        }),
        "Russia-leader-ad7dbb51ac3c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Russia-leader-ad7dbb51ac3c.png"),
            content_type: "image/png",
        }),
        "Samoa-a54b8284cdc9.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Samoa-a54b8284cdc9.webp"),
            content_type: "image/webp",
        }),
        "Samoa-leader-baecf0adbf80.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Samoa-leader-baecf0adbf80.png"),
            content_type: "image/png",
        }),
        "SaoTome-c221ea95d0d2.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/SaoTome-c221ea95d0d2.webp"),
            content_type: "image/webp",
        }),
        "SaoTome-leader-dfdec363be04.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/SaoTome-leader-dfdec363be04.png"),
            content_type: "image/png",
        }),
        "SaudiArabia-1417bf694248.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/SaudiArabia-1417bf694248.webp"),
            content_type: "image/webp",
        }),
        "SaudiArabia-leader-b3eaa313d3eb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/SaudiArabia-leader-b3eaa313d3eb.png"),
            content_type: "image/png",
        }),
        "Senegal-leader-180cd0430468.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Senegal-leader-180cd0430468.png"),
            content_type: "image/png",
        }),
        "Serbia-73b42d727616.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Serbia-73b42d727616.webp"),
            content_type: "image/webp",
        }),
        "Serbia-leader-4836d1e82b2d.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Serbia-leader-4836d1e82b2d.png"),
            content_type: "image/png",
        }),
        "Seychelles-19f784374d49.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Seychelles-19f784374d49.webp"),
            content_type: "image/webp",
        }),
        "Seychelles-leader-ebb53369343e.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Seychelles-leader-ebb53369343e.png"),
            content_type: "image/png",
        }),
        "Singapore-3c48d2fb2f7a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Singapore-3c48d2fb2f7a.webp"),
            content_type: "image/webp",
        }),
        "Singapore-leader-666c2be14c86.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Singapore-leader-666c2be14c86.png"),
            content_type: "image/png",
        }),
        "Slovenia-1a6852c763e8.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Slovenia-1a6852c763e8.webp"),
            content_type: "image/webp",
        }),
        "Slovenia-leader-73f1f980568a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Slovenia-leader-73f1f980568a.png"),
            content_type: "image/png",
        }),
        "SolomonIslands-f492155d4a4e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/SolomonIslands-f492155d4a4e.webp"),
            content_type: "image/webp",
        }),
        "SolomonIslands-leader-1faf4b1461be.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/SolomonIslands-leader-1faf4b1461be.png"),
            content_type: "image/png",
        }),
        "SouthAfrica-c18b98eb769d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/SouthAfrica-c18b98eb769d.webp"),
            content_type: "image/webp",
        }),
        "SouthAfrica-leader-570b0edbc6e0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/SouthAfrica-leader-570b0edbc6e0.png"),
            content_type: "image/png",
        }),
        "SouthKorea-leader-fb75ff77f7ab.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/SouthKorea-leader-fb75ff77f7ab.png"),
            content_type: "image/png",
        }),
        "Spain-1ab13145c12d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Spain-1ab13145c12d.webp"),
            content_type: "image/webp",
        }),
        "Spain-leader-f6d1802b79b0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Spain-leader-f6d1802b79b0.png"),
            content_type: "image/png",
        }),
        "SriLanka-3d12f3f83446.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/SriLanka-3d12f3f83446.webp"),
            content_type: "image/webp",
        }),
        "SriLanka-leader-cd991ccd12b6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/SriLanka-leader-cd991ccd12b6.png"),
            content_type: "image/png",
        }),
        "Sudan-db01b56e2028.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Sudan-db01b56e2028.webp"),
            content_type: "image/webp",
        }),
        "Sudan-leader-7f6cd05d6b53.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Sudan-leader-7f6cd05d6b53.png"),
            content_type: "image/png",
        }),
        "Suriname-57bb04414091.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Suriname-57bb04414091.webp"),
            content_type: "image/webp",
        }),
        "Suriname-leader-3a6b156d8479.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Suriname-leader-3a6b156d8479.png"),
            content_type: "image/png",
        }),
        "Swaziland-0cae5ee95b61.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Swaziland-0cae5ee95b61.webp"),
            content_type: "image/webp",
        }),
        "Swaziland-leader-2469fa3b99c5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Swaziland-leader-2469fa3b99c5.png"),
            content_type: "image/png",
        }),
        "Sweden-760e51a41b4d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Sweden-760e51a41b4d.webp"),
            content_type: "image/webp",
        }),
        "Sweden-leader-385b4a4784ac.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Sweden-leader-385b4a4784ac.png"),
            content_type: "image/png",
        }),
        "Switzerland-3830d79d0784.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Switzerland-3830d79d0784.webp"),
            content_type: "image/webp",
        }),
        "Switzerland-leader-ef1e6ee4b749.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Switzerland-leader-ef1e6ee4b749.png"),
            content_type: "image/png",
        }),
        "Syria-9b264fb10afb.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Syria-9b264fb10afb.webp"),
            content_type: "image/webp",
        }),
        "Syria-leader-30077fbc4bd5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Syria-leader-30077fbc4bd5.png"),
            content_type: "image/png",
        }),
        "Taiwan-d9eeaaad4764.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Taiwan-d9eeaaad4764.webp"),
            content_type: "image/webp",
        }),
        "Taiwan-leader-753218d3b9ac.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Taiwan-leader-753218d3b9ac.png"),
            content_type: "image/png",
        }),
        "Tajikistan-1156e86fce5c.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Tajikistan-1156e86fce5c.webp"),
            content_type: "image/webp",
        }),
        "Tajikistan-leader-ec3e76b96f01.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Tajikistan-leader-ec3e76b96f01.png"),
            content_type: "image/png",
        }),
        "Tanzania-1b3df45b8711.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Tanzania-1b3df45b8711.webp"),
            content_type: "image/webp",
        }),
        "Tanzania-leader-c7a9ad34bc38.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Tanzania-leader-c7a9ad34bc38.png"),
            content_type: "image/png",
        }),
        "Thailand-1eab1b0aca79.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Thailand-1eab1b0aca79.webp"),
            content_type: "image/webp",
        }),
        "Thailand-leader-5053f1afa592.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Thailand-leader-5053f1afa592.png"),
            content_type: "image/png",
        }),
        "Tonga-136734790809.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Tonga-136734790809.webp"),
            content_type: "image/webp",
        }),
        "Tonga-leader-ebd2ff6c883c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Tonga-leader-ebd2ff6c883c.png"),
            content_type: "image/png",
        }),
        "TrinidadTobago-c573490695f6.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/TrinidadTobago-c573490695f6.webp"),
            content_type: "image/webp",
        }),
        "TrinidadTobago-leader-70f9c5d60065.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/TrinidadTobago-leader-70f9c5d60065.png"),
            content_type: "image/png",
        }),
        "Tunisia-e2d49284c1a1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Tunisia-e2d49284c1a1.webp"),
            content_type: "image/webp",
        }),
        "Tunisia-leader-9be2b3bf8d5b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Tunisia-leader-9be2b3bf8d5b.png"),
            content_type: "image/png",
        }),
        "Turkey-e0af9dc12d8b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Turkey-e0af9dc12d8b.webp"),
            content_type: "image/webp",
        }),
        "Turkey-leader-b46e149456ba.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Turkey-leader-b46e149456ba.png"),
            content_type: "image/png",
        }),
        "Turkmenistan-f38dab11ceb5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Turkmenistan-f38dab11ceb5.webp"),
            content_type: "image/webp",
        }),
        "Turkmenistan-leader-2d172c1ea313.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Turkmenistan-leader-2d172c1ea313.png"),
            content_type: "image/png",
        }),
        "UAE-d1d72d5a5940.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/UAE-d1d72d5a5940.webp"),
            content_type: "image/webp",
        }),
        "UAE-leader-398bef13e65f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/UAE-leader-398bef13e65f.png"),
            content_type: "image/png",
        }),
        "UK-3720e6545ca3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/UK-3720e6545ca3.webp"),
            content_type: "image/webp",
        }),
        "UK-leader-005a2e5a6961.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/UK-leader-005a2e5a6961.png"),
            content_type: "image/png",
        }),
        "USA-d924827d2a14.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/USA-d924827d2a14.webp"),
            content_type: "image/webp",
        }),
        "USA-leader-088ed05335f8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/USA-leader-088ed05335f8.png"),
            content_type: "image/png",
        }),
        "USSR-c09819e723d7.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/USSR-c09819e723d7.webp"),
            content_type: "image/webp",
        }),
        "USSR-leader-c1d33087b77c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/USSR-leader-c1d33087b77c.png"),
            content_type: "image/png",
        }),
        "Uganda-2576e6893d89.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Uganda-2576e6893d89.webp"),
            content_type: "image/webp",
        }),
        "Uganda-leader-d587a43edd3e.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Uganda-leader-d587a43edd3e.png"),
            content_type: "image/png",
        }),
        "Ukraine-a39df9937284.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Ukraine-a39df9937284.webp"),
            content_type: "image/webp",
        }),
        "Ukraine-leader-082df7061021.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Ukraine-leader-082df7061021.png"),
            content_type: "image/png",
        }),
        "Uruguay-1d8e52189e41.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Uruguay-1d8e52189e41.webp"),
            content_type: "image/webp",
        }),
        "Uruguay-leader-70e88aba2989.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Uruguay-leader-70e88aba2989.png"),
            content_type: "image/png",
        }),
        "Uzbekistan-leader-58202dfd8fa7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Uzbekistan-leader-58202dfd8fa7.png"),
            content_type: "image/png",
        }),
        "Vanuatu-leader-ae09d4392d40.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Vanuatu-leader-ae09d4392d40.png"),
            content_type: "image/png",
        }),
        "Venezuela-c3df9d921292.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Venezuela-c3df9d921292.webp"),
            content_type: "image/webp",
        }),
        "Venezuela-leader-78680e6c23db.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Venezuela-leader-78680e6c23db.png"),
            content_type: "image/png",
        }),
        "Vietnam-a2596dee0d3b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Vietnam-a2596dee0d3b.webp"),
            content_type: "image/webp",
        }),
        "Vietnam-leader-e5a8a54d6af6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Vietnam-leader-e5a8a54d6af6.png"),
            content_type: "image/png",
        }),
        "Yemen-efe87b865b08.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Yemen-efe87b865b08.webp"),
            content_type: "image/webp",
        }),
        "Yemen-leader-bb56b66ff38a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Yemen-leader-bb56b66ff38a.png"),
            content_type: "image/png",
        }),
        "Yugoslavia-d1380837e251.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Yugoslavia-d1380837e251.webp"),
            content_type: "image/webp",
        }),
        "Yugoslavia-leader-a3e9ec5c2120.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Yugoslavia-leader-a3e9ec5c2120.png"),
            content_type: "image/png",
        }),
        "Zaire-0beb18820b9d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Zaire-0beb18820b9d.webp"),
            content_type: "image/webp",
        }),
        "Zaire-leader-493de7626ad5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Zaire-leader-493de7626ad5.png"),
            content_type: "image/png",
        }),
        "Zambia-21d2515a9266.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Zambia-21d2515a9266.webp"),
            content_type: "image/webp",
        }),
        "Zambia-leader-039752d11c9b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Zambia-leader-039752d11c9b.png"),
            content_type: "image/png",
        }),
        "Zimbabwe-7a24d023476b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/portraits/Zimbabwe-7a24d023476b.webp"),
            content_type: "image/webp",
        }),
        "Zimbabwe-leader-906af32af708.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/leader-art/Zimbabwe-leader-906af32af708.png"),
            content_type: "image/png",
        }),
        _ => None,
    }
}

#[allow(dead_code)]
pub const FILENAMES: &[&str] = &[
    "Afghanistan-fce177144639.webp",
    "Afghanistan-leader-f86caeb10c1d.png",
    "Albania-dc27557adba1.webp",
    "Albania-leader-903811fcd953.png",
    "Algeria-0b9c67b3580c.webp",
    "Algeria-leader-40fd7af2f732.png",
    "Angola-leader-f4e74b240157.png",
    "Argentina-b91623db6af3.webp",
    "Argentina-leader-a101d5f078a3.png",
    "Armenia-a368e4ff55d1.webp",
    "Armenia-leader-ca833833a698.png",
    "Australia-leader-f55526a0d34c.png",
    "Austria-8654c9cef838.webp",
    "Austria-leader-df62375be251.png",
    "Azerbaijan-2f640fd15e9b.webp",
    "Azerbaijan-leader-5c9cd794afa1.png",
    "Bahamas-1c8efdb481a3.webp",
    "Bahamas-leader-8572851d48cb.png",
    "Bahrain-948f22793ce8.webp",
    "Bahrain-leader-85ca829f1fb7.png",
    "Bangladesh-c46c7660231d.webp",
    "Bangladesh-leader-22739f7701b4.png",
    "Belarus-30cc563e5afb.webp",
    "Belarus-leader-c9f31ded4c1a.png",
    "Belgium-leader-e9b24afba072.png",
    "Belize-leader-3228c097c1df.png",
    "Bhutan-ae31c54f2ad4.webp",
    "Bhutan-leader-b2cf694ebed0.png",
    "Bolivia-bba86fa3bff1.webp",
    "Bolivia-leader-2ea566d44234.png",
    "Bosnia-cca8507f915e.webp",
    "Bosnia-leader-e78227c3f1b4.png",
    "Botswana-6957bece838d.webp",
    "Botswana-leader-1bd3e888ee42.png",
    "Brazil-dd81b9e75b6c.webp",
    "Brazil-leader-d0f6f3b52a10.png",
    "Brunei-148342c02d15.webp",
    "Brunei-leader-740096a4e925.png",
    "Bulgaria-673e684ff947.webp",
    "Bulgaria-leader-df60ef4ca603.png",
    "Cambodia-1fef6e1ef9b7.webp",
    "Cambodia-leader-36a4db761f64.png",
    "Cameroon-bd66e3ef1a63.webp",
    "Cameroon-leader-fbdadb6d80fa.png",
    "Canada-e1b5c394ad55.webp",
    "Canada-leader-5e8ec77bcd18.png",
    "CapeVerde-4436e5afadf5.webp",
    "CapeVerde-leader-35a141178c3b.png",
    "CentralAfricanRepublic-d2777cd71eeb.webp",
    "CentralAfricanRepublic-leader-c57ccb06fdc7.png",
    "Chad-leader-4bc000d7aee9.png",
    "Chile-8ca8a4c797a3.webp",
    "Chile-leader-ee0b701ecc5a.png",
    "China-a8ba380d17c6.webp",
    "China-leader-350f76603ff5.png",
    "Colombia-8857df09c470.webp",
    "Colombia-leader-b33336138ce5.png",
    "Comoros-leader-0cbc3b8182b8.png",
    "Congo-11dca3605869.webp",
    "Congo-leader-e306732110d9.png",
    "CostaRica-eabce8094e78.webp",
    "CostaRica-leader-99717561cd37.png",
    "Croatia-40e31abb08ec.webp",
    "Croatia-leader-a02aa5a96157.png",
    "Cuba-ec84e0920b43.webp",
    "Cuba-leader-72a2d0148fef.png",
    "Cyprus-739821002edf.webp",
    "Cyprus-leader-554396a51feb.png",
    "Czechoslovakia-d2402dd13b8d.webp",
    "Czechoslovakia-leader-9fca0a08f5ca.png",
    "Denmark-1d8d01f03ea7.webp",
    "Denmark-leader-7db97be7511b.png",
    "DominicanRepublic-f876ab0536fd.webp",
    "DominicanRepublic-leader-338e895731fa.png",
    "EastTimor-803175d13879.webp",
    "EastTimor-leader-f1dd388f69b7.png",
    "Ecuador-625d480e50f7.webp",
    "Ecuador-leader-a83ed4f7cde5.png",
    "Egypt-9002995e92ea.webp",
    "Egypt-leader-a9767e906d23.png",
    "ElSalvador-3f5bddcbf46c.webp",
    "ElSalvador-leader-106251a76796.png",
    "EquatorialGuinea-5fbe4aec0a0a.webp",
    "EquatorialGuinea-leader-3709a2e9b864.png",
    "Estonia-eefc03c6692e.webp",
    "Estonia-leader-d7c769b9b9c7.png",
    "Ethiopia-a078474d6dc1.webp",
    "Ethiopia-leader-cab15e7748e8.png",
    "Fiji-e526b1a13c3a.webp",
    "Fiji-leader-c636a3f231f6.png",
    "Finland-85477212a438.webp",
    "Finland-leader-0a2cdb94da79.png",
    "France-fcd6b90d4338.webp",
    "France-leader-45efa5125248.png",
    "Gabon-leader-a07a1ecd636f.png",
    "Georgia-616c410a0127.webp",
    "Georgia-leader-a68f4b0660b0.png",
    "Germany-leader-82e3ff0675fe.png",
    "Ghana-1c298c7d5d5a.webp",
    "Ghana-leader-2ccab2063dd4.png",
    "Greece-8630f8dc9e62.webp",
    "Greece-leader-63df4fe43beb.png",
    "Guatemala-b4499f3121d1.webp",
    "Guatemala-leader-ad689e066275.png",
    "Guyana-d84ea0bada0e.webp",
    "Guyana-leader-38003ef82d27.png",
    "Haiti-17fd6a98fbd3.webp",
    "Haiti-leader-e5fe31935f13.png",
    "Honduras-f9e7b2b05ab5.webp",
    "Honduras-leader-30a3fd9e88a0.png",
    "Hungary-05087255cb00.webp",
    "Hungary-leader-275b3ae1a8ec.png",
    "Iceland-596ee2ad62a5.webp",
    "Iceland-leader-84b7f895d85f.png",
    "India-262b7848a6c1.webp",
    "India-leader-d2045da0dd8b.png",
    "Indonesia-b05c91d384ff.webp",
    "Indonesia-leader-263c706699ed.png",
    "Iran-2a433b6f832a.webp",
    "Iran-leader-ec534fac151c.png",
    "Iraq-703752196158.webp",
    "Iraq-leader-caf35a654595.png",
    "Ireland-951a29fd9759.webp",
    "Ireland-leader-3fd7b6772f15.png",
    "Israel-694f2fc34915.webp",
    "Israel-leader-adeb621a7630.png",
    "Italy-490fd77a886a.webp",
    "Italy-leader-43d2007c1cf4.png",
    "Jamaica-d2ad974f38b6.webp",
    "Jamaica-leader-f23541a20f37.png",
    "Japan-ce625f760d02.webp",
    "Japan-leader-e8f07cf89b13.png",
    "Jordan-c34f095391d1.webp",
    "Jordan-leader-ff0d08eac2bb.png",
    "Kazakhstan-4da7e6dcc5ce.webp",
    "Kazakhstan-leader-2ee19cb92075.png",
    "Kenya-9808bce561b8.webp",
    "Kenya-leader-fcd01befb37f.png",
    "Kuwait-1312e894a527.webp",
    "Kuwait-leader-53e78d23f848.png",
    "Kyrgyzstan-f11115fe3b50.webp",
    "Kyrgyzstan-leader-f955e90d88bf.png",
    "Laos-d9171488de98.webp",
    "Laos-leader-c006e05428e8.png",
    "Latvia-2af3992e0329.webp",
    "Latvia-leader-945f3683ace4.png",
    "Lebanon-5ac96440fd0a.webp",
    "Lebanon-leader-daa1bdfcdd35.png",
    "Lesotho-f84b8249569d.webp",
    "Lesotho-leader-25fb37ce645c.png",
    "Libya-30d504bf7617.webp",
    "Libya-leader-84e7af913b21.png",
    "Lithuania-d0da5887380a.webp",
    "Lithuania-leader-b3a8a7f8813e.png",
    "Luxembourg-3df6ae969f9e.webp",
    "Luxembourg-leader-0f084bf6b375.png",
    "Macedonia-b885c99f5cdc.webp",
    "Macedonia-leader-e5e39a810e5d.png",
    "Madagascar-6bfdb03d052d.webp",
    "Madagascar-leader-49a878ed910e.png",
    "Malawi-3ea5ca1b10e1.webp",
    "Malawi-leader-9918ee88e318.png",
    "Malaysia-c8b5e83391aa.webp",
    "Malaysia-leader-ebc5fabaddf2.png",
    "Maldives-fb6d44c5c534.webp",
    "Maldives-leader-4a0dbdafbfb5.png",
    "Malta-leader-7eee9b6631a2.png",
    "Mauritius-be395bdefbe3.webp",
    "Mauritius-leader-141599545a72.png",
    "Mexico-8030c7281e1b.webp",
    "Mexico-leader-61c5830fa230.png",
    "Moldova-0199410bd728.webp",
    "Moldova-leader-b3efadfbaee6.png",
    "Mongolia-f3c139ce91ca.webp",
    "Mongolia-leader-9b7faaf35c88.png",
    "Montenegro-393df428fe2e.webp",
    "Montenegro-leader-b0ab96c2fd44.png",
    "Morocco-50c11f9dd586.webp",
    "Morocco-leader-b7d54d4363c6.png",
    "Mozambique-d91375a47ed5.webp",
    "Mozambique-leader-9ae0fab19167.png",
    "Myanmar-6422b1cada0e.webp",
    "Myanmar-leader-8ab70720325f.png",
    "Namibia-becf3dbb0829.webp",
    "Namibia-leader-8ed44252fafd.png",
    "Nepal-667c97815649.webp",
    "Nepal-leader-b34225e7a67d.png",
    "Netherlands-2c3fb66f19be.webp",
    "Netherlands-leader-767f75c73e9f.png",
    "NewZealand-931ef513b810.webp",
    "NewZealand-leader-e01a6f19ff24.png",
    "Nicaragua-c696d20a1e21.webp",
    "Nicaragua-leader-d759757dd883.png",
    "Nigeria-4ad4d17426a5.webp",
    "Nigeria-leader-47783b146ea5.png",
    "NorthKorea-ada9424cc241.webp",
    "NorthKorea-leader-6e8f560c6d32.png",
    "Norway-leader-69d39eb268ea.png",
    "Oman-leader-9ed97b2ff48a.png",
    "Pakistan-leader-3ddd4356bc37.png",
    "Panama-0bd09f557ac9.webp",
    "Panama-leader-c656f5adb5c8.png",
    "PapuaNewGuinea-2798c565d3bc.webp",
    "PapuaNewGuinea-leader-182b40264e85.png",
    "Paraguay-8f6ca0d5b95f.webp",
    "Paraguay-leader-e9dd37d369c0.png",
    "Peru-2760db6ca168.webp",
    "Peru-leader-b8a168df7dd2.png",
    "Philippines-09d6fa43d875.webp",
    "Philippines-leader-28d07dd2fac6.png",
    "Poland-1b4ccc3cc292.webp",
    "Poland-leader-312bcf73faff.png",
    "Portugal-leader-4976924da894.png",
    "Qatar-d30b81d6d372.webp",
    "Qatar-leader-6b7135cc0429.png",
    "Romania-dc48f86150b3.webp",
    "Romania-leader-1c1b3769bef0.png",
    "Russia-88e3be89087e.webp",
    "Russia-leader-ad7dbb51ac3c.png",
    "Samoa-a54b8284cdc9.webp",
    "Samoa-leader-baecf0adbf80.png",
    "SaoTome-c221ea95d0d2.webp",
    "SaoTome-leader-dfdec363be04.png",
    "SaudiArabia-1417bf694248.webp",
    "SaudiArabia-leader-b3eaa313d3eb.png",
    "Senegal-leader-180cd0430468.png",
    "Serbia-73b42d727616.webp",
    "Serbia-leader-4836d1e82b2d.png",
    "Seychelles-19f784374d49.webp",
    "Seychelles-leader-ebb53369343e.png",
    "Singapore-3c48d2fb2f7a.webp",
    "Singapore-leader-666c2be14c86.png",
    "Slovenia-1a6852c763e8.webp",
    "Slovenia-leader-73f1f980568a.png",
    "SolomonIslands-f492155d4a4e.webp",
    "SolomonIslands-leader-1faf4b1461be.png",
    "SouthAfrica-c18b98eb769d.webp",
    "SouthAfrica-leader-570b0edbc6e0.png",
    "SouthKorea-leader-fb75ff77f7ab.png",
    "Spain-1ab13145c12d.webp",
    "Spain-leader-f6d1802b79b0.png",
    "SriLanka-3d12f3f83446.webp",
    "SriLanka-leader-cd991ccd12b6.png",
    "Sudan-db01b56e2028.webp",
    "Sudan-leader-7f6cd05d6b53.png",
    "Suriname-57bb04414091.webp",
    "Suriname-leader-3a6b156d8479.png",
    "Swaziland-0cae5ee95b61.webp",
    "Swaziland-leader-2469fa3b99c5.png",
    "Sweden-760e51a41b4d.webp",
    "Sweden-leader-385b4a4784ac.png",
    "Switzerland-3830d79d0784.webp",
    "Switzerland-leader-ef1e6ee4b749.png",
    "Syria-9b264fb10afb.webp",
    "Syria-leader-30077fbc4bd5.png",
    "Taiwan-d9eeaaad4764.webp",
    "Taiwan-leader-753218d3b9ac.png",
    "Tajikistan-1156e86fce5c.webp",
    "Tajikistan-leader-ec3e76b96f01.png",
    "Tanzania-1b3df45b8711.webp",
    "Tanzania-leader-c7a9ad34bc38.png",
    "Thailand-1eab1b0aca79.webp",
    "Thailand-leader-5053f1afa592.png",
    "Tonga-136734790809.webp",
    "Tonga-leader-ebd2ff6c883c.png",
    "TrinidadTobago-c573490695f6.webp",
    "TrinidadTobago-leader-70f9c5d60065.png",
    "Tunisia-e2d49284c1a1.webp",
    "Tunisia-leader-9be2b3bf8d5b.png",
    "Turkey-e0af9dc12d8b.webp",
    "Turkey-leader-b46e149456ba.png",
    "Turkmenistan-f38dab11ceb5.webp",
    "Turkmenistan-leader-2d172c1ea313.png",
    "UAE-d1d72d5a5940.webp",
    "UAE-leader-398bef13e65f.png",
    "UK-3720e6545ca3.webp",
    "UK-leader-005a2e5a6961.png",
    "USA-d924827d2a14.webp",
    "USA-leader-088ed05335f8.png",
    "USSR-c09819e723d7.webp",
    "USSR-leader-c1d33087b77c.png",
    "Uganda-2576e6893d89.webp",
    "Uganda-leader-d587a43edd3e.png",
    "Ukraine-a39df9937284.webp",
    "Ukraine-leader-082df7061021.png",
    "Uruguay-1d8e52189e41.webp",
    "Uruguay-leader-70e88aba2989.png",
    "Uzbekistan-leader-58202dfd8fa7.png",
    "Vanuatu-leader-ae09d4392d40.png",
    "Venezuela-c3df9d921292.webp",
    "Venezuela-leader-78680e6c23db.png",
    "Vietnam-a2596dee0d3b.webp",
    "Vietnam-leader-e5a8a54d6af6.png",
    "Yemen-efe87b865b08.webp",
    "Yemen-leader-bb56b66ff38a.png",
    "Yugoslavia-d1380837e251.webp",
    "Yugoslavia-leader-a3e9ec5c2120.png",
    "Zaire-0beb18820b9d.webp",
    "Zaire-leader-493de7626ad5.png",
    "Zambia-21d2515a9266.webp",
    "Zambia-leader-039752d11c9b.png",
    "Zimbabwe-7a24d023476b.webp",
    "Zimbabwe-leader-906af32af708.png",
];
