//! Generated by tools/avatars/fetch_commons_portraits.py. Do not edit by hand.

pub struct PortraitAsset {
    pub bytes: &'static [u8],
    pub content_type: &'static str,
}

pub fn get(name: &str) -> Option<PortraitAsset> {
    match name {
        "Afghanistan-fce177144639.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Afghanistan-fce177144639-449fb60aaf667940.webp"),
            content_type: "image/webp",
        }),
        "Afghanistan-leader-f86caeb10c1d.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Afghanistan-d73dbdabd2409aab.webp"),
            content_type: "image/webp",
        }),
        "Albania-dc27557adba1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Albania-dc27557adba1-86e9cc05196b4b4e.webp"),
            content_type: "image/webp",
        }),
        "Albania-leader-903811fcd953.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Albania-bb7a779058608e01.webp"),
            content_type: "image/webp",
        }),
        "Algeria-0b9c67b3580c.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Algeria-0b9c67b3580c-5c379930e8cd5839.webp"),
            content_type: "image/webp",
        }),
        "Algeria-leader-40fd7af2f732.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Algeria-5f619f3fae54ec78.webp"),
            content_type: "image/webp",
        }),
        "Angola-leader-f4e74b240157.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Angola-0bd35020373b0592.webp"),
            content_type: "image/webp",
        }),
        "Argentina-b91623db6af3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Argentina-b91623db6af3-d7f811c59f37c48a.webp"),
            content_type: "image/webp",
        }),
        "Argentina-leader-a101d5f078a3.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Argentina-20530b8f0cb0b597.webp"),
            content_type: "image/webp",
        }),
        "Armenia-a368e4ff55d1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Armenia-a368e4ff55d1-34f03df8b18a06d2.webp"),
            content_type: "image/webp",
        }),
        "Armenia-leader-ca833833a698.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Armenia-21eb6efd51242161.webp"),
            content_type: "image/webp",
        }),
        "Australia-leader-f55526a0d34c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Australia-df7be195fadf5f33.webp"),
            content_type: "image/webp",
        }),
        "Austria-8654c9cef838.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Austria-8654c9cef838-7d100ce9c4ba8e8f.webp"),
            content_type: "image/webp",
        }),
        "Austria-leader-df62375be251.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Austria-8d5724e2b7574d0a.webp"),
            content_type: "image/webp",
        }),
        "Azerbaijan-2f640fd15e9b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Azerbaijan-2f640fd15e9b-97cf25227897f9bc.webp"),
            content_type: "image/webp",
        }),
        "Azerbaijan-leader-5c9cd794afa1.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Azerbaijan-3ba7b5990db0b70f.webp"),
            content_type: "image/webp",
        }),
        "Bahamas-1c8efdb481a3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bahamas-1c8efdb481a3-045b4891c5859228.webp"),
            content_type: "image/webp",
        }),
        "Bahamas-leader-8572851d48cb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bahamas-64cf448203c1eb58.webp"),
            content_type: "image/webp",
        }),
        "Bahrain-948f22793ce8.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bahrain-948f22793ce8-e0fe504fa33eb17d.webp"),
            content_type: "image/webp",
        }),
        "Bahrain-leader-85ca829f1fb7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bahrain-bf18c1dc179483d2.webp"),
            content_type: "image/webp",
        }),
        "Bangladesh-c46c7660231d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bangladesh-c46c7660231d-d39c58bec9b2b04d.webp"),
            content_type: "image/webp",
        }),
        "Bangladesh-leader-22739f7701b4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bangladesh-1214ebdd78d7791e.webp"),
            content_type: "image/webp",
        }),
        "Belarus-30cc563e5afb.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Belarus-30cc563e5afb-f527302e65e1bb6f.webp"),
            content_type: "image/webp",
        }),
        "Belarus-leader-c9f31ded4c1a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Belarus-4edfc8b89e4e6f0c.webp"),
            content_type: "image/webp",
        }),
        "Belgium-leader-e9b24afba072.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Belgium-da8bc444b041c993.webp"),
            content_type: "image/webp",
        }),
        "Belize-leader-3228c097c1df.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Belize-84462b8b0a3bf90b.webp"),
            content_type: "image/webp",
        }),
        "Bhutan-ae31c54f2ad4.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bhutan-ae31c54f2ad4-f10b7f2e1120c2f8.webp"),
            content_type: "image/webp",
        }),
        "Bhutan-leader-b2cf694ebed0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bhutan-fde56aadabb41935.webp"),
            content_type: "image/webp",
        }),
        "Bolivia-bba86fa3bff1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bolivia-bba86fa3bff1-2bfb6bfd7002d35b.webp"),
            content_type: "image/webp",
        }),
        "Bolivia-leader-2ea566d44234.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bolivia-a7a810f0f5d17085.webp"),
            content_type: "image/webp",
        }),
        "Bosnia-cca8507f915e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bosnia-cca8507f915e-0e73e55319b65a7e.webp"),
            content_type: "image/webp",
        }),
        "Bosnia-leader-e78227c3f1b4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bosnia-c9426b4369866744.webp"),
            content_type: "image/webp",
        }),
        "Botswana-6957bece838d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Botswana-6957bece838d-5e504ddcffe07c97.webp"),
            content_type: "image/webp",
        }),
        "Botswana-leader-1bd3e888ee42.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Botswana-84e56578988f121f.webp"),
            content_type: "image/webp",
        }),
        "Brazil-dd81b9e75b6c.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Brazil-dd81b9e75b6c-46d4204941eed3ca.webp"),
            content_type: "image/webp",
        }),
        "Brazil-leader-d0f6f3b52a10.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Brazil-5f7623b4dc6b0ad3.webp"),
            content_type: "image/webp",
        }),
        "Brunei-148342c02d15.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Brunei-148342c02d15-619a7398dfde03a5.webp"),
            content_type: "image/webp",
        }),
        "Brunei-leader-740096a4e925.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Brunei-db25b3020bbe582b.webp"),
            content_type: "image/webp",
        }),
        "Bulgaria-673e684ff947.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bulgaria-673e684ff947-78e1511e966c8011.webp"),
            content_type: "image/webp",
        }),
        "Bulgaria-leader-df60ef4ca603.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Bulgaria-19aa7094d744fb1e.webp"),
            content_type: "image/webp",
        }),
        "Cambodia-1fef6e1ef9b7.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Cambodia-1fef6e1ef9b7-87c7f04c2cd5253d.webp"),
            content_type: "image/webp",
        }),
        "Cambodia-leader-36a4db761f64.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Cambodia-ba838369344fb78c.webp"),
            content_type: "image/webp",
        }),
        "Cameroon-bd66e3ef1a63.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Cameroon-bd66e3ef1a63-3015c48edd46e1c9.webp"),
            content_type: "image/webp",
        }),
        "Cameroon-leader-fbdadb6d80fa.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Cameroon-fd5269db0f616cd9.webp"),
            content_type: "image/webp",
        }),
        "Canada-e1b5c394ad55.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Canada-e1b5c394ad55-9f41b8817c4309c8.webp"),
            content_type: "image/webp",
        }),
        "Canada-leader-5e8ec77bcd18.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Canada-12cda912f9d21e6a.webp"),
            content_type: "image/webp",
        }),
        "CapeVerde-4436e5afadf5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/CapeVerde-4436e5afadf5-9c63cc084446ecac.webp"),
            content_type: "image/webp",
        }),
        "CapeVerde-leader-35a141178c3b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/CapeVerde-e4bbd6f4a5b930da.webp"),
            content_type: "image/webp",
        }),
        "CentralAfricanRepublic-d2777cd71eeb.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/CentralAfricanRepublic-d2777cd71eeb-7da62031aef2387e.webp"),
            content_type: "image/webp",
        }),
        "CentralAfricanRepublic-leader-c57ccb06fdc7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/CentralAfricanRepublic-d43c385bd9fa8cc6.webp"),
            content_type: "image/webp",
        }),
        "Chad-leader-4bc000d7aee9.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Chad-746ea394ff0dc939.webp"),
            content_type: "image/webp",
        }),
        "Chile-8ca8a4c797a3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Chile-8ca8a4c797a3-852372c425eb2b73.webp"),
            content_type: "image/webp",
        }),
        "Chile-leader-ee0b701ecc5a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Chile-88bf5ef5204084bc.webp"),
            content_type: "image/webp",
        }),
        "China-a8ba380d17c6.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/China-a8ba380d17c6-33fc14341f5a0bdc.webp"),
            content_type: "image/webp",
        }),
        "China-leader-350f76603ff5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/China-62007abafde83376.webp"),
            content_type: "image/webp",
        }),
        "Colombia-8857df09c470.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Colombia-8857df09c470-b55bee84a9ade372.webp"),
            content_type: "image/webp",
        }),
        "Colombia-leader-b33336138ce5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Colombia-cbd8eb7d60611e88.webp"),
            content_type: "image/webp",
        }),
        "Comoros-leader-0cbc3b8182b8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Comoros-a46f68f00dc1bc2b.webp"),
            content_type: "image/webp",
        }),
        "Congo-11dca3605869.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Congo-11dca3605869-58d24cd665bb6064.webp"),
            content_type: "image/webp",
        }),
        "Congo-leader-e306732110d9.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Congo-3aac76373adc0928.webp"),
            content_type: "image/webp",
        }),
        "CostaRica-eabce8094e78.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/CostaRica-eabce8094e78-e43f77e797f86dd2.webp"),
            content_type: "image/webp",
        }),
        "CostaRica-leader-99717561cd37.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/CostaRica-19398c9da3880e2d.webp"),
            content_type: "image/webp",
        }),
        "Croatia-40e31abb08ec.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Croatia-40e31abb08ec-174fc97890e67f2e.webp"),
            content_type: "image/webp",
        }),
        "Croatia-leader-a02aa5a96157.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Croatia-67be22e17744b31f.webp"),
            content_type: "image/webp",
        }),
        "Cuba-ec84e0920b43.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Cuba-ec84e0920b43-cb9e50ddb00ae051.webp"),
            content_type: "image/webp",
        }),
        "Cuba-leader-72a2d0148fef.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Cuba-68f23dbb3cfd8a2b.webp"),
            content_type: "image/webp",
        }),
        "Cyprus-739821002edf.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Cyprus-739821002edf-13bfc1fbceac8199.webp"),
            content_type: "image/webp",
        }),
        "Cyprus-leader-554396a51feb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Cyprus-9efb439fa6a4d435.webp"),
            content_type: "image/webp",
        }),
        "Czechoslovakia-d2402dd13b8d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Czechoslovakia-d2402dd13b8d-e591cdd0fe5f3247.webp"),
            content_type: "image/webp",
        }),
        "Czechoslovakia-leader-9fca0a08f5ca.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Czechoslovakia-c20cba94f17f8b89.webp"),
            content_type: "image/webp",
        }),
        "Denmark-1d8d01f03ea7.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Denmark-1d8d01f03ea7-e0aea505e8b27bb6.webp"),
            content_type: "image/webp",
        }),
        "Denmark-leader-7db97be7511b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Denmark-8e9f1b50a15e12ab.webp"),
            content_type: "image/webp",
        }),
        "DominicanRepublic-f876ab0536fd.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/DominicanRepublic-f876ab0536fd-9946f61d53794a4d.webp"),
            content_type: "image/webp",
        }),
        "DominicanRepublic-leader-338e895731fa.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/DominicanRepublic-e8443834e8eacedf.webp"),
            content_type: "image/webp",
        }),
        "EastTimor-803175d13879.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/EastTimor-803175d13879-287465e006a04db2.webp"),
            content_type: "image/webp",
        }),
        "EastTimor-leader-f1dd388f69b7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/EastTimor-07f376a9a1eb7fa2.webp"),
            content_type: "image/webp",
        }),
        "Ecuador-625d480e50f7.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ecuador-625d480e50f7-77efa88a52637824.webp"),
            content_type: "image/webp",
        }),
        "Ecuador-leader-a83ed4f7cde5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ecuador-ce28cea48cbe9de3.webp"),
            content_type: "image/webp",
        }),
        "Egypt-9002995e92ea.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Egypt-9002995e92ea-9a14e8d66eba390e.webp"),
            content_type: "image/webp",
        }),
        "Egypt-leader-a9767e906d23.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Egypt-017eac0bf68b436d.webp"),
            content_type: "image/webp",
        }),
        "ElSalvador-3f5bddcbf46c.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/ElSalvador-3f5bddcbf46c-dfd4689f21a4448d.webp"),
            content_type: "image/webp",
        }),
        "ElSalvador-leader-106251a76796.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/ElSalvador-024338d759dbe17d.webp"),
            content_type: "image/webp",
        }),
        "EquatorialGuinea-5fbe4aec0a0a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/EquatorialGuinea-5fbe4aec0a0a-07f576f905195305.webp"),
            content_type: "image/webp",
        }),
        "EquatorialGuinea-leader-3709a2e9b864.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/EquatorialGuinea-b83978fc9f3cffb8.webp"),
            content_type: "image/webp",
        }),
        "Estonia-eefc03c6692e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Estonia-eefc03c6692e-5231b3ad22fc3072.webp"),
            content_type: "image/webp",
        }),
        "Estonia-leader-d7c769b9b9c7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Estonia-ddf349d0f61268cc.webp"),
            content_type: "image/webp",
        }),
        "Ethiopia-a078474d6dc1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ethiopia-a078474d6dc1-a959d038d9e4c9a6.webp"),
            content_type: "image/webp",
        }),
        "Ethiopia-leader-cab15e7748e8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ethiopia-863a3a40e8393cef.webp"),
            content_type: "image/webp",
        }),
        "Fiji-e526b1a13c3a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Fiji-e526b1a13c3a-e8aa41134fb88c16.webp"),
            content_type: "image/webp",
        }),
        "Fiji-leader-c636a3f231f6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Fiji-d4923ecd49d87d90.webp"),
            content_type: "image/webp",
        }),
        "Finland-85477212a438.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Finland-85477212a438-eecfb0c2a4058836.webp"),
            content_type: "image/webp",
        }),
        "Finland-leader-0a2cdb94da79.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Finland-365ecd22a9f4c10e.webp"),
            content_type: "image/webp",
        }),
        "France-fcd6b90d4338.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/France-fcd6b90d4338-11f8bda6311cd263.webp"),
            content_type: "image/webp",
        }),
        "France-leader-45efa5125248.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/France-e8fdabfb073a29fb.webp"),
            content_type: "image/webp",
        }),
        "Gabon-leader-a07a1ecd636f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Gabon-747658a7084af316.webp"),
            content_type: "image/webp",
        }),
        "Georgia-616c410a0127.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Georgia-616c410a0127-2f254005afeb95d8.webp"),
            content_type: "image/webp",
        }),
        "Georgia-leader-a68f4b0660b0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Georgia-1b8fad12cc5d8825.webp"),
            content_type: "image/webp",
        }),
        "Germany-leader-82e3ff0675fe.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Germany-947582041360653a.webp"),
            content_type: "image/webp",
        }),
        "Ghana-1c298c7d5d5a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ghana-1c298c7d5d5a-05d04ccde2d886d6.webp"),
            content_type: "image/webp",
        }),
        "Ghana-leader-2ccab2063dd4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ghana-3341185211ffba74.webp"),
            content_type: "image/webp",
        }),
        "Greece-8630f8dc9e62.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Greece-8630f8dc9e62-c1adcd9c805e4b19.webp"),
            content_type: "image/webp",
        }),
        "Greece-leader-63df4fe43beb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Greece-9a2b2a741170a1ed.webp"),
            content_type: "image/webp",
        }),
        "Guatemala-b4499f3121d1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Guatemala-b4499f3121d1-e44df6b2f114fd8c.webp"),
            content_type: "image/webp",
        }),
        "Guatemala-leader-ad689e066275.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Guatemala-d15a5bafa8b638f0.webp"),
            content_type: "image/webp",
        }),
        "Guyana-d84ea0bada0e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Guyana-d84ea0bada0e-5ba9edd3b8241d09.webp"),
            content_type: "image/webp",
        }),
        "Guyana-leader-38003ef82d27.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Guyana-e13dbd678186cd8b.webp"),
            content_type: "image/webp",
        }),
        "Haiti-17fd6a98fbd3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Haiti-17fd6a98fbd3-f75606035fcd3076.webp"),
            content_type: "image/webp",
        }),
        "Haiti-leader-e5fe31935f13.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Haiti-8baa1872d4d30a5e.webp"),
            content_type: "image/webp",
        }),
        "Honduras-f9e7b2b05ab5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Honduras-f9e7b2b05ab5-da634ad9b3176a30.webp"),
            content_type: "image/webp",
        }),
        "Honduras-leader-30a3fd9e88a0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Honduras-47af5ae422fab2a5.webp"),
            content_type: "image/webp",
        }),
        "Hungary-05087255cb00.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Hungary-05087255cb00-02e1289991a10b7b.webp"),
            content_type: "image/webp",
        }),
        "Hungary-leader-275b3ae1a8ec.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Hungary-534ba5200f63f886.webp"),
            content_type: "image/webp",
        }),
        "Iceland-596ee2ad62a5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Iceland-596ee2ad62a5-b2ec6ee66b277b55.webp"),
            content_type: "image/webp",
        }),
        "Iceland-leader-84b7f895d85f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Iceland-212af7d3d678a02a.webp"),
            content_type: "image/webp",
        }),
        "India-262b7848a6c1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/India-262b7848a6c1-b24ae29900457c32.webp"),
            content_type: "image/webp",
        }),
        "India-leader-d2045da0dd8b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/India-c428d848f111888e.webp"),
            content_type: "image/webp",
        }),
        "Indonesia-b05c91d384ff.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Indonesia-b05c91d384ff-99f2dcce6e75b5d9.webp"),
            content_type: "image/webp",
        }),
        "Indonesia-leader-263c706699ed.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Indonesia-f81450c2ed509700.webp"),
            content_type: "image/webp",
        }),
        "Iran-2a433b6f832a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Iran-2a433b6f832a-867c66e74aacaed0.webp"),
            content_type: "image/webp",
        }),
        "Iran-leader-ec534fac151c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Iran-35fb645a35d18eb2.webp"),
            content_type: "image/webp",
        }),
        "Iraq-703752196158.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Iraq-703752196158-06b6cfc536a84438.webp"),
            content_type: "image/webp",
        }),
        "Iraq-leader-caf35a654595.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Iraq-b81fd504d5237a74.webp"),
            content_type: "image/webp",
        }),
        "Ireland-951a29fd9759.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ireland-951a29fd9759-eb0dffca5c902ede.webp"),
            content_type: "image/webp",
        }),
        "Ireland-leader-3fd7b6772f15.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ireland-a81e7215806bc2d7.webp"),
            content_type: "image/webp",
        }),
        "Israel-694f2fc34915.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Israel-694f2fc34915-3b29ab61578de0bf.webp"),
            content_type: "image/webp",
        }),
        "Israel-leader-adeb621a7630.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Israel-e94f1edee9145e79.webp"),
            content_type: "image/webp",
        }),
        "Italy-490fd77a886a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Italy-490fd77a886a-147122e18b537e6e.webp"),
            content_type: "image/webp",
        }),
        "Italy-leader-43d2007c1cf4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Italy-ba3d5cfbaa3ff93c.webp"),
            content_type: "image/webp",
        }),
        "Jamaica-d2ad974f38b6.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Jamaica-d2ad974f38b6-f28325b985c6f76b.webp"),
            content_type: "image/webp",
        }),
        "Jamaica-leader-f23541a20f37.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Jamaica-621eb80f6fb218f1.webp"),
            content_type: "image/webp",
        }),
        "Japan-ce625f760d02.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Japan-ce625f760d02-975d847e780d9df8.webp"),
            content_type: "image/webp",
        }),
        "Japan-leader-e8f07cf89b13.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Japan-13905d26f18e8c4f.webp"),
            content_type: "image/webp",
        }),
        "Jordan-c34f095391d1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Jordan-c34f095391d1-1cb99a32d0cff088.webp"),
            content_type: "image/webp",
        }),
        "Jordan-leader-ff0d08eac2bb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Jordan-061f94850213d286.webp"),
            content_type: "image/webp",
        }),
        "Kazakhstan-4da7e6dcc5ce.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Kazakhstan-4da7e6dcc5ce-14e41803d02ec9cd.webp"),
            content_type: "image/webp",
        }),
        "Kazakhstan-leader-2ee19cb92075.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Kazakhstan-1120e49d9d44fe16.webp"),
            content_type: "image/webp",
        }),
        "Kenya-9808bce561b8.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Kenya-9808bce561b8-c2926593e87c1e5e.webp"),
            content_type: "image/webp",
        }),
        "Kenya-leader-fcd01befb37f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Kenya-04b25ad8c04ef850.webp"),
            content_type: "image/webp",
        }),
        "Kuwait-1312e894a527.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Kuwait-1312e894a527-f57b5ddbd5b87118.webp"),
            content_type: "image/webp",
        }),
        "Kuwait-leader-53e78d23f848.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Kuwait-d9070ebd46ecfd10.webp"),
            content_type: "image/webp",
        }),
        "Kyrgyzstan-f11115fe3b50.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Kyrgyzstan-f11115fe3b50-f620f1f49620f9e5.webp"),
            content_type: "image/webp",
        }),
        "Kyrgyzstan-leader-f955e90d88bf.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Kyrgyzstan-3fd4d4fc1b0adbe6.webp"),
            content_type: "image/webp",
        }),
        "Laos-d9171488de98.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Laos-d9171488de98-99d2463cc9604a9e.webp"),
            content_type: "image/webp",
        }),
        "Laos-leader-c006e05428e8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Laos-f270dee064f91188.webp"),
            content_type: "image/webp",
        }),
        "Latvia-2af3992e0329.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Latvia-2af3992e0329-cb251f7ac44fd654.webp"),
            content_type: "image/webp",
        }),
        "Latvia-leader-945f3683ace4.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Latvia-f06db2bbf86cafd1.webp"),
            content_type: "image/webp",
        }),
        "Lebanon-5ac96440fd0a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Lebanon-5ac96440fd0a-7bf101202884fef7.webp"),
            content_type: "image/webp",
        }),
        "Lebanon-leader-daa1bdfcdd35.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Lebanon-24760681102147dc.webp"),
            content_type: "image/webp",
        }),
        "Lesotho-f84b8249569d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Lesotho-f84b8249569d-36b082a9793ec63f.webp"),
            content_type: "image/webp",
        }),
        "Lesotho-leader-25fb37ce645c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Lesotho-8e17e27c5780ed88.webp"),
            content_type: "image/webp",
        }),
        "Libya-30d504bf7617.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Libya-30d504bf7617-312cd3c94d73e076.webp"),
            content_type: "image/webp",
        }),
        "Libya-leader-84e7af913b21.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Libya-a6853058cd1743ae.webp"),
            content_type: "image/webp",
        }),
        "Lithuania-d0da5887380a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Lithuania-d0da5887380a-7b2772ec28f61782.webp"),
            content_type: "image/webp",
        }),
        "Lithuania-leader-b3a8a7f8813e.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Lithuania-280cafba58502de3.webp"),
            content_type: "image/webp",
        }),
        "Luxembourg-3df6ae969f9e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Luxembourg-3df6ae969f9e-c7b8314efd6f1948.webp"),
            content_type: "image/webp",
        }),
        "Luxembourg-leader-0f084bf6b375.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Luxembourg-f1c6f803690964bf.webp"),
            content_type: "image/webp",
        }),
        "Macedonia-b885c99f5cdc.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Macedonia-b885c99f5cdc-4ff99b2a8f475ff8.webp"),
            content_type: "image/webp",
        }),
        "Macedonia-leader-e5e39a810e5d.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Macedonia-28b6b044e677d962.webp"),
            content_type: "image/webp",
        }),
        "Madagascar-6bfdb03d052d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Madagascar-6bfdb03d052d-f6388d8ebdf734b4.webp"),
            content_type: "image/webp",
        }),
        "Madagascar-leader-49a878ed910e.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Madagascar-f2ed27105d20cc36.webp"),
            content_type: "image/webp",
        }),
        "Malawi-3ea5ca1b10e1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Malawi-3ea5ca1b10e1-7cbf1c81446314fc.webp"),
            content_type: "image/webp",
        }),
        "Malawi-leader-9918ee88e318.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Malawi-b7723bf70ff35c88.webp"),
            content_type: "image/webp",
        }),
        "Malaysia-c8b5e83391aa.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Malaysia-c8b5e83391aa-72ba20ed99b711bb.webp"),
            content_type: "image/webp",
        }),
        "Malaysia-leader-ebc5fabaddf2.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Malaysia-229a49e9dd19e292.webp"),
            content_type: "image/webp",
        }),
        "Maldives-fb6d44c5c534.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Maldives-fb6d44c5c534-6a9024b7c357a283.webp"),
            content_type: "image/webp",
        }),
        "Maldives-leader-4a0dbdafbfb5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Maldives-d062aa649210666f.webp"),
            content_type: "image/webp",
        }),
        "Malta-leader-7eee9b6631a2.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Malta-55e2e0fcf7c397ee.webp"),
            content_type: "image/webp",
        }),
        "Mauritius-be395bdefbe3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Mauritius-be395bdefbe3-5a81f519175b62a3.webp"),
            content_type: "image/webp",
        }),
        "Mauritius-leader-141599545a72.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Mauritius-b32ec32c1458539a.webp"),
            content_type: "image/webp",
        }),
        "Mexico-8030c7281e1b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Mexico-8030c7281e1b-09d567c987466d92.webp"),
            content_type: "image/webp",
        }),
        "Mexico-leader-61c5830fa230.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Mexico-33161810af022709.webp"),
            content_type: "image/webp",
        }),
        "Moldova-0199410bd728.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Moldova-0199410bd728-e016ef2a0c5aedef.webp"),
            content_type: "image/webp",
        }),
        "Moldova-leader-b3efadfbaee6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Moldova-f4202b2fe482e5ef.webp"),
            content_type: "image/webp",
        }),
        "Mongolia-f3c139ce91ca.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Mongolia-f3c139ce91ca-810f840ff348dcb8.webp"),
            content_type: "image/webp",
        }),
        "Mongolia-leader-9b7faaf35c88.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Mongolia-281d49b72f359fe7.webp"),
            content_type: "image/webp",
        }),
        "Montenegro-393df428fe2e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Montenegro-393df428fe2e-375a3b0c48a903ec.webp"),
            content_type: "image/webp",
        }),
        "Montenegro-leader-b0ab96c2fd44.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Montenegro-5eb126bccfdbce41.webp"),
            content_type: "image/webp",
        }),
        "Morocco-50c11f9dd586.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Morocco-50c11f9dd586-318997141e4d6556.webp"),
            content_type: "image/webp",
        }),
        "Morocco-leader-b7d54d4363c6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Morocco-548105920bb14fcb.webp"),
            content_type: "image/webp",
        }),
        "Mozambique-d91375a47ed5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Mozambique-d91375a47ed5-b88d6c4b4c767186.webp"),
            content_type: "image/webp",
        }),
        "Mozambique-leader-9ae0fab19167.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Mozambique-0f08d8233a305264.webp"),
            content_type: "image/webp",
        }),
        "Myanmar-6422b1cada0e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Myanmar-6422b1cada0e-131e6322dfaa546b.webp"),
            content_type: "image/webp",
        }),
        "Myanmar-leader-8ab70720325f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Myanmar-fb1dc86ece85af17.webp"),
            content_type: "image/webp",
        }),
        "Namibia-becf3dbb0829.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Namibia-becf3dbb0829-7c6256d3789f4716.webp"),
            content_type: "image/webp",
        }),
        "Namibia-leader-8ed44252fafd.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Namibia-aa7e8edbfa00a2e0.webp"),
            content_type: "image/webp",
        }),
        "Nepal-667c97815649.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Nepal-667c97815649-97d0b7b495106150.webp"),
            content_type: "image/webp",
        }),
        "Nepal-leader-b34225e7a67d.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Nepal-be9088827878b4f7.webp"),
            content_type: "image/webp",
        }),
        "Netherlands-2c3fb66f19be.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Netherlands-2c3fb66f19be-4f5ba1bb096b6917.webp"),
            content_type: "image/webp",
        }),
        "Netherlands-leader-767f75c73e9f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Netherlands-3c3d9f23dc4a47df.webp"),
            content_type: "image/webp",
        }),
        "NewZealand-931ef513b810.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/NewZealand-931ef513b810-e0a8cfcbe0278d97.webp"),
            content_type: "image/webp",
        }),
        "NewZealand-leader-e01a6f19ff24.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/NewZealand-aa9ce148b97e4fbc.webp"),
            content_type: "image/webp",
        }),
        "Nicaragua-c696d20a1e21.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Nicaragua-c696d20a1e21-ab0a59f34eb50671.webp"),
            content_type: "image/webp",
        }),
        "Nicaragua-leader-d759757dd883.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Nicaragua-0a9fb7a4779a0963.webp"),
            content_type: "image/webp",
        }),
        "Nigeria-4ad4d17426a5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Nigeria-4ad4d17426a5-bab8139e872cee40.webp"),
            content_type: "image/webp",
        }),
        "Nigeria-leader-47783b146ea5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Nigeria-bbfbce9cade8e0c4.webp"),
            content_type: "image/webp",
        }),
        "NorthKorea-ada9424cc241.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/NorthKorea-ada9424cc241-ec9f492a941f8ad8.webp"),
            content_type: "image/webp",
        }),
        "NorthKorea-leader-6e8f560c6d32.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/NorthKorea-5d10ea65ae88f27d.webp"),
            content_type: "image/webp",
        }),
        "Norway-leader-69d39eb268ea.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Norway-e001b392200623cd.webp"),
            content_type: "image/webp",
        }),
        "Oman-leader-9ed97b2ff48a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Oman-2207d62c52774045.webp"),
            content_type: "image/webp",
        }),
        "Pakistan-leader-3ddd4356bc37.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Pakistan-4061891315e6b194.webp"),
            content_type: "image/webp",
        }),
        "Panama-0bd09f557ac9.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Panama-0bd09f557ac9-38fe27676ffe6738.webp"),
            content_type: "image/webp",
        }),
        "Panama-leader-c656f5adb5c8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Panama-a0a234a7623e392d.webp"),
            content_type: "image/webp",
        }),
        "PapuaNewGuinea-2798c565d3bc.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/PapuaNewGuinea-2798c565d3bc-bf5da6b04da864fa.webp"),
            content_type: "image/webp",
        }),
        "PapuaNewGuinea-leader-182b40264e85.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/PapuaNewGuinea-64672a6e5f167684.webp"),
            content_type: "image/webp",
        }),
        "Paraguay-8f6ca0d5b95f.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Paraguay-8f6ca0d5b95f-7cd45056612f439c.webp"),
            content_type: "image/webp",
        }),
        "Paraguay-leader-e9dd37d369c0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Paraguay-c21b17894fa32fd3.webp"),
            content_type: "image/webp",
        }),
        "Peru-2760db6ca168.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Peru-2760db6ca168-de864268b8213854.webp"),
            content_type: "image/webp",
        }),
        "Peru-leader-b8a168df7dd2.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Peru-63778c435e55cc50.webp"),
            content_type: "image/webp",
        }),
        "Philippines-09d6fa43d875.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Philippines-09d6fa43d875-64061eaa4964ec17.webp"),
            content_type: "image/webp",
        }),
        "Philippines-leader-28d07dd2fac6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Philippines-1df2fefedb9bd8c8.webp"),
            content_type: "image/webp",
        }),
        "Poland-1b4ccc3cc292.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Poland-1b4ccc3cc292-24ecd154215e95d3.webp"),
            content_type: "image/webp",
        }),
        "Poland-leader-312bcf73faff.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Poland-cd66c03063bb1172.webp"),
            content_type: "image/webp",
        }),
        "Portugal-leader-4976924da894.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Portugal-144c4e999495c326.webp"),
            content_type: "image/webp",
        }),
        "Qatar-d30b81d6d372.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Qatar-d30b81d6d372-07935db7213b9613.webp"),
            content_type: "image/webp",
        }),
        "Qatar-leader-6b7135cc0429.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Qatar-dc458fefde093e1e.webp"),
            content_type: "image/webp",
        }),
        "Romania-dc48f86150b3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Romania-dc48f86150b3-ab85ddb16245aa88.webp"),
            content_type: "image/webp",
        }),
        "Romania-leader-1c1b3769bef0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Romania-09db4c6f0d41c306.webp"),
            content_type: "image/webp",
        }),
        "Russia-88e3be89087e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Russia-88e3be89087e-e97ad88be9bf4355.webp"),
            content_type: "image/webp",
        }),
        "Russia-leader-ad7dbb51ac3c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Russia-39d2288722e7fad9.webp"),
            content_type: "image/webp",
        }),
        "Samoa-a54b8284cdc9.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Samoa-a54b8284cdc9-5b1de73fbba6e8c7.webp"),
            content_type: "image/webp",
        }),
        "Samoa-leader-baecf0adbf80.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Samoa-e408b15d607c9ef5.webp"),
            content_type: "image/webp",
        }),
        "SaoTome-c221ea95d0d2.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SaoTome-c221ea95d0d2-d0c2506d78c96a64.webp"),
            content_type: "image/webp",
        }),
        "SaoTome-leader-dfdec363be04.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SaoTome-d7cf99a3a20f5d61.webp"),
            content_type: "image/webp",
        }),
        "SaudiArabia-1417bf694248.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SaudiArabia-1417bf694248-8fc1cddd886ae4f0.webp"),
            content_type: "image/webp",
        }),
        "SaudiArabia-leader-b3eaa313d3eb.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SaudiArabia-4cd603a312e9deea.webp"),
            content_type: "image/webp",
        }),
        "Senegal-leader-180cd0430468.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Senegal-4304668dd6c17bfa.webp"),
            content_type: "image/webp",
        }),
        "Serbia-73b42d727616.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Serbia-73b42d727616-2e9a7078027a6579.webp"),
            content_type: "image/webp",
        }),
        "Serbia-leader-4836d1e82b2d.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Serbia-58713d8692b6cf35.webp"),
            content_type: "image/webp",
        }),
        "Seychelles-19f784374d49.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Seychelles-19f784374d49-0a20f753b4689c5a.webp"),
            content_type: "image/webp",
        }),
        "Seychelles-leader-ebb53369343e.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Seychelles-d02b3cb61be44fb9.webp"),
            content_type: "image/webp",
        }),
        "Singapore-3c48d2fb2f7a.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Singapore-3c48d2fb2f7a-b63cb49a2ef13412.webp"),
            content_type: "image/webp",
        }),
        "Singapore-leader-666c2be14c86.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Singapore-cc6d6ee1d327b029.webp"),
            content_type: "image/webp",
        }),
        "Slovenia-1a6852c763e8.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Slovenia-1a6852c763e8-17ef4403b548aa45.webp"),
            content_type: "image/webp",
        }),
        "Slovenia-leader-73f1f980568a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Slovenia-f63ddca83d910171.webp"),
            content_type: "image/webp",
        }),
        "SolomonIslands-f492155d4a4e.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SolomonIslands-f492155d4a4e-795e6086dfd76e3c.webp"),
            content_type: "image/webp",
        }),
        "SolomonIslands-leader-1faf4b1461be.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SolomonIslands-dfab0e3923c1c12d.webp"),
            content_type: "image/webp",
        }),
        "SouthAfrica-c18b98eb769d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SouthAfrica-c18b98eb769d-8beb49f14f02b351.webp"),
            content_type: "image/webp",
        }),
        "SouthAfrica-leader-570b0edbc6e0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SouthAfrica-567766ef261a3c53.webp"),
            content_type: "image/webp",
        }),
        "SouthKorea-leader-fb75ff77f7ab.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SouthKorea-6842e217f65b0d37.webp"),
            content_type: "image/webp",
        }),
        "Spain-1ab13145c12d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Spain-1ab13145c12d-286127ee0a875de1.webp"),
            content_type: "image/webp",
        }),
        "Spain-leader-f6d1802b79b0.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Spain-405fa56e9ce8d9fb.webp"),
            content_type: "image/webp",
        }),
        "SriLanka-3d12f3f83446.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SriLanka-3d12f3f83446-38b93a48ed8c5074.webp"),
            content_type: "image/webp",
        }),
        "SriLanka-leader-cd991ccd12b6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/SriLanka-ca796ec56b0fa713.webp"),
            content_type: "image/webp",
        }),
        "Sudan-db01b56e2028.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Sudan-db01b56e2028-2f58317e8b9964c2.webp"),
            content_type: "image/webp",
        }),
        "Sudan-leader-7f6cd05d6b53.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Sudan-f45ff38bc21580ba.webp"),
            content_type: "image/webp",
        }),
        "Suriname-57bb04414091.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Suriname-57bb04414091-0ff1a45e727cc28f.webp"),
            content_type: "image/webp",
        }),
        "Suriname-leader-3a6b156d8479.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Suriname-0ac105f1e3fc6f43.webp"),
            content_type: "image/webp",
        }),
        "Swaziland-0cae5ee95b61.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Swaziland-0cae5ee95b61-888163dbeda969eb.webp"),
            content_type: "image/webp",
        }),
        "Swaziland-leader-2469fa3b99c5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Swaziland-5d95f1c4c7b57100.webp"),
            content_type: "image/webp",
        }),
        "Sweden-760e51a41b4d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Sweden-760e51a41b4d-2b8a3788fe7e92fa.webp"),
            content_type: "image/webp",
        }),
        "Sweden-leader-385b4a4784ac.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Sweden-7b7a8aa18d008595.webp"),
            content_type: "image/webp",
        }),
        "Switzerland-3830d79d0784.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Switzerland-3830d79d0784-38928466e28d4eb1.webp"),
            content_type: "image/webp",
        }),
        "Switzerland-leader-ef1e6ee4b749.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Switzerland-8f44f97f5109646d.webp"),
            content_type: "image/webp",
        }),
        "Syria-9b264fb10afb.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Syria-9b264fb10afb-b1736c75eb02aed3.webp"),
            content_type: "image/webp",
        }),
        "Syria-leader-30077fbc4bd5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Syria-fc01a5fdb31b18a9.webp"),
            content_type: "image/webp",
        }),
        "Taiwan-d9eeaaad4764.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Taiwan-d9eeaaad4764-8da4005b4c4c0299.webp"),
            content_type: "image/webp",
        }),
        "Taiwan-leader-753218d3b9ac.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Taiwan-67b5fb3878786c0f.webp"),
            content_type: "image/webp",
        }),
        "Tajikistan-1156e86fce5c.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Tajikistan-1156e86fce5c-b81b9faab4a4c8c7.webp"),
            content_type: "image/webp",
        }),
        "Tajikistan-leader-ec3e76b96f01.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Tajikistan-bc576c4495ed5103.webp"),
            content_type: "image/webp",
        }),
        "Tanzania-1b3df45b8711.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Tanzania-1b3df45b8711-0c2869c962f8edc2.webp"),
            content_type: "image/webp",
        }),
        "Tanzania-leader-c7a9ad34bc38.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Tanzania-b2e65678b79eba6b.webp"),
            content_type: "image/webp",
        }),
        "Thailand-1eab1b0aca79.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Thailand-1eab1b0aca79-1d15cd3b4c18f3aa.webp"),
            content_type: "image/webp",
        }),
        "Thailand-leader-5053f1afa592.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Thailand-93f42909d02908f7.webp"),
            content_type: "image/webp",
        }),
        "Tonga-136734790809.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Tonga-136734790809-906faeb4c53d39ee.webp"),
            content_type: "image/webp",
        }),
        "Tonga-leader-ebd2ff6c883c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Tonga-a0341f8b063131dc.webp"),
            content_type: "image/webp",
        }),
        "TrinidadTobago-c573490695f6.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/TrinidadTobago-c573490695f6-3e7d64a70fd00c4a.webp"),
            content_type: "image/webp",
        }),
        "TrinidadTobago-leader-70f9c5d60065.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/TrinidadTobago-468b76aca8f15884.webp"),
            content_type: "image/webp",
        }),
        "Tunisia-e2d49284c1a1.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Tunisia-e2d49284c1a1-1537b18e135d36be.webp"),
            content_type: "image/webp",
        }),
        "Tunisia-leader-9be2b3bf8d5b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Tunisia-001473e5361c04b5.webp"),
            content_type: "image/webp",
        }),
        "Turkey-e0af9dc12d8b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Turkey-e0af9dc12d8b-c9d983ac3f5c8bbf.webp"),
            content_type: "image/webp",
        }),
        "Turkey-leader-b46e149456ba.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Turkey-e5d1c29aa72ba120.webp"),
            content_type: "image/webp",
        }),
        "Turkmenistan-f38dab11ceb5.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Turkmenistan-f38dab11ceb5-3c68fcca343b0c07.webp"),
            content_type: "image/webp",
        }),
        "Turkmenistan-leader-2d172c1ea313.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Turkmenistan-2501f2078ac5474b.webp"),
            content_type: "image/webp",
        }),
        "UAE-d1d72d5a5940.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/UAE-d1d72d5a5940-9bc3c0792dd43f6c.webp"),
            content_type: "image/webp",
        }),
        "UAE-leader-398bef13e65f.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/UAE-429018c74f5bb42b.webp"),
            content_type: "image/webp",
        }),
        "UK-3720e6545ca3.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/UK-3720e6545ca3-0f3cf6deeae1e9e6.webp"),
            content_type: "image/webp",
        }),
        "UK-leader-005a2e5a6961.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/UK-bf0cb82518a93a52.webp"),
            content_type: "image/webp",
        }),
        "USA-d924827d2a14.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/USA-d924827d2a14-029ca553a5c5758f.webp"),
            content_type: "image/webp",
        }),
        "USA-leader-088ed05335f8.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/USA-9a9acf43cd29aa48.webp"),
            content_type: "image/webp",
        }),
        "USSR-c09819e723d7.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/USSR-c09819e723d7-10efd4531585e28f.webp"),
            content_type: "image/webp",
        }),
        "USSR-leader-c1d33087b77c.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/USSR-e26ef1d17e0953d6.webp"),
            content_type: "image/webp",
        }),
        "Uganda-2576e6893d89.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Uganda-2576e6893d89-631553b42609c50e.webp"),
            content_type: "image/webp",
        }),
        "Uganda-leader-d587a43edd3e.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Uganda-1d0cb037d1f38c14.webp"),
            content_type: "image/webp",
        }),
        "Ukraine-a39df9937284.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ukraine-a39df9937284-a0d9819329692727.webp"),
            content_type: "image/webp",
        }),
        "Ukraine-leader-082df7061021.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Ukraine-5421781753d96d20.webp"),
            content_type: "image/webp",
        }),
        "Uruguay-1d8e52189e41.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Uruguay-1d8e52189e41-12fb82bacee2305a.webp"),
            content_type: "image/webp",
        }),
        "Uruguay-leader-70e88aba2989.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Uruguay-a62789b1a0d2480e.webp"),
            content_type: "image/webp",
        }),
        "Uzbekistan-leader-58202dfd8fa7.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Uzbekistan-9d6d399b2d7eedee.webp"),
            content_type: "image/webp",
        }),
        "Vanuatu-leader-ae09d4392d40.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Vanuatu-6ee5565314c309e5.webp"),
            content_type: "image/webp",
        }),
        "Venezuela-c3df9d921292.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Venezuela-c3df9d921292-5b5355077ff60fb4.webp"),
            content_type: "image/webp",
        }),
        "Venezuela-leader-78680e6c23db.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Venezuela-47a7c4c997c62059.webp"),
            content_type: "image/webp",
        }),
        "Vietnam-a2596dee0d3b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Vietnam-a2596dee0d3b-e524b1fe14540129.webp"),
            content_type: "image/webp",
        }),
        "Vietnam-leader-e5a8a54d6af6.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Vietnam-4d866130c525e6d3.webp"),
            content_type: "image/webp",
        }),
        "Yemen-efe87b865b08.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Yemen-efe87b865b08-8f062790f473640f.webp"),
            content_type: "image/webp",
        }),
        "Yemen-leader-bb56b66ff38a.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Yemen-c47fe15449f644ed.webp"),
            content_type: "image/webp",
        }),
        "Yugoslavia-d1380837e251.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Yugoslavia-d1380837e251-ae52a3a66fdb0d8a.webp"),
            content_type: "image/webp",
        }),
        "Yugoslavia-leader-a3e9ec5c2120.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Yugoslavia-5a9db1ceb457a3ea.webp"),
            content_type: "image/webp",
        }),
        "Zaire-0beb18820b9d.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Zaire-0beb18820b9d-872e069215f7cbf9.webp"),
            content_type: "image/webp",
        }),
        "Zaire-leader-493de7626ad5.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Zaire-114173317efe20ac.webp"),
            content_type: "image/webp",
        }),
        "Zambia-21d2515a9266.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Zambia-21d2515a9266-e9d91373994c1c50.webp"),
            content_type: "image/webp",
        }),
        "Zambia-leader-039752d11c9b.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Zambia-53d1bc481db60a50.webp"),
            content_type: "image/webp",
        }),
        "Zimbabwe-7a24d023476b.webp" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Zimbabwe-7a24d023476b-a5e04309dd2ee2eb.webp"),
            content_type: "image/webp",
        }),
        "Zimbabwe-leader-906af32af708.png" => Some(PortraitAsset {
            bytes: include_bytes!("../ui/display-art/Zimbabwe-98beb766c06d57e7.webp"),
            content_type: "image/webp",
        }),
        _ => None,
    }
}

#[allow(dead_code)]
pub const FILENAMES: &[&str] = &[
    "Afghanistan-fce177144639.webp",
    "Afghanistan-leader-f86caeb10c1d.png",
    "Albania-dc27557adba1.webp",
    "Albania-leader-903811fcd953.png",
    "Algeria-0b9c67b3580c.webp",
    "Algeria-leader-40fd7af2f732.png",
    "Angola-leader-f4e74b240157.png",
    "Argentina-b91623db6af3.webp",
    "Argentina-leader-a101d5f078a3.png",
    "Armenia-a368e4ff55d1.webp",
    "Armenia-leader-ca833833a698.png",
    "Australia-leader-f55526a0d34c.png",
    "Austria-8654c9cef838.webp",
    "Austria-leader-df62375be251.png",
    "Azerbaijan-2f640fd15e9b.webp",
    "Azerbaijan-leader-5c9cd794afa1.png",
    "Bahamas-1c8efdb481a3.webp",
    "Bahamas-leader-8572851d48cb.png",
    "Bahrain-948f22793ce8.webp",
    "Bahrain-leader-85ca829f1fb7.png",
    "Bangladesh-c46c7660231d.webp",
    "Bangladesh-leader-22739f7701b4.png",
    "Belarus-30cc563e5afb.webp",
    "Belarus-leader-c9f31ded4c1a.png",
    "Belgium-leader-e9b24afba072.png",
    "Belize-leader-3228c097c1df.png",
    "Bhutan-ae31c54f2ad4.webp",
    "Bhutan-leader-b2cf694ebed0.png",
    "Bolivia-bba86fa3bff1.webp",
    "Bolivia-leader-2ea566d44234.png",
    "Bosnia-cca8507f915e.webp",
    "Bosnia-leader-e78227c3f1b4.png",
    "Botswana-6957bece838d.webp",
    "Botswana-leader-1bd3e888ee42.png",
    "Brazil-dd81b9e75b6c.webp",
    "Brazil-leader-d0f6f3b52a10.png",
    "Brunei-148342c02d15.webp",
    "Brunei-leader-740096a4e925.png",
    "Bulgaria-673e684ff947.webp",
    "Bulgaria-leader-df60ef4ca603.png",
    "Cambodia-1fef6e1ef9b7.webp",
    "Cambodia-leader-36a4db761f64.png",
    "Cameroon-bd66e3ef1a63.webp",
    "Cameroon-leader-fbdadb6d80fa.png",
    "Canada-e1b5c394ad55.webp",
    "Canada-leader-5e8ec77bcd18.png",
    "CapeVerde-4436e5afadf5.webp",
    "CapeVerde-leader-35a141178c3b.png",
    "CentralAfricanRepublic-d2777cd71eeb.webp",
    "CentralAfricanRepublic-leader-c57ccb06fdc7.png",
    "Chad-leader-4bc000d7aee9.png",
    "Chile-8ca8a4c797a3.webp",
    "Chile-leader-ee0b701ecc5a.png",
    "China-a8ba380d17c6.webp",
    "China-leader-350f76603ff5.png",
    "Colombia-8857df09c470.webp",
    "Colombia-leader-b33336138ce5.png",
    "Comoros-leader-0cbc3b8182b8.png",
    "Congo-11dca3605869.webp",
    "Congo-leader-e306732110d9.png",
    "CostaRica-eabce8094e78.webp",
    "CostaRica-leader-99717561cd37.png",
    "Croatia-40e31abb08ec.webp",
    "Croatia-leader-a02aa5a96157.png",
    "Cuba-ec84e0920b43.webp",
    "Cuba-leader-72a2d0148fef.png",
    "Cyprus-739821002edf.webp",
    "Cyprus-leader-554396a51feb.png",
    "Czechoslovakia-d2402dd13b8d.webp",
    "Czechoslovakia-leader-9fca0a08f5ca.png",
    "Denmark-1d8d01f03ea7.webp",
    "Denmark-leader-7db97be7511b.png",
    "DominicanRepublic-f876ab0536fd.webp",
    "DominicanRepublic-leader-338e895731fa.png",
    "EastTimor-803175d13879.webp",
    "EastTimor-leader-f1dd388f69b7.png",
    "Ecuador-625d480e50f7.webp",
    "Ecuador-leader-a83ed4f7cde5.png",
    "Egypt-9002995e92ea.webp",
    "Egypt-leader-a9767e906d23.png",
    "ElSalvador-3f5bddcbf46c.webp",
    "ElSalvador-leader-106251a76796.png",
    "EquatorialGuinea-5fbe4aec0a0a.webp",
    "EquatorialGuinea-leader-3709a2e9b864.png",
    "Estonia-eefc03c6692e.webp",
    "Estonia-leader-d7c769b9b9c7.png",
    "Ethiopia-a078474d6dc1.webp",
    "Ethiopia-leader-cab15e7748e8.png",
    "Fiji-e526b1a13c3a.webp",
    "Fiji-leader-c636a3f231f6.png",
    "Finland-85477212a438.webp",
    "Finland-leader-0a2cdb94da79.png",
    "France-fcd6b90d4338.webp",
    "France-leader-45efa5125248.png",
    "Gabon-leader-a07a1ecd636f.png",
    "Georgia-616c410a0127.webp",
    "Georgia-leader-a68f4b0660b0.png",
    "Germany-leader-82e3ff0675fe.png",
    "Ghana-1c298c7d5d5a.webp",
    "Ghana-leader-2ccab2063dd4.png",
    "Greece-8630f8dc9e62.webp",
    "Greece-leader-63df4fe43beb.png",
    "Guatemala-b4499f3121d1.webp",
    "Guatemala-leader-ad689e066275.png",
    "Guyana-d84ea0bada0e.webp",
    "Guyana-leader-38003ef82d27.png",
    "Haiti-17fd6a98fbd3.webp",
    "Haiti-leader-e5fe31935f13.png",
    "Honduras-f9e7b2b05ab5.webp",
    "Honduras-leader-30a3fd9e88a0.png",
    "Hungary-05087255cb00.webp",
    "Hungary-leader-275b3ae1a8ec.png",
    "Iceland-596ee2ad62a5.webp",
    "Iceland-leader-84b7f895d85f.png",
    "India-262b7848a6c1.webp",
    "India-leader-d2045da0dd8b.png",
    "Indonesia-b05c91d384ff.webp",
    "Indonesia-leader-263c706699ed.png",
    "Iran-2a433b6f832a.webp",
    "Iran-leader-ec534fac151c.png",
    "Iraq-703752196158.webp",
    "Iraq-leader-caf35a654595.png",
    "Ireland-951a29fd9759.webp",
    "Ireland-leader-3fd7b6772f15.png",
    "Israel-694f2fc34915.webp",
    "Israel-leader-adeb621a7630.png",
    "Italy-490fd77a886a.webp",
    "Italy-leader-43d2007c1cf4.png",
    "Jamaica-d2ad974f38b6.webp",
    "Jamaica-leader-f23541a20f37.png",
    "Japan-ce625f760d02.webp",
    "Japan-leader-e8f07cf89b13.png",
    "Jordan-c34f095391d1.webp",
    "Jordan-leader-ff0d08eac2bb.png",
    "Kazakhstan-4da7e6dcc5ce.webp",
    "Kazakhstan-leader-2ee19cb92075.png",
    "Kenya-9808bce561b8.webp",
    "Kenya-leader-fcd01befb37f.png",
    "Kuwait-1312e894a527.webp",
    "Kuwait-leader-53e78d23f848.png",
    "Kyrgyzstan-f11115fe3b50.webp",
    "Kyrgyzstan-leader-f955e90d88bf.png",
    "Laos-d9171488de98.webp",
    "Laos-leader-c006e05428e8.png",
    "Latvia-2af3992e0329.webp",
    "Latvia-leader-945f3683ace4.png",
    "Lebanon-5ac96440fd0a.webp",
    "Lebanon-leader-daa1bdfcdd35.png",
    "Lesotho-f84b8249569d.webp",
    "Lesotho-leader-25fb37ce645c.png",
    "Libya-30d504bf7617.webp",
    "Libya-leader-84e7af913b21.png",
    "Lithuania-d0da5887380a.webp",
    "Lithuania-leader-b3a8a7f8813e.png",
    "Luxembourg-3df6ae969f9e.webp",
    "Luxembourg-leader-0f084bf6b375.png",
    "Macedonia-b885c99f5cdc.webp",
    "Macedonia-leader-e5e39a810e5d.png",
    "Madagascar-6bfdb03d052d.webp",
    "Madagascar-leader-49a878ed910e.png",
    "Malawi-3ea5ca1b10e1.webp",
    "Malawi-leader-9918ee88e318.png",
    "Malaysia-c8b5e83391aa.webp",
    "Malaysia-leader-ebc5fabaddf2.png",
    "Maldives-fb6d44c5c534.webp",
    "Maldives-leader-4a0dbdafbfb5.png",
    "Malta-leader-7eee9b6631a2.png",
    "Mauritius-be395bdefbe3.webp",
    "Mauritius-leader-141599545a72.png",
    "Mexico-8030c7281e1b.webp",
    "Mexico-leader-61c5830fa230.png",
    "Moldova-0199410bd728.webp",
    "Moldova-leader-b3efadfbaee6.png",
    "Mongolia-f3c139ce91ca.webp",
    "Mongolia-leader-9b7faaf35c88.png",
    "Montenegro-393df428fe2e.webp",
    "Montenegro-leader-b0ab96c2fd44.png",
    "Morocco-50c11f9dd586.webp",
    "Morocco-leader-b7d54d4363c6.png",
    "Mozambique-d91375a47ed5.webp",
    "Mozambique-leader-9ae0fab19167.png",
    "Myanmar-6422b1cada0e.webp",
    "Myanmar-leader-8ab70720325f.png",
    "Namibia-becf3dbb0829.webp",
    "Namibia-leader-8ed44252fafd.png",
    "Nepal-667c97815649.webp",
    "Nepal-leader-b34225e7a67d.png",
    "Netherlands-2c3fb66f19be.webp",
    "Netherlands-leader-767f75c73e9f.png",
    "NewZealand-931ef513b810.webp",
    "NewZealand-leader-e01a6f19ff24.png",
    "Nicaragua-c696d20a1e21.webp",
    "Nicaragua-leader-d759757dd883.png",
    "Nigeria-4ad4d17426a5.webp",
    "Nigeria-leader-47783b146ea5.png",
    "NorthKorea-ada9424cc241.webp",
    "NorthKorea-leader-6e8f560c6d32.png",
    "Norway-leader-69d39eb268ea.png",
    "Oman-leader-9ed97b2ff48a.png",
    "Pakistan-leader-3ddd4356bc37.png",
    "Panama-0bd09f557ac9.webp",
    "Panama-leader-c656f5adb5c8.png",
    "PapuaNewGuinea-2798c565d3bc.webp",
    "PapuaNewGuinea-leader-182b40264e85.png",
    "Paraguay-8f6ca0d5b95f.webp",
    "Paraguay-leader-e9dd37d369c0.png",
    "Peru-2760db6ca168.webp",
    "Peru-leader-b8a168df7dd2.png",
    "Philippines-09d6fa43d875.webp",
    "Philippines-leader-28d07dd2fac6.png",
    "Poland-1b4ccc3cc292.webp",
    "Poland-leader-312bcf73faff.png",
    "Portugal-leader-4976924da894.png",
    "Qatar-d30b81d6d372.webp",
    "Qatar-leader-6b7135cc0429.png",
    "Romania-dc48f86150b3.webp",
    "Romania-leader-1c1b3769bef0.png",
    "Russia-88e3be89087e.webp",
    "Russia-leader-ad7dbb51ac3c.png",
    "Samoa-a54b8284cdc9.webp",
    "Samoa-leader-baecf0adbf80.png",
    "SaoTome-c221ea95d0d2.webp",
    "SaoTome-leader-dfdec363be04.png",
    "SaudiArabia-1417bf694248.webp",
    "SaudiArabia-leader-b3eaa313d3eb.png",
    "Senegal-leader-180cd0430468.png",
    "Serbia-73b42d727616.webp",
    "Serbia-leader-4836d1e82b2d.png",
    "Seychelles-19f784374d49.webp",
    "Seychelles-leader-ebb53369343e.png",
    "Singapore-3c48d2fb2f7a.webp",
    "Singapore-leader-666c2be14c86.png",
    "Slovenia-1a6852c763e8.webp",
    "Slovenia-leader-73f1f980568a.png",
    "SolomonIslands-f492155d4a4e.webp",
    "SolomonIslands-leader-1faf4b1461be.png",
    "SouthAfrica-c18b98eb769d.webp",
    "SouthAfrica-leader-570b0edbc6e0.png",
    "SouthKorea-leader-fb75ff77f7ab.png",
    "Spain-1ab13145c12d.webp",
    "Spain-leader-f6d1802b79b0.png",
    "SriLanka-3d12f3f83446.webp",
    "SriLanka-leader-cd991ccd12b6.png",
    "Sudan-db01b56e2028.webp",
    "Sudan-leader-7f6cd05d6b53.png",
    "Suriname-57bb04414091.webp",
    "Suriname-leader-3a6b156d8479.png",
    "Swaziland-0cae5ee95b61.webp",
    "Swaziland-leader-2469fa3b99c5.png",
    "Sweden-760e51a41b4d.webp",
    "Sweden-leader-385b4a4784ac.png",
    "Switzerland-3830d79d0784.webp",
    "Switzerland-leader-ef1e6ee4b749.png",
    "Syria-9b264fb10afb.webp",
    "Syria-leader-30077fbc4bd5.png",
    "Taiwan-d9eeaaad4764.webp",
    "Taiwan-leader-753218d3b9ac.png",
    "Tajikistan-1156e86fce5c.webp",
    "Tajikistan-leader-ec3e76b96f01.png",
    "Tanzania-1b3df45b8711.webp",
    "Tanzania-leader-c7a9ad34bc38.png",
    "Thailand-1eab1b0aca79.webp",
    "Thailand-leader-5053f1afa592.png",
    "Tonga-136734790809.webp",
    "Tonga-leader-ebd2ff6c883c.png",
    "TrinidadTobago-c573490695f6.webp",
    "TrinidadTobago-leader-70f9c5d60065.png",
    "Tunisia-e2d49284c1a1.webp",
    "Tunisia-leader-9be2b3bf8d5b.png",
    "Turkey-e0af9dc12d8b.webp",
    "Turkey-leader-b46e149456ba.png",
    "Turkmenistan-f38dab11ceb5.webp",
    "Turkmenistan-leader-2d172c1ea313.png",
    "UAE-d1d72d5a5940.webp",
    "UAE-leader-398bef13e65f.png",
    "UK-3720e6545ca3.webp",
    "UK-leader-005a2e5a6961.png",
    "USA-d924827d2a14.webp",
    "USA-leader-088ed05335f8.png",
    "USSR-c09819e723d7.webp",
    "USSR-leader-c1d33087b77c.png",
    "Uganda-2576e6893d89.webp",
    "Uganda-leader-d587a43edd3e.png",
    "Ukraine-a39df9937284.webp",
    "Ukraine-leader-082df7061021.png",
    "Uruguay-1d8e52189e41.webp",
    "Uruguay-leader-70e88aba2989.png",
    "Uzbekistan-leader-58202dfd8fa7.png",
    "Vanuatu-leader-ae09d4392d40.png",
    "Venezuela-c3df9d921292.webp",
    "Venezuela-leader-78680e6c23db.png",
    "Vietnam-a2596dee0d3b.webp",
    "Vietnam-leader-e5a8a54d6af6.png",
    "Yemen-efe87b865b08.webp",
    "Yemen-leader-bb56b66ff38a.png",
    "Yugoslavia-d1380837e251.webp",
    "Yugoslavia-leader-a3e9ec5c2120.png",
    "Zaire-0beb18820b9d.webp",
    "Zaire-leader-493de7626ad5.png",
    "Zambia-21d2515a9266.webp",
    "Zambia-leader-039752d11c9b.png",
    "Zimbabwe-7a24d023476b.webp",
    "Zimbabwe-leader-906af32af708.png",
];
