//! External, genuine pinned-master archive qualification. The generator and its
//! SHA/revision manifest are separate evidence; this test never creates the
//! source world or upgrades it through fresh-game initialization.
use super::*;
use serde_json::Value;

fn original_fields_survive(before: &Value, after: &Value, path: &str) {
    match before {
        Value::Object(fields) => {
            assert!(after.is_object(), "{path}: lost object");
            for (name, value) in fields {
                let next = format!("{path}.{name}");
                let actual = after
                    .get(name)
                    .unwrap_or_else(|| panic!("{next}: lost property"));
                original_fields_survive(value, actual, &next);
            }
        }
        Value::Array(rows) => {
            let actual = after
                .as_array()
                .unwrap_or_else(|| panic!("{path}: lost array"));
            assert_eq!(rows.len(), actual.len(), "{path}: changed ownership count");
            for (index, (before, after)) in rows.iter().zip(actual).enumerate() {
                original_fields_survive(before, after, &format!("{path}[{index}]"));
            }
        }
        _ => assert_eq!(before, after, "{path}: changed original property"),
    }
}

fn compare_recorded_field(before: &Value, after: &Value, field: &str) {
    if let Some(value) = before.get(field) {
        original_fields_survive(value, &after[field], field);
    }
}

fn world_payload(mut value: &Value) -> &Value {
    while value.get("format").is_some() && value.get("world").is_some() {
        value = &value["world"];
    }
    value
}

fn original_front_bits_survive(source: &Value, world: &WorldState) {
    // Conflict.front is BTreeMap<String, f32> in both pinned master and this
    // candidate. Check its native bits as well as the exact wire JSON below;
    // no decimal tolerance or ownership-wide float normalization is permitted.
    for before in source["conflicts"].as_array().unwrap() {
        let id = before["id"].as_u64().unwrap();
        let after = world.conflicts.iter().find(|c|u64::from(c.id)==id)
            .expect("An original conflict disappeared");
        let front: std::collections::BTreeMap<String, f32> =
            serde_json::from_value(before["front"].clone()).unwrap();
        assert_eq!(front.len(), after.front.len(), "Conflict {id}: front keys changed");
        for (district, value) in front {
            let actual = after.front.get(&district).expect("An original front district disappeared");
            assert_eq!(value.to_bits(), actual.to_bits(),
                "Conflict {id}, {district}: original native f32 bits changed");
        }
    }
}

fn assert_game_equal(a: &Game, b: &Game) {
    assert!(
        save(&a.world) == save(&b.world),
        "Canonical world differs after archive continuation"
    );
    assert_eq!(
        serde_json::to_value(&a.history).unwrap(),
        serde_json::to_value(&b.history).unwrap()
    );
    assert_eq!(
        serde_json::to_value(&a.log).unwrap(),
        serde_json::to_value(&b.log).unwrap()
    );
    assert_eq!(a.history_epoch, b.history_epoch);
}

#[test]
#[ignore = "Requires SPHERES_S05_MASTER_ARCHIVE pointing to the unchanged archive generated by the recorded pinned-master executable"]
fn actual_pinned_master_archive_preserves_property_history_and_next_day() {
    let path = std::path::PathBuf::from(
        std::env::var_os("SPHERES_S05_MASTER_ARCHIVE")
            .expect("Set SPHERES_S05_MASTER_ARCHIVE to the generated original archive"),
    );
    assert!(path.is_absolute(), "Use an absolute external evidence path");
    let original = std::fs::read(&path).unwrap();
    let text = std::str::from_utf8(&original).unwrap();
    let archive: Value = serde_json::from_str(text).unwrap();
    assert_eq!(archive["format"], "spheres-campaign");
    assert_eq!(archive["version"], 1);
    let source = world_payload(&archive["world"]);
    assert_eq!(source["year"], 1990);
    assert_eq!(source["month"], 2);
    assert_eq!(source.get("day").and_then(Value::as_u64).unwrap_or(1), 1);
    assert_eq!(source["rules"]["operational_warfare"], 1);
    assert!(
        source["companies"]["roster"]
            .as_array()
            .is_some_and(|r| !r.is_empty())
    );
    assert!(source["campaign"]["initialized"].as_bool().unwrap_or(false));
    assert!(archive["history"].as_array().is_some_and(|h| h.len() >= 32));

    let mut first = storage::decode(text)
        .expect("Original master archive must migrate without replacing its date or property");
    let independently_loaded = storage::decode(text).unwrap();
    assert_game_equal(&first, &independently_loaded);
    original_front_bits_survive(source, &first.world);
    // Compare the actual native save representation. `to_value` promotes an
    // f32 front value to f64 (for example -0.22152066 becomes
    // -0.22152066230773926); the real serializer retains its f32 wire number.
    // This is not a migration difference. Every saved number, including all
    // f64 money/quantities, still receives the exact equality check below.
    let migrated_save: Value = serde_json::from_str(&save(&first.world)).unwrap();
    let migrated = world_payload(&migrated_save);
    // Compare original values, allowing only newly introduced default fields.
    // Debt ratio is derived on old open-book load; nominal cash/debt are checked.
    for field in [
        "rules",
        "rng",
        "year",
        "month",
        "day",
        "player",
        "districts",
        "district_population",
        "district_population_scale",
        "population_system",
        "fiscal_recovery",
        "starting_industry",
        "materials",
        "commerce",
        "resources",
        "manufacturing",
        "logistics",
        "daily",
        "province_economy",
        "governments",
        "leadership",
        "conflicts",
        "campaign",
        "campaign_supply",
        "campaign_peace",
    ] {
        compare_recorded_field(source, migrated, field);
    }
    let source_nations = source["nations"].as_array().unwrap();
    let loaded_nations = migrated["nations"].as_array().unwrap();
    assert_eq!(source_nations.len(), loaded_nations.len());
    for (before, after) in source_nations.iter().zip(loaded_nations) {
        assert_eq!(before["id"], after["id"], "Nation identities/order changed");
        for field in [
            "id",
            "alive",
            "population",
            "population_outcomes",
            "gdp",
            "treasury_bn",
            "debt_bn",
            "budget",
            "program_budget",
            "arsenal",
            "equipment",
            "operations",
            "tech",
            "initial_population",
            "military",
            "mil_strength",
            "munitions",
            "war_exhaustion",
        ] {
            compare_recorded_field(before, after, field);
        }
    }
    // Requested construction capacity is intentionally retired in S02. It is
    // not paid property. The original paid project/industry/receipt books are.
    for field in [
        "projects",
        "provinces",
        "next_id",
        "industry",
        "rebuild_sites",
        "operations",
    ] {
        compare_recorded_field(&source["production"], &migrated["production"], field);
    }
    original_fields_survive(
        &source["companies"],
        &migrated["sector_contractors"],
        "companies -> sector_contractors",
    );
    assert_eq!(
        serde_json::to_value(&first.history).unwrap(),
        archive["history"]
    );
    assert_eq!(serde_json::to_value(&first.log).unwrap(), archive["log"]);
    assert_eq!(
        first.history_epoch,
        archive
            .get("history_epoch")
            .and_then(Value::as_u64)
            .unwrap_or(0)
    );
    assert_eq!(
        first.world.date_str(),
        archive["saved_date"].as_str().unwrap()
    );
    // Loading must not adopt the prospective supplier-input book or fictional
    // party identities that the old source never recorded.
    assert_eq!(first.world.supplier_operations.version, 0);
    assert!(first.world.companies.is_empty());
    assert!(first.world.party_leadership.is_none());

    let canonical_archive = storage::encode(&first).unwrap();
    let mut resumed = storage::decode(&canonical_archive).unwrap();
    assert_game_equal(&first, &resumed);
    let date = first.world.date_str();
    assert_eq!(
        first.advance_days(1, vec![]),
        resumed.advance_days(1, vec![])
    );
    assert_ne!(
        first.world.date_str(),
        date,
        "A real daily continuation must advance"
    );
    assert_game_equal(&first, &resumed);
    let reloaded = storage::decode(&storage::encode(&first).unwrap()).unwrap();
    assert_game_equal(&first, &reloaded);
    assert_eq!(
        std::fs::read(&path).unwrap(),
        original,
        "External evidence was modified"
    );
    eprintln!(
        "S05 MASTER ARCHIVE: {} | original {} | continued {} | nations {} | contractors {} | history {} | original operational state retained; prospective supplier and party capabilities remain absent",
        path.display(),
        date,
        first.world.date_str(),
        source_nations.len(),
        first.world.sector_contractors.roster.len(),
        first.history.len()
    );
}
