//! Opt-in, disposable diplomatic-inbox fixture. This is deliberately authored
//! test state, not evidence of offers generated by an ordinary campaign run.
use super::*;
use serde_json::{json, Value};
use spheres_sim::{agency, commitment, statecraft, war};
use std::{fs, io::Write, path::Path};

fn exclusive(path: &Path, bytes: &[u8]) {
    let mut file = fs::OpenOptions::new().write(true).create_new(true).open(path).unwrap();
    file.write_all(bytes).unwrap();
    file.sync_all().unwrap();
}

#[test]
#[ignore = "Exports authored native inbox archives only to a NEW SPHERES_S10D_INBOX_FIXTURE_DIR"]
fn s10d_export_disposable_diplomatic_inbox_fixture() {
    let destination = std::path::PathBuf::from(std::env::var_os("SPHERES_S10D_INBOX_FIXTURE_DIR")
        .expect("Set SPHERES_S10D_INBOX_FIXTURE_DIR to a new disposable directory"));
    assert!(destination.is_absolute(), "The fixture destination must be absolute");
    assert!(!destination.exists(), "Never overwrite an existing fixture or save directory");
    let mut g = Game::new(13, Some(NationId::France));
    fresh_play_rules(&mut g).unwrap();
    // Authored preconditions, explicitly disclosed in the exported manifest.
    // Actual proposal functions below still enforce their native hard rules.
    g.world.statecraft.pacts.clear();
    g.world.statecraft.trade.clear();
    g.world.sanctions.clear();
    g.world.nation_mut(NationId::France).political_capital = 100.0;
    for other in [NationId::Japan, NationId::Brazil, NationId::Kuwait] {
        g.world.set_relation(NationId::France, other, 98.0);
    }
    statecraft::propose_trade(&mut g.world, NationId::Japan, NationId::France).unwrap();
    statecraft::propose_pact(&mut g.world, NationId::Brazil, NationId::France).unwrap();
    let (a, b) = if NationId::France < NationId::Kuwait {
        (NationId::France, NationId::Kuwait)
    } else { (NationId::Kuwait, NationId::France) };
    g.world.statecraft.pacts.push(spheres_sim::world::Pact { a, b, since_year:1990, since_month:1 });
    let theatre = war::theatre_between(&g.world, NationId::Iraq, NationId::Kuwait);
    let cid = commitment::open_conflict(&mut g.world, NationId::Iraq, NationId::Kuwait, theatre).unwrap();
    let index = g.world.conflicts.iter().position(|c| c.id == cid).unwrap();
    let mut conflict = g.world.conflicts.remove(index);
    agency::offer_call(&mut g.world, &mut conflict, NationId::France, 2, true);
    g.world.conflicts.insert(index, conflict);
    assert_eq!(g.world.agency.offers.len(), 3);
    assert!(g.world.agency.offers[2].expires_day < g.world.agency.offers[0].expires_day);
    resources::warm(&mut g.world);
    g.history.clear();
    g.snapshot();
    // Normalize exactly as the browser's ordinary campaign Load will do.
    let mut g = storage::decode(&storage::encode(&g).unwrap()).unwrap();
    let before = storage::encode(&g).unwrap();
    let initial_world = save(&g.world);
    let before_state = state_json(&g, None);
    let offers = agency::view(&g.world, NationId::France).offers;
    assert_eq!(offers.len(), 3);
    let mut quotes = Vec::<Value>::new();
    for offer in &offers {
        assert!(offer.accept_blocked.is_none(), "Authored offer {} must be legally answerable: {:?}", offer.id, offer.accept_blocked);
        for accept in [true, false] {
            let command = json!({"kind":"respond_diplomacy","offer":offer.id,"accept":accept});
            let quote = decision_review::preview(&g, NationId::France, "decisions", &command);
            assert_eq!(quote["valid"], true, "{quote}");
            quotes.push(quote);
        }
    }
    assert_eq!(save(&g.world), initial_world, "Native previews must preserve all authored world state");
    let accepted_offer = offers.iter().find(|o| o.from == NationId::Japan).unwrap();
    let command = json!({"kind":"respond_diplomacy","offer":accepted_offer.id,"accept":true});
    let quote = decision_review::preview(&g, NationId::France, "decisions", &command);
    let payload = json!({"session_id":g.session_id,"client_id":"s10d-native-fixture","request_seq":1,
        "commands":[command],"review_kind":"decisions","review_token":quote["review_token"]});
    let result = transport::immediate_request(&mut g, &payload).unwrap();
    assert_eq!(result["errors"], json!([]));
    assert_eq!(g.world.agency.history.len(), 1);
    assert_eq!(g.world.agency.history[0].offer.id, accepted_offer.id);
    assert_eq!(g.world.agency.history[0].outcome, "accepted");
    assert_eq!(g.world.relation(NationId::France, NationId::Japan), 100.0);
    assert_eq!(g.world.trade_depth(NationId::France, NationId::Japan), 0.05);
    let after = storage::encode(&g).unwrap();
    let loaded = storage::decode(&after).unwrap();
    assert_eq!(save(&loaded.world), save(&g.world));
    assert_eq!(loaded.log, g.log);
    assert_eq!(loaded.history, g.history);
    let after_state = state_json(&g, None);
    let manifest = json!({
        "version":1,"fixture":"s10d-authored-native-diplomatic-inbox",
        "compiled_revision":env!("SPHERES_REVISION"),
        "scope":"Disposable authored transaction and UI fixture. Not an ordinary campaign, historical treaty, simulated war or campaign-certification duration result.",
        "authored_preconditions":["Integrated fresh France, seed 13, zero days advanced", "All starting defense pacts, trade agreements and sanctions cleared", "France political capital set to 100 and relations with Japan, Brazil and Kuwait set to 98", "A France-Kuwait defense pact authored for a native Iraq-Kuwait test conflict"],
        "native_actions":["Japan proposes trade to France through statecraft::propose_trade", "Brazil proposes defense pact through statecraft::propose_pact", "Native Iraq-Kuwait conflict and 7-day guaranteed France reply queued after the 30-day treaties", "Preview all six answer choices, then accept Japan trade through the protected native review transport"],
        "player":"France","date":before_state["date"],"days_advanced":0,
        "before_file":"before.json","expected_after_file":"expected-after.json",
        "command":command,"quotes":quotes,
        "before_agency":before_state["agency"],"after_agency":after_state["agency"],
        "before_log":before_state["log"],"after_log":after_state["log"],
        "before_dispatch_count":before_state["dispatch_count"],"after_dispatch_count":after_state["dispatch_count"]
    });
    fs::create_dir(&destination).unwrap();
    exclusive(&destination.join("before.json"), before.as_bytes());
    exclusive(&destination.join("expected-after.json"), after.as_bytes());
    exclusive(&destination.join("manifest.json"), serde_json::to_string_pretty(&manifest).unwrap().as_bytes());
    println!("S10D_FIXTURE_MANIFEST={}", destination.join("manifest.json").display());
}
